### ISSUE TITLE
Mop up test won't start if the test is open before candidates are added

### ISSUE THREAD

**Issue by mbrookeswebdev** [jac-uk/admin#1017]
It is possible to open a test before candidates are added and then test wont start. Perhaps its best to disable Open Tests button until candidates are added (?)

**Comment by mbrookeswebdev** [comment]
![Mop up3.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/fe08c55b-45d8-4368-9909-858116b2d528)![Mop up4.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/2536c91a-bb70-4fb4-a141-670d2a93eaa5)

**Comment by warrensearle** [comment]
This is a good spot, thanks @mbrookeswebdev
