### ISSUE TITLE
Filtered qualifying test reports (for 00037)

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1020]
The team for 00037 have to have two separate lists of merit for the QT they have. 

They need a list for the Employer tribunal.

And a list for the Employee tribunal.

These will need to be downloaded as well. 

The following question is the one that needs to inform which list a candidate goes onto: Do you wish to be considered for the employer panel or the employee panel? Please note that you are only able to apply for one panel.

This needs to be in place by **11 November**

---

The plan here is to enable an Admin to define a subset of data to be included in a qualifying test report. In this instance we will then be able to create one report for Employer Panel and another report for Employee panel.

Defining the subset of data will be enabled by offering the Admin a selection from the possible Working Preferences answers available in the exercise. We have Location, Jurisdiction and Custom working preference questions available to be configured for an exercise.

**Comment by warrensearle** [comment]
Have implemented a 'Jurisdiction Filter' on the report Edit form as follows:
![Screenshot 2020-11-12 at 01.05.40.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/0bf023b0-32c8-482d-bb59-e5592d33f054)

This restricts the report to only include candidates matching the chosen filter value.
![Screenshot 2020-11-12 at 01.07.23.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/ac6c5a0a-eb40-4a8f-be8d-8107ea0f318e)

Including similar filters for Location and Custom preferences can be tackled under future tickets, as they are not yet needed (and may never be).
