### ISSUE TITLE
Held fee-paid judicial role needs to be a column heading in export from applied

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1055]
As an admin I need to be able to clearly see who has and has not held a Held fee-paid judicial role. The only place this is captured is in the equality and diversity questions where it asks Have you held fee-paid judicial role? The export from applied needs to have this information as one of the headings and capture it as yes/no 

https://admin.judicialappointments.digital/exercises/D7vODO7AVyTTlctVmA5Y/applications/applied
Export contacts

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle could you get someone on this fix - please let me or @joy-ade know if any questions.

**Comment by mbrookeswebdev** [comment]
Confirmed with @Rebecca-mcknight1991 , need to include Prefer not to say option as well.

**Comment by mbrookeswebdev** [comment]
Confirmed with @Rebecca-mcknight1991 , use 'Unknown' for empty/null or undefined values.
