### ISSUE TITLE
Covering letter, CV and SoS not showing for High Court on admin 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1057]
**Describe the bug**
Statement of Suitability, Covering letter and CV on High Court exercise number 00020 not appearing on the admin side to download. File clearly showing as received on Apply and my application has been sent. 

**To Reproduce**
1. Go to https://admin.judicialappointments.digital/exercises/UlI71xkfeF20vAvYbE29/applications/applied
2. Click on applied, click any application reference number 
3. Scroll down to find Statement of Suitability, CV or covering letter. 

**Expected behavior**
The team needs to be able to download all 3 of these documents. 

**Screenshots**
![Screenshot 2020-11-09 at 15.28.37.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/b2d273f6-4f36-408a-a17a-b62f0d1fc3c7)

![Screenshot 2020-11-09 at 15.32.04.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/3b53fce0-1527-46ba-af5d-403e94e2a49b)

![Screenshot 2020-11-09 at 15.32.11.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/e794b5a5-f84d-4021-84b2-67b3bf154f9b)![Screenshot 2020-11-09 at 15.32.17.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/3f276b54-de3f-4190-99da-bb2ccc278cc8)
![Screenshot 2020-11-09 at 15.32.21.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/06f47a1e-916f-442f-a46a-ef6096d12200)![Screenshot 2020-11-09 at 15.32.24.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/bef2eb5a-52bf-4b61-a584-1baea82601b2)

**Additional context**
Very high profile exercise so needs resolution asap.

**Comment by warrensearle** [comment]
Hey @Rebecca-mcknight1991 this is part of hotfix 0.42.1. Have checked and the files are now showing up. Please review on production.
