### ISSUE TITLE
Add extension date in Application 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1063]
As an admin I need to be able to extend the application window for certain individuals without reopening the exercise. 

1. Admin goes into draft applications AND applications list
2. Admin should be able to go into the application reference number of the relevant candidate
3. At the top of the application they see an option for 'Give Extension'

![Screenshot 2020-11-19 at 12.46.58.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/d86ab475-713a-4c70-ac0e-3bb6c906d5a7)

4. Modal appears
5. Input new deadline date, time and reason for extension (would the reason come from the notes tab?) 
6. Save 
7. Give extension changes to 'Edit extension' 
8. Date of extension appears somewhere - leave to your creativity (in grey box too?)

**Comment by lloback** [comment]
Changes on this ticket included:

		○ - Added .npmrc file in order to use JAC-KIT
		○ Added the jac-kit to the ADMIN app
		○ Changed the EditableField component to allow Objects as values (for date
		○ EditableField: Fixed Bug where the Link was not showing orrectly
		○ Removed the Modal COmponent from the admin repo
		○ Changed NOTES to allow application level notes
		○ removed the CSS from the admin repo
		○ Added the CSS from the Jac-kit
		○ Created the DATE EXTENSION in the application
		○ Added the modal from the jac-kit to Indepedenten Assessment

**Comment by Rebecca-mcknight1991** [comment]
@lloback this looks great.
