### ISSUE TITLE
Add any numbers of documents to exercise downloads 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1066]
The exercise downloads page needs to be redesigned. 

There should be a drop down menu for the type of document you are uploading with the following options:
Job Description *
Terms and Conditions *
Competency Framework *
Pension Information *
Skills and Abilities Criteria 
Independent Assessment Form *
Candidate Assessment Form *
Welsh Translation 
Other

A box should then appear allowing them to name the document. They might need to upload more than one document under a heading e.g. 2 documents under Pension Information. 

The number of documents upload-able should be unlimited. They just need to add another as they do now. 

They should be able to save and continue but get a message at the top to save and continue anyway to check they want to save and continue anyway if one of the italics items if not uploaded. 

To the candidate these documents still appear under 'Related Content'.

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub confirm file type and size we support at the moment. Thanks.

**Comment by Rebecca-mcknight1991** [comment]
@lloback @warrensearle this looks good but we need the required documents to be changed. I've realised only really the Job Description, Terms and Conditions and Independent Assessment form should be required. And they should be required but still allow someone to save and continue whilst they await the arrival of documents. At the moment I cannot continue and more than these 3 are required. Thanks. If that could be sorted before this goes onto production that would be great.

**Comment by joy-ade** [comment]
@Rebecca-mcknight1991 @lloback @warrensearle 

Many thanks for this Becky l did review the ticket too and Welsh Translation, Skills and Abilities Criteria and Competency Framework are all made mandatory, you have to fill all before you continue.
