### ISSUE TITLE
Display responses provided in a previous test

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1077]
If a qualifying test response is reset or moved to a mop up date then answers provided so far are retained however these are not currently displayed in the Responses view.

It is useful to see this information to adjust the time given to the candidate

---

e.g.

Here's a test with answers
![Screenshot 2020-11-23 at 12.46.15.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/cd0aa146-2a75-4ee4-98ac-7d14c816d467)

Here's the same test after it has been Reset
![Screenshot 2020-11-23 at 12.46.29.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/3fdfb1f6-95e3-4c78-9e6e-2114585dbfc8)

---

**Actual**
Answers are not displayed

**Expected**
Answers should be displayed, along with date stamps and durations

**Comment by lloback** [comment]
raised PR: https://github.com/jac-uk/admin/pull/1259

**Comment by warrensearle** [comment]
@KateMJAC this was previously approved by developers just, potentially, needs UTG approval.... so have moved to Code Approved

**Comment by KateMJAC** [comment]
Sent to the UTG for testing today - 1/07/21. Awaiting feedback.
