### ISSUE TITLE
Static Reports: Preferences and Salaried Part time working, Welsh

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1078]
As part of #849 and digital-platform#360 we now have stats, counts and reports available.

This task is about exposing that data. The user will select which stats they're interested in and view the corresponding results on-screen and will also be able to download into an excel spreadsheet..

Note: This task has been sized to cover setting up the report and presenting the MVP, easier to access, data. There may be additional tasks in the future to include some of the data from harder-to-reach places.

---

For example it can be helpful to see how many candidates speak Welsh very quickly or which jurisdictions they have applied for. 

Can we have drop down bar to filter candidates in the below categories:

[ ] Location Preferences
[ ] Jurisdiction Preferences
[ ] Additional Preferences
[ ] Welsh Post
[ ] Qualification
[ ] Post Qualification Experiences
[ ] Gaps in Employment
[ ] Reasonable length of Services
[ ] Leadership Judge details
[ ] Independent Assessors
[ ] Additional selection categories
[ ] Self  assessment competencies
[ ] Statement of suitability  

There is not an exact science to what the team may need to see and therefore it might be most sensible that using the filter they can choose to see any of the fields within the application form except for personal information outside of the name of the candidate and reference number (that includes reasonable adjustments which are captured in a separate report) and the equality and diversity information which is captured in that report and in the contacts download. 

This is an on screen report and they just need to clear see the numbers of candidates for the criteria they have decided to see in the report and Admin should be able to download data  in an excel spreadsheet.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle How would I get this into like a 5 and a 3?

**Comment by KateMJAC** [comment]
If we are unable to create a filter so that admins can choose to see any of the fields within the application form, we will need to go to the Design Group to workshop what reports are essential/required.

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by KateMJAC** [comment]
hello @warrensearle is there an update on this ticket?

**Comment by JeremykJAC** [comment]
Can we make this report downloadable - following convo with Joy and Kate.

**Comment by JeremykJAC** [comment]
- [ ] Add video recording

**Comment by JeremykJAC** [comment]
https://www.loom.com/share/57c3e099214540e4a13ef303de1905ab

**Comment by JeremykJAC** [comment]
https://www.loom.com/share/8cdfbd0cfc864e20ad5ee2fffaff1317
