### ISSUE TITLE
Cannot upload files on behalf of Candidates

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1090]
**Describe the bug**
As an admin user I cannot upload a file on behalf of a candidate. 
This includes, but is not limited to, Self Assessment and Statement of Suitability.

**To Reproduce**
1. Go to an Applied application for an exercise which requests files from candidates (see assessment options)
2. Scroll to the bottom of the application and click to replace or upload a Self Assessment, say
3. Choose a .docx file
4. See error in screenshot below

**Expected behavior**
File should successfully upload

**Screenshots**
![Screenshot 2020-11-26 at 18.07.27.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/4ca12826-2e09-4a82-9f22-5abd43750d4e)

---

This is either an issue with uploading to the wrong place (admin app) or a storage permissions issue (digital platform).
It is likely a consequence of recent work to enable Admins to upload files on behalf of Assessors

**Comment by warrensearle** [comment]
This has been fixed by updating storage security rules.

However there's another related bug happening straight after a file is successfully uploaded, as follows:

![Screenshot 2020-11-26 at 18.23.02.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/a611912a-2783-466c-88a4-e9e50c290722)

Sounds like we're amending vuex state directly rather than via a mutation function

**Comment by warrensearle** [comment]
@lloback I've fixed the security rules issue. Could you look at the second issue mentioned in comment above?
Thank you :)

**Comment by lloback** [comment]
This is ready to review on PR/
