### ISSUE TITLE
Change to diversity report 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1110]
As a member of the Diversity and Engagement team I need to be able to see withdrawals in the diversity report up until the point they withdraw. 

ie. if Becky applies for Recorder but withdraws after selection day I need to see her in the figures except after selection. 

If Joy applies and withdraws before shortlisting she needs to be in applied stats but not beyond then.

**Comment by warrensearle** [comment]
The report has been updated to also include withdrawn applications.
The same change has also been applied to the outreach report.

Note that we don't currently display a report on the withdrawn candidates. I propose we include a new tab called 'Withdrawn' that explores the stats for this group of candidates. @joy-ade could you check whether this would be a useful feature and if so write up a new ticket for this work. It would be a 2 story point task.

**Comment by joy-ade** [comment]
@warrensearle this ticket has been reviewed.
