### ISSUE TITLE
Working Preference  (Exercise 048 Launching on 13th Jan)

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1116]
As an Admin l want to add another question to candidate working preference "which role are you applying for"  so that l can know candidate working preference 

As an Admin l want candidate to answer question with single choice and candidate should  then click save  and continues.

As an Admin  I want  candidate single choice answer to be saved so that when candidate scroll back their answer are saved.
![Working Perference 1.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/98aafc4e-270f-420f-8657-2ecc091d9d45)![Working Perference 2.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/96118308-9392-4da5-9f02-c9e2c61e4328)

**Comment by warrensearle** [comment]
This looks like a bug where the question type is not being maintained when there is kore than one custom question.

![Screenshot 2021-01-04 at 10.06.13.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/542ed9fd-a309-44c8-bfef-db5185609e9b)
