### ISSUE TITLE
Exporting Welsh Report

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1121]
Exercise JAC00021

As an Admin l want to  generate report so that l can know how many candidate applied for welsh Post.

NOTE:- James wants to know  which candidate apply for welsh post. So that they can start allocating interview slots.

**Comment by joy-ade** [comment]
@warrensearle I have updated the ticket. I spoke to James all he needs is information of candidates that applied for Welsh post

**Comment by warrensearle** [comment]
Thanks @joy-ade I have emailed you with the results of this query. As mentioned we are aiming to allow the team to query for data like this as part of #1078 but that is a way off.

Please check and update this ticket to Done if all is satisfactory.
