### ISSUE TITLE
Import scenario test scores

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1122]
## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## Risk - how likely is this to impact other areas?
🟢 Low risk 

## Additional context

As an admin
I want to provide scores for a scenario test
So that I can rank and continue processing the best applications

---

In this iteration the scores will be decided offline and be available in a spreadsheet with the following format:

```
applicationRef | scoreQ1 | scoreQ2 | ... | totalScore
```

In the future we will support scoring test answers within Admin (or a separate targetted App)

---

For Scenario Test replace the 'Close & Score' button with an 'Import Scores' button. This will open a page/modal to upload the scores spreadsheet and confirm column mappings (n.b. there may be multiple sheets in which case the user will need to confirm the sheet).
A cloud function will help here and (when all is ok) import the scores data. 

[TODO more detail on UI]

**Comment by KateMJAC** [comment]
Discussed as part of the QT II epic today. It was agreed that this ticket was a priority to be included in April's work.

**Comment by JeremykJAC** [comment]
https://admin.judicialappointments.digital/exercises/BBjcdF0pJqcbPuEwU0a2/tasks/qualifying-tests/bhaXCWnfzkxj3JkpT11G/

**Comment by JeremykJAC** [comment]
After feedback in the Standup this issue is now on hold

**Comment by KateMJAC** [comment]
@HalcyonJAC  Based on discussions at the 02/07/21 Digital Stan-up, we will not need to continue with this work due to Dries work on the Merit list and UI to enter scored directly onto the platform.

**Comment by JeremykJAC** [comment]
This is being superseded by work Warren has been asked to do with punching these figures onto the platform rather than via an upload
