### ISSUE TITLE
Update status of custom selection

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1123]
As an admin
I want to choose specific applications and update their status (perhaps under EMP)
So that I can ensure candidates have the correct status

---

This is part of the QT Scores Report and enables admin to choose which applications to amend as having passed/failed a test (for example).
It is very similar functionality to Stages & Statuses and could link to the same Update Status form (providing the back navigation returns the user to QT Report)

**Comment by KateMJAC** [comment]
Hello @warrensearle can this ticket be closed? 

The ticket seems to be covered to the QT results epic #881 and #933.

**Comment by warrensearle** [comment]
This ticket is still valid. The epic breaks down into lots of smaller tasks including a task around collecting the cut-off score to update qt results (#933) and a task around updating the status of a custom selection of qt results (this one).

**Comment by KateMJAC** [comment]
Discussed as part of the QT II epic today. It was agreed that this ticket was a priority to be included in April's work.

**Comment by JeremykJAC** [comment]
https://admin.judicialappointments.digital/exercises/BBjcdF0pJqcbPuEwU0a2/stages/review/edit

**Comment by JeremykJAC** [comment]
Further clarity from Warren needed
