### ISSUE TITLE
Vacancy Page Date Display Error when using Safari

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1128]
**Description of bug**
Users see the error message ‘Invalid Date NaN’ next to the launch date field when viewing the Future Applications section of the live vacancy page via Safari on an iOS device. 

The error message is only occurring on exercises that have the month of launch listed only and not for exercises that list a full date e.g. 1/6/21. 
The bug has been reproduced using Safari on a Mac, iPad and I phone, however it does not occur when using Chrome on a Mac or Firefox on a Dom1 thinkpad to view the live vacancy page. 

**To reproduce** 
1)	Visit https://apply.judicialappointments.digital/vacancies using safari on an iPhone/iPad/Mac.
2)	Click vacancies within the menu options.
3)	Scroll to Future Applications and the error is displayed under the first exercise, Fee Paid member of the First Tier Tribunal General Regulatory Chamber assigned to the General Regulatory Chamber (Environmental jurisdiction). It is also displayed on three other exercises listed under Future Applications. 

**Expected behaviour**
The month of launch should appear. 

In the case of Fee Paid member of the First Tier Tribunal General Regulatory Chamber assigned to the General Regulatory Chamber (Environmental jurisdiction), this should be March 2021. 

The launch months of the other three exercises are accessible by viewing the vacancy page on a thinkpad or by using Chrome on a iOS device. 

**Screenshot**

![Safari Bug.jpg](https://images.zenhubusercontent.com/5fcfacf3d4e677f3af4fdecb/4a2b98ca-4169-412b-b2df-18da83f4ae21)

**Comment by warrensearle** [comment]
Hey @mbrookeswebdev this one looks right up your street :)

**Comment by mbrookeswebdev** [comment]
Issue moved to [jac-uk/apply #677](https://github.com/jac-uk/apply/issues/677) via [**ZenHub**](https://www.zenhub.com/)
