### ISSUE TITLE
Create Panel

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1130]
### 1. Area on the Tasks on the Left, with 2 new links "SIFT" and "SELECTION DAYS"
<img src="https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/140514b6-131c-4d67-be72-165ecce9e043"  width="250"/>

### 2. A list of the Panels Already Created with a link to the specific Panel
<img src="https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/96537b23-1110-4f7c-a491-60e814c38551" width="250"/>

### 3. A view with the form to create a new Panel
<img src="https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/ad88d41c-d075-4768-bc2c-fe0477f61f39" width="250"/>

====================

As an admin, I need to create task area called ‘Panels’, where I can create panels and allocate panel members for specific activities at different stages of an exercise, these stages include:

•	eligibility sift
•	paper sift 
•	selection days (interviews). 

I need this functionality to be integrated with Google Drive so that content and files can be copied over into folders for panels to review.  

The number of panels I need to create will vary depending on the exercise and what exercise activity is taking place. It could be one panel or 10+.  

I need to name the panels using the following convention, ‘Panel 1’, ‘Panel 2’, ‘Panel 3’ etc, but this may change in the future.  

As an exercise moves from one activity to another, I may need to create more than one set of panels, which may consist of different panellists. To avoid confusion, I need a way to clearly connect a panel/set of panels to a specific activity within the ‘Panels’ task area. 

Once the Panel/s are created, I need to add panellists to their allocated panel. Panels can consist of a different number of panellists depending on the exercise, so I would need an option to assign the following panellist roles in the event we have four or more panellists: 
•	Chair
•	Independent
•	Judicial
•	Other

I will need to assign each panel member to their role and identify them by their full name and  JAC @digital email address.

**Comment by KateMJAC** [comment]
Hello @lloback, following our discussion on Monday and reviewing the prototypes I wanted to flag whether the below was possible: 

Can a delete panel option also be provided?

At the sift stage, the create panel fields will need to display ‘sift panel dates’ and not ‘interview dates’ as shown in the prototype above. Is this easy to make bespoke to each stage or do we need to keep it generic and just use ‘date’? The most likely scenario is that the dates will be a range, however there may be instances where there is only one day of activity.
