### ISSUE TITLE
Assign Candidates to Panel

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1131]
### 1. List all candidates
For a sift it will be the all the candidates on the REVIEW state
For SELECTION DAY it will be all the candidates in the SHORTLISTED state
<img src="https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/ceb4938a-4456-49f1-bc6b-010f5a2551b4" width="250"/>
<img src="https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/270b20a3-d265-4c6e-af67-9d538929c375" width="250"/>

=============================

As an admin, at different stages of an exercise, I need to assign candidates to a particular panel so that panellists can be provided information related to the candidates they are assessing. 

The number of candidates I need to add can vary across exercises and exercise stages, so there shouldn’t be a minimum or maximum number of candidates that can be assigned to each panel. 

Candidates will be allocated at different stages of an exercise, so an assign button in each of the stages on the platform will allow me to click the check box and add the candidates I want to each panel listed within task area. 

When assigning candidates to a panel at the eligibility sift or paper sift stages I will need name blind capability. In a name blind scenario, candidates should be identified using the characters that appear after the dash within their unique identifier. Eg, if their unique identifier is JAC00351-fiz0003  we need to use fiz0003. 

When assigning candidates to a panel for selection days (shortlisted stage) I will need to use the candidates’ full names.

**Comment by KateMJAC** [comment]
@lloback for your info, I reached out to our senior appointments team to confirm whether they always run name blind sifts. They confirmed that there will be some circumstances where candidates are identified by name at the sift stage. This means that the panel will need to receive the panel packs with documents that haven't been redacted. 

Based on this confirmation, can we please allow an option at the sift stage to transfer candidate applications/documents and create a file on Google Drive, both with name blind capability and with the capability to display the candidates name?

**Comment by KateMJAC** [comment]
@lloback Can you please confirm that we will have the capability to remove a candidate from one panel and allocate them to another without causing any duplication of candidates across numerous panels? 

An admin would need an option to select a candidate allocated to one panel and reallocate to another panel thereby removing them from the initial list under the first panel, or an ability to delete them from the originally allocated panel and then to go back into the main candidate list to allocate them to a new panel. 

Raising the above off the back of a question I received at today’s digital drop-in.

**Comment by lloback** [comment]
Yes. We willl be able to remove the candidates from ine panel and add to others
