### ISSUE TITLE
Update Character Issues report to reflect new character information data

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1139]
Now that character information has grown considerably in apply#563 we need to update the Character Issues report.
We will also revisit the data model for how we store character issues on `applicationRecord`.

**Comment by KateMJAC** [comment]
Assigned to Halcyon's March WO.

**Comment by KateMJAC** [comment]
Maria is able to provide information in relation to the new character information data.

**Comment by HalcyonJAC** [comment]
I think I have found a bug:

I have applied for 2 exercises locally. When I get to the Character Information page the input boxes have the same values in them whatever I do.

For example, I opened an application for exercise 'P4BWVWQBynf72vwboUg6' and filled in the character info section - see below:

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/2eadbd88-ef0d-44b5-8bfc-6255920dcfa9)

...if I then load my application (which was in progrss) for exercise 'mzdAdY3zBAAQkbHGOJgg' I see the input boxes have the same values in them for some reason:

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/54b3ae0f-2b1a-410a-ba2e-55c044d7ec59)

**Comment by HalcyonJAC** [comment]
Hi

I have updated the flagApplicationIssuesForExercise endpoint to use characterInformationV2 when appropriate - this is in issue #515 on the digital platform, which populates the character issue info in the `applicationRecords` collection.

The admin portal now needs updating too though as it currently looks for the character info data in the `allocations` collection. There may be other changes related to this also, in issue #1071

**Comment by HalcyonJAC** [comment]
Note: A few weeks ago this ticket was put on hold as @warrensearle has/had another ticket open where he was altering the code in the backup routines for some reason.

Once @warrensearle has finished updating the backup routine, this ticket can be resumed

**Comment by warrensearle** [comment]
Have un-blocked this. The fix in #1071 is to ensure the UI is looking at the `applicationRecords` collection instead of `applications`. This has been applied in the following PR #1337

**Comment by HalcyonJAC** [comment]
Digital Platform - `exportApplicationCharacterIssues` function needs to look at `applicationRecords` instead of `applications`

**Comment by HalcyonJAC** [comment]
There are some additional requirements for this report, @joy-ade to provide details shortly...

- [ ] On-screen report and export to both use Character Info v4 (which is what this ticket was originally for)
- [ ] Ability to be able to filter the report/export by stage (i.e. selected candidates only)
- [ ] Add the following fields to the export:
  - TBA
  - TBA
  - TBA
