### ISSUE TITLE
Approach to implementing user roles

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1147]
We need to agree our approach to implementing User Roles in the digital platform.

[This ticket will be updated with the approach we will take.]

**1. How do we manage user roles?**
We will include a Users area in the admin app. This will list all Users and their Role.
It will be possible to select individual and multiple users (using existing Table component multi-select) and set/change their role

**2. What data model (if any) do we use?**
We will introduce a new `Users` collection. Each document's ID will match the user's auth ID and each document will contain the following fields only:
- `displayName`
- `email`
- `role`

**3. How do we know the current user's role?**
We will use a custom claim on the user's authorisation token called `role`.
`role` will have the following values:
- `'admin'` will be basic admin user
- `'manager'` will be manager role
- `'superadmin'` will be super admin

**4. How shall we get the Admin UI to reflect the current user's role?**
We could use the PermissionsPlugin, which checks whether a user has permission to access resources. Buttons, forms etc could be conditionally displayed, depending on the result and navigation guards could be used to restrict access to routes.

**Comment by warrensearle** [comment]
@mbrookeswebdev the following links are worth a read with regards how we could implement user roles in the Admin UI.

**Global helpers/plugins in Vue:**
https://medium.com/js-dojo/registering-globally-your-helpers-in-a-vue-app-b7ba3b9596b3
https://vuejs.org/v2/guide/plugins.html

**Examples of what others do:**
https://vuejsdevelopers.com/2018/01/08/vue-js-roles-permissions-casl/
https://medium.com/@aimme/very-simple-way-to-manage-permissions-on-vue-js-6ecbf930c0aa
https://casl.js.org/v5/en/package/casl-vue

**Comment by mbrookeswebdev** [comment]
I've created a plugin that checks if a user has a permission, [here is the link to the branch](https://github.com/jac-uk/admin/commit/9fbbcb6d87d9f016a60e23a7c0b579b984fe8e35).

**Comment by warrensearle** [comment]
I'd say this task is done. The above approach / outline can be included in the Epic ticket, say, and used for implementation tasks.
Have moved back to 21JANA milestone as that's where the majority of the work happened.

**Comment by mbrookeswebdev** [comment]
[There is a branch in Admin repo with some prototype code written for ticket 1147](https://github.com/jac-uk/admin/tree/feature/1147-approach-to-implementing-user-roles).
