### ISSUE TITLE
Withdrawn Candidate 

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1156]
On Exercises 0026
A candidate withdraw from the exercise after selection day. The status was updated to reflect the changes but candidate is still showing under shortlisted stage.

![Capture.PNG 14.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/1fd29af1-83fb-4fb1-8e61-a86fdb2c9d99)![Capture.PNG15.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/3a58c336-8cb3-4b6c-84b1-f10e5157a2d5)

**Comment by joy-ade** [comment]
@KateMJAC  can you take a look at this ticket pls. Its hasn't been assigned to anyone.

**Comment by warrensearle** [comment]
Hey @joy-ade and @KateMJAC I believe this is expected behaviour. Withdrawn candidates should remain in the last stage/status they were in when they withdrew. Please confirm if this has changed.

**Comment by KateMJAC** [comment]
@warrensearle i'm unable to recall if the Selection Exercise Manager (SEM) who reported the issue advised this was impacting their final statistics or if they just thought that the candidate should be removed from the 'shortlisted' stage. 

Either way, there hasn't been a change in process to my knowledge, so it is possible that this is a misunderstanding on behalf of the SEM. 

@joy-ade are you able to clarify with the SEM that the candidate should remain in the 'shortlisted' status to determine whether there is still an issue beyond that?

**Comment by joy-ade** [comment]
@Warren Exercise 0027 The candidate withdrew from the exercise after selection day. The SEM updated the platform to reflect this, but it is still showing under stages as shortlisted. SEM wants to provide updated diversity report for the SCC paper. SEM updated the candidate's status on platform to withdrew but Candidate's details was still showing under stages as shortlisted.

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by warrensearle** [comment]
@KateMJAC after having further discussion with @joy-ade I think we agreed this is expected behaviour, therefore there's no work to do and the ticket can be closed.
