### ISSUE TITLE
Diversity Report 

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1157]
Exercise 00011

The final statistical report - the figure for post application for disabled and  professional background does not add up. There is an incorrect calculation for  number of candidates  and percentage on all exercises on the platform.
 ![Capture Stat report a Bug.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/2331093f-38c1-469c-b6f3-d382cd8027c0)

**Comment by joy-ade** [comment]
@KateMJAC  Could you check this ticket pls?

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by warrensearle** [comment]
Hi @joy-ade following our discussion earlier I suspect this ticket can be closed.

**Professional Background** is a multiple choice question therefore the percentages and totals next to each answer can add up to more than 100% of the applicants.

**Social Mobility** is a grouping of independent questions so the percentages / totals should not be combined.

**Comment by joy-ade** [comment]
@warrensearle  Thanks  for the update. I will close the ticket accordingly.

**Comment by warrensearle** [comment]
@joy-ade there was a data issue with ex 0014 which has been resolved as part of this ticket

**Comment by joy-ade** [comment]
Thanks @***@***.***> for looking into the issues and fixing it.
