### ISSUE TITLE
Handover Report - 9th February.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1160]
There are errors in the data when downloading  handover report the data in some columns does not represent what the field title are.  The screen shoot below in for exercise 025, columns A-k is correct while Columns "L" onward doesn't align with the field title!   The team need this fixed by 9th of February they will send out handover report on this date.

Note: Current Address field does not apply. The data wasn't provided by the candidates

**Comment by joy-ade** [comment]
@warrensearle can you assign this ticket to Tom or Maria. The issues has been flagged out by two exercise teams pls.

**Comment by warrensearle** [comment]
Sure thing @joy-ade. Is it ok if @tomlovesgithub or @mbrookeswebdev pick this up next sprint, or is it more urgent than that?
