### ISSUE TITLE
QT Test - add a button "Mark as completed"

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1185]
As Super Admin l need to be able to mark a candidate's test as completed.
 
Note:
Add a button "Marked as completed" next to the "Reset" button in the candidate QT area.
Add Joy and Kate as Super Admin Users.
Only Super Admin users should be able to click "Mark as completed" button. 
"Mark as completed" button will change the test status to "Completed".
Start/end date timestamps should be preserved as they are.
![Capture.PNG QT.PNG1.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/a4bc30b0-9404-4be2-a3ff-021e0fd0c5c2)

**Comment by KateMJAC** [comment]
Tested and worked as described above:

- [X] Add a button "Marked as completed" next to the "Reset" button in the candidate QT area.

- [X] Add Joy and Kate as Super Admin Users.

- [X] "Mark as completed" button will change the test status to "Completed".

- [X] Start/end date timestamps should be preserved as they are.

- [X] Only Super Admin users should be able to click "Mark as completed" button.
