### ISSUE TITLE
Firebase Permissions

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1194]
Please speak to KateMJAC regarding the requirements of this ticket.

**Comment by KateMJAC** [comment]
This ticket has now been resolved via the recent work completed by Adam and Tom that has implemented a MS sign-in for the Admin app. Users now have to sign in their .gov.uk credentials.

**Comment by KateMJAC** [comment]
Warren will need to sit down with me to make the required changes due to level of permissions.

**Comment by londonprojects** [comment]
@KateMJAC when is this scheduled to happen?

**Comment by londonprojects** [comment]
@warrensearle Can you help with this?

**Comment by warrensearle** [comment]
@londonprojects we are good to go on this, just need to arrange a mid-week day to roll out the changes with @KateMJAC
