### ISSUE TITLE
Ex 051 - Unable to download QT - critical analysis test results

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1198]
**The issue**

As an admin working on exercise JAC00051 – Deputy District Judge (Magistrates’ Court), I am unable to download the responses from the JAC staff dry run of our QT critical analysis test that was held on 1/03/21. 

We also held a JAC staff dry run QT situational judgement test on the same day and we are able to download those results. 

**Describe the solution you would like**

I would like to be able to download the results from the QT critical analysis test – JAC staff dry run held on 1/3/21.

**Comment by mbrookeswebdev** [comment]
To test - 

1. Log into Admin, go to an active exercise, create a Qualifying test, invite test candidates. 
2. Log into Apply as test candidates, complete the test. 
3. Log into Admin, go to the created Qualifying Test, click on Responses and click on Export responses button. ([Apply test script](https://docs.google.com/spreadsheets/d/1ui5XkroLH1UHUgahLuaVrFLQr6afIuAXo1r9cQZRgeE/edit#gid=1815186770), [Admin test script](https://docs.google.com/spreadsheets/d/1BAyEPjLIOQcVFfSCRTsBzDL-lKeQscuFkTAWLJelcvU/edit?usp=drive_web&ouid=104315484718704594540))
4. Make sure it is possible to download responses, check negative behaviour (i.e.skipping questions in a test etc) as well as positive.
5. Make sure all data is present.

**Comment by warrensearle** [comment]
Have reviewed code and approved - with a suggestion for simplifying.

Have also tested against the prod data and it enables ex 51 data to be downloaded

**Comment by HalcyonJAC** [comment]
Hi @mbrookeswebdev @warrensearle  

If this code change is all ok can it be merged as a priority please?

I ask as we are working on the following item at the moment, which will effect this export/download:

#1100 - Exports should be prepared server-side

Locally, I have already created a feature branch off of develop for #1100. Let me know once this pull request has been merged though and I will merge develop into my local feature branch for #1100 to help avoid any merge conflicts coming up when its time to review #1100 ;)

Thanks

**Comment by KateMJAC** [comment]
I have tested this on staging and was able to download CA QT results that included null values. When compairing the download with the responses held on the platform thay corresponded. Null values were displayed in the download as ---, clearly indicating that no answer was provided. 

Everything now works as it should. Thank you Maria.
