### ISSUE TITLE
Deployment improvement – button for JAC to control deployments

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1201]
As a Super User (JAC Staff) I want to click on a button so that l can deploy code to live environment.

This piece of work will enable the senior developer to create a button that will allow JAC staff to deploy to live environment by pressing the button after testing. (Only JAC staff will only be allowed to deploy to live environment) 

Note
create a button to be used by super user to deploy to live environment.
only JAC staff are allowed to deploy to live environment

**Comment by joy-ade** [comment]
@warrensearle this task is created as per conversation and its a top priority ticket to work on. Should you need more information about this ticket do get in touch.

**Comment by warrensearle** [comment]
Great, thanks Joy

**Comment by warrensearle** [comment]
Right now deployments happen by one of the staff developers starting a release branch; staff reviewing the batch of features in that release; and then, when approved, the staff developers finishing the release.

For the first pass of this task we will look to:
- [ ] Evaluate our current pipeline & identify what we could/should improve
- [ ] Include feature-based previews. As these will enable staff to review & approve changes earlier
- [ ] Simplify current release process

We will look to utilise existing tools - e.g. Github Pull Request approvals & Github Actions - to get some easy wins.
That said we will be open to new tools & approaches - e.g. move to Gitlab; use Google Cloud Build; mono-repo; manual triggers - to get the best-fit result.

**Comment by KateMJAC** [comment]
Warren has advised that we need to wait until after 29 April to implement, due to the QT related code freeze.
