### ISSUE TITLE
Display of supporting information during scenario QT

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1204]
**The issue**

As an admin, I have received feedback from participants of the exercise 033 – Recorder 2020 scenario qualifying test (QT) that they experienced difficulties accessing the on-screen supporting materials that were presented via an accordion, which resulted in them losing time scrolling through the materials. 

**Describe what solution you would like considered** 

Views from developers and operations team members have been canvassed and we would like to explore the option to present supporting information of varying lengths (3-20 pages) during scenario QTs via the following two prototypes:

1)	A PDF that either opens in a new window or a new tab. 

We would like to ensure that all the relevant documents are included in one PDF in the order which they will need to be read during the QT, to make it easier for candidates/users. 

2)	Enhancing the current accordion feature so that the user could maintain scroll position, allowing it to go full-screen and allowing highlighting/snippets.

Supporting information is currently presented in Scenario QTs via an accordion. Accordions work well for a few short paragraphs of text, but a large amount of text is hard to read and requires a lot of scrolling. 

We will then conduct user research to see if either of these features meets user needs.

**Comment by JeremykJAC** [comment]
Awaiting a copy of a QT pdf/information we can use to create one - in order to create prototype.

**Comment by JeremykJAC** [comment]
We have come up with two options, each with two variants:

**Option one - PDF in new tab**

When the user clicks on View scenarios this will load a new tab with the supporting documents in a new tab.

Variant one - https://projects.invisionapp.com/d/main?origin=v7#/console/21063170/447205704/preview?scrollOffset=0
Variant two - https://invis.io/H4103VG67QE9#/447205706_Option_1_B

**Option two - on-screen**

The supporting documents are embedded onto the page with the question. The user has the ability to jump to a section via clicking on the paragraph headings to the left of the supporting documentation. 

Variant one - https://invis.io/H4103VG67QE9#/447205705_Option_2_Variation
Variant two - https://invis.io/H4103VG67QE9#/447206325_Option_2_Variation_Scenario_2

**Comment by JeremykJAC** [comment]
- Does this need to work with a screen reader?

**Comment by JeremykJAC** [comment]
- A/B testing in a live enviroment?

**Comment by KateMJAC** [comment]
@JeremykJAC for accessibility I think compatability with a screen reader would be the goal. 

I am unsure whether our current QT set-up works with a screen reader though. 

This work will also need to be A/B tested in a live environment. I believe we will be seeking advice on how to best test this with some end users/candidates.

**Comment by KateMJAC** [comment]
This ticket is complete. The prototypes will beed to be tested via user testing by candidates, as the next step in the process.
