### ISSUE TITLE
Show new/old Character Information data on the Candidate's page in Admin

### ISSUE THREAD

**Issue by mbrookeswebdev** [jac-uk/admin#1206]
![Screenshot.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/9bca3b22-bc08-4c3b-8d9d-071933c2ac91)

Also, make margins smaller to make Character Info section look like the rest of displayed information and save space.

![margins.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/a6c84857-3557-47a4-86e1-c21d4606d73f)

**Comment by mbrookeswebdev** [comment]
**BEFORE RELEASE NEED TO CHECK FOR CANDIDATES WHO'VE ALREADY APPLIED USING THE NEW CHARACTER INFORMATION FORM**

**Comment by KateMJAC** [comment]
User testing group tested with positive results. I have also testing with a positive result. This can be moved to review once the comment above from Maria is clarified/action on if still required.
