### ISSUE TITLE
033 Recorder Exercise change candidate's Jurisdiction.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1214]
On 00033 Recorder Exercise, for candidate (details in the platform-issues channel), can you change the jurisdiction to read just Family and Crime. Please remove Civil from the list on Digital platform.![Capture.PNG 20.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/b84b8ee7-62b9-4441-a059-ae9ef7c28edc)

**Comment by mbrookeswebdev** [comment]
I've made the change as requested.
