### ISSUE TITLE
Tabs no longer function on application view

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/admin#1224]
Bug caught by warren. 
Tabs in application view no longer change the info displayed
![Screenshot 2021-03-16 at 10.51.19.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/9b7b43f2-9533-45c7-b47f-b8b2ad58e682)![Screenshot 2021-03-16 at 10.51.39.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/5f07073d-bb5b-4da1-8a71-bdf9760bba53)![Screenshot 2021-03-16 at 10.51.28.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/c5903069-1a6a-4eff-a74b-5c5d14b52bc4)![Screenshot 2021-03-16 at 10.51.47.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/cef05762-d3f6-4d88-a548-a1ae7829d220)

**Comment by KateMJAC** [comment]
Tested by the user testing group and myself. 

User testing group confirmed that the data displayed changes as each tab was collected and that the information displayed was as to be expected. 

My testing also delivered a positive result.
