### ISSUE TITLE
Qt reset

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/admin#1226]
Admin changes relating to [apply #730](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/730)

- [x] Add a confirmation modal
- [x] Add a `reset` field to the `statusLog` when reseting

```
{
   status: activated,
   statusLog: {
      started: DATE,
      completed: DATE,
      reset: DATE,
   }
}
```

**Comment by KateMJAC** [comment]
Based on discussions at 2/7/21 stand-up this ticket is to be progressed.
