### ISSUE TITLE
Resolve QT autosave issue

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1228]
The QT autosave function was rolled back in late 2020, as it created issues with the QT timer. 

In advance of the 051's proposed scenario test on 27 April 2021, this issue needs to be resolved (testing inclusive) and the autosave function reinstated for all QTs, but most importantly the scenario QT, as this test involves candidates providing typed answers rather than selecting an option. 

For critical analysis and situational judgement QTs a different save option can be considered if the autosave function cannot be reinstated across all types of QTs.

**Comment by KateMJAC** [comment]
The other question coming out of this ticket @warrensearle is the autosave still affecting the timer on scenario tests?

**Comment by lloback** [comment]
- Fixed the autosave for Critical Analysis
- Fixed autosave for Situational Judgement
- Fixed autosave for Scenario
No changes to the timer - no interference - no nothing

PR: https://github.com/jac-uk/apply/pull/745

**Comment by lloback** [comment]
This can be tested on the following URL:

https://jac-apply-develop--pr745-bugfix-1228-autosave-11zorvuh.web.app
