### ISSUE TITLE
Bug Handover Report Cannot read qualifications of undefined for Exercise 030. Need reports by 30th March, 2021.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1232]
As an administrator l want to log on exercise 030 on the platform then click on handover tab and click on the export bottom so than l can download the handover report for the JO

Notes
These functionality is not working for this exercises but works for others like (029). The Admin staff cannot export Handover data. I also have issue I am unable to export the handover report from the platform for this exercise.  Whenever I press the 'export data' button nothing happens.

Warren investigation.
Some exercises are seeing an error when trying to export handover data.![Screenshot 2021-03-26 at 14.55.25.png](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/1a56689e-2c9b-42a5-bf0d-06f927be319a)

**Comment by KateMJAC** [comment]
The 9 candidates in handover were in the withdrawn status. Maria moved them to applied and the rpot could then be downloaded.
