### ISSUE TITLE
Configure npm to use github packages for JAC Kit

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1237]
Amend npm configuration to look at github packages for JAC Kit

**Comment by warrensearle** [comment]
_**This really only needs testing by the development team... plus our CI tool (CircleCI) will report an error if there's a problem with this change.**_

To test:
- Check out a fresh clone of https://github.com/jac-uk/admin
- Run `npm install`
- Note if you are not already authenticated with Github Packages then you will need to run `npm login --scope=@OWNER --registry=https://npm.pkg.github.com`. Log in with a Personal Access Token that has at least the following permissions `read:packages, repo`

Expected:
You should be able to install admin without issue

**Comment by KateMJAC** [comment]
Just did a shout out on Slack to ask Devs to test this one. Feedback should be left on the ticket via a comment.

**Comment by mbrookeswebdev** [comment]
@warrensearle npm run serve gives this error

![4.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/5eb27c95-9297-4ca7-a908-50528b576b90)

**Comment by mbrookeswebdev** [comment]
Tested and it works.

**Comment by KateMJAC** [comment]
@warrensearle Tom, Maria and Darrel all tested this with a positive result.
