### ISSUE TITLE
Clarify ‘Out of time’ text on QT summary page and candidate message

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1241]
**Issue:**

At the moment ‘out of time’ count on the QT summary page (shown below) includes all candidates that don’t submit the test before the allocated time. This includes people that completed all answers but failed to select submit and candidates that failed to complete all of the answers before the platform auto submitted their test. 

This is confusing to the exercise team and SLT, as it does not portray an accurate picture of what has occurred. 

Candidates who have supplied an answer for all questions also receive an onscreen message indicating that they didn’t compete the test in time. This is also recoreded in the 'Past' test tab.  We have received feedback that this was confusing to them. 

**Describe the solution**

We ideally require the summary page and apply side messaging to differentiate between those candidates who had completed all questions and those who didn’t, before their test was auto-submitted, or we need revisit the wording of both displays.

 ![Out of time.png](https://images.zenhubusercontent.com/5fcfacf3d4e677f3af4fdecb/e91288f2-6676-4fd1-b63e-7a7ef1f929d7)

**Comment by KateMJAC** [comment]
Hello @warrensearle and @lloback did we discuss this ticket this morning? I can't recall it's status from a dev perspective.

**Comment by warrensearle** [comment]
Closing as this has been implemented / superseded under the following ticket:
https://github.com/jac-uk/digital-platform/issues/657
