### ISSUE TITLE
Exercise Download for S9(1) Exercise- 035

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1243]
The error is in exercise downloads. We use the skills and abilities framework and I uploaded them document to the 035 s9(1) page. A candidate emailed to say this link on the info page wasn't working. I tried reinputting the link to ensure it was correct (the other links work) but it was still redirecting me to the admin edit downloads page, it showed as an error for the candidate. I figured out that for some reason 'Skills and Abilities' is not showing on the 'Exercise Downloads' page under 'Exercise'. I fixed the error by uploading the doc under the 'competency framework' section and linking to that. This seems to have been the case on 024 and 020 when I look at them.

@tomlovesgithub can you investigate this issue pls.

**Comment by KateMJAC** [comment]
This has been tested by the user testing group and myself with positive results. 

This is cleared to go onto production.
