### ISSUE TITLE
Spike: What work has been completed on the Character Check Consent Form?

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1273]
It looks like the great work that Enor has completed on the Character Check Consent Form has been implemented on staging. However, we need to undertand whether all workflows related to this feature have been completed and where this functionality has been released.

Please confirm the follwing: 

- [ ] Whether the consent form has been realeased on Production, in anyway eg. realeased but hidden.
- [ ] We can see the form on staging, but has the required work been completed on Admin? we need to be able to view the information and for it to be included in the automated JO handover. 
- [ ] Does the current consent form include questions for all of the data we need to collect A) for character check consent and B) the JO handover? (Kate and Joy are more responsible for this task)

**Comment by mbrookeswebdev** [comment]
- There is a consent form present but [hidden in the project on the Apply side](https://github.com/jac-uk/apply/tree/master/src/views/Apply/CharacterChecks) (as per the Apply prototype). We need to check whether information requested is still relevant and correct and update links if required. (Title field need to be changed as per gov.design guidelines and changes to first/last names as per recent changes in #615/#616).
 
- On Admin side some of the collected information is displayed in Applications->Candidate->Agency report. We need to update to reflect title, first/last names changes +/or do we need another tab Consent Check to display all the info we collect? We don't have the "Send email" button functionality which would send consent check form to candidates using Notify as per Admin prototype.

![Test.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/70765176-342f-40d1-9b18-178f54025064)

**Comment by KateMJAC** [comment]
Hello @mbrookeswebdev, you're right that we can't send emails from the platform yet, but can we set it up the same way IAs are currently set up? assessors recieve a link and then log-in to upload the assessment. If we can replicated that or set it up so that candidates can receive a notification and then log in and complete the form, or could we generate a link that the team then sends via notify? 

A link for notify isn't the best way forward, but it would do for an MVP, get what we need for the JO transfer and still be a massive imporvement on the way teams currently collect this information.

**Comment by mbrookeswebdev** [comment]
@KateMJAC I believe IAs are set up using the Notify API. I've also found some unused code in the digital-platform dealing with sending consent checks email. I'll need to discuss with Warren whether this can be updated if needed and used to send consent checks requests.

**Comment by KateMJAC** [comment]
This work is now being done via
