### ISSUE TITLE
Vulnerability - npm audit

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/admin#1303]

**Comment by HalcyonJAC** [comment]
found 103 vulnerabilities (3 low, 88 moderate, 12 high) in 2245 scanned packages

npm automatically fixed 84 of these.

fixed 84 of 103 vulnerabilities in 2245 scanned packages

`firebase-tools` needs updating 1 major version to fix 10 - but all of these reside in dependencies of `firebase-tools` - `axios`, `json-bigint` and `node-forge`.

**Comment by HalcyonJAC** [comment]
- [x] Upgrade `sass-loader` for faster compilation
