### ISSUE TITLE
System Activity Logging

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/admin#1307]
Store logs of events in the system – i.e. application created, submitted, etc.

Qualifying Test reset.

Include user, timestamp, event detail.

**Comment by JeremykJAC** [comment]
**Actions to log**

- Candidate/apply actions
- Candidates making changes to their questions (we get candidates insisting that they edited a certain section but the edits didn’t save due to platform error).
- Candidates uploading documents (same as above).

**Admin actions**

- Changing candidates’ personal details.
-  Changing candidates’ application answers (at the moment admin users can change the IA section and downloads, but Tom is working on a ticket to make all of the questions editable, so this will need to be logged).
- Changes to statuses/stages (teams contact us saying that someone is mysteriously in the wrong stage/status, but we suspect candidates get moved in error, so it would good to log that).
- If an exercise is unpublished from the website.

**Comment by JeremykJAC** [comment]
Blocked pending conversation with Warren

**Comment by KateMJAC** [comment]
@HalcyonJAC this may be covered by Changing candidates’ personal details, but can you please liaise with @mbrookeswebdev with regards to the changes to candidate email addresses. Maria is currently working on a piece of work around that and suggested that this needs to be loged.

**Comment by JeremykJAC** [comment]
Need a conversation with Warren

**Comment by londonprojects** [comment]
@warrensearle @JeremykJAC What conversation needs to happen?

**Comment by warrensearle** [comment]
Hey @JeremykJAC let me know if/how I can help
