### ISSUE TITLE
System Health Monitor

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/admin#1308]
A job that runs at 9am each morning to check for anomalies in the system; i.e., highlight records in the database that indicate some kind of user/system error.

The results of which could either be emailed to key members of staff or be shown on-screen via a dashboard in the Admin portal.

**Comment by JeremykJAC** [comment]
Awaiting requirements

**Comment by londonprojects** [comment]
@JeremykJAC @KateMJAC How are you planning to get the requirements?

**Comment by JeremykJAC** [comment]
@londonprojects We put a message out in Slack and in the Stand-Up but we haven't had any feedback. This ticket was then bumped by another one. Some of out blocked work is where it was on a W/O and then has been super-seeded. 

When we got no feedback we moved on to something we could do. 

Things like this could do with having the requirements gathered otherwise we get stuck trying to do it when we should be coding. When nothing came to light we didn't sit it on any longer.
