### ISSUE TITLE
Enabling Completion of the Character Consent Form

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1312]
**Is your feature request related to a problem? Please describe.**

As an Admin, I use the character consent form to gain consent for checks and to collect information for the JO handover. I currently have to create this via Google Forms and email the link to candidates. This takes me a lot of time and the data collected is then kept off the platform when it should be held on there.   

**Describe the solution you'd like**
I need the following functionality on the platform:

- [x] I need to be able to select candidates that are required to complete the consent form. I may need to do this after shortlisting, before selection days, or it may happen after selection days.
- [x] I need to be able to set a date deadline for completion of the form.
- [x] The selected candidates/users need to be notified that they are required to complete the form. 
- [x] The selected candidates/users need to be able to login to their profile and complete the form. 
- [x] I need to be able to use some of the data in the automated JO handover.
- [x] I will need to use some of the data for automated character checks, which I hear is being developed on the platform shortly. 

**Describe alternatives you've considered**

Setting-up a Google Form and emailing a link to candidates. This is too time consuming and results in data being held off the platform, which is not ideal. 

**Additional context**

The consent form is already on staging and production. What's required here can be developed in a similar way that IAs function.

**Comment by KateMJAC** [comment]
Please create any further tickets that are required to complete this work.

**Comment by mbrookeswebdev** [comment]
[There is a branch in Admin repo with some prototype code written for ticket 1147](https://github.com/jac-uk/admin/tree/feature/1147-approach-to-implementing-user-roles).
