### ISSUE TITLE
Location Preferences

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1313]
As a admin when l download candidate location preference  l want to see the order candidate has filled them in so that l can have the correct order location the candidate have filled in their  location.

Note:

The candidate shouldn't be allowed to choose same location preference twice.
The candidate preferred location shouldn't be reordered by the platform.
If candidate fills in their Location preference e.g London to be their first choice and Birmingham to second and  if a candidate is forced to decide in priority order the  platform might put candidate first priority to last and the platform doesn’t tell the candidate its doing this. 

@tomlovesgithub I will update this ticket asap

**Comment by KateMJAC** [comment]
@joy-ade and @tomlovesgithub, this work has now gone out to the UTG. I will update when responses are received.
