### ISSUE TITLE
Additional question fields in relation to legal experience.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1314]
As admin l want the candidate to answers the following question so that l can have all the information l need for statutory com letters. This field should be made mandatory. Candidate needs to provide answers to the following question.

Note

These information should be capture underneath Law related Task on the application form this information is needed for judicial roles. Once a candidate click this option 1(The carrying-out of judicial functions of any court or tribunal)  on Law related task  then there should be a pop up field that will ask candidate below questions. And the field has to be made mandatory for candidate. 

![Capture.PNG 21.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/ce172d70-9587-4bfb-875e-b677d6b4be5d)

Legal Experience:  textbox one line

Dates: date MON/YEAR

Category of Law: textbox oneline

Time engaged in this activity:  Start date/end date DAY/mon/year

Judicial Office: true/false tickbox
⎣
   Previous Judicial Office Type: text oneline

   Judicial Appointments: Date day/mon/year

   Nature of Appointment: textbox one line
   eg(fee-paid tribunal judge)

   Circuit or Region: textbox one line

   Jurisdiction: texbox

   Tribunal: textbox oneline

**Comment by KateMJAC** [comment]
@tomlovesgithub please check with Matt after he has returned from leave and ensure that he is okay with the content of this work before it is release. 

FYI - @joy-ade @londonprojects

**Comment by londonprojects** [comment]
Hello @tomlovesgithub Do you have a status on this ticket? If so can you update it?

**Comment by joy-ade** [comment]
@londonprojects I shared this tickets with Matt on Friday on Kate's instruction, he is reviewing the tickets and we await Matt feedback. @tomlovesgithub FYI

**Comment by joy-ade** [comment]
@tomlovesgithub Find the changes that Matt required be made before we push this ticket to live.


 

![Capture.PNG97.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/2ddf491f-8b8b-4364-9d1e-a3f2884c212e)![Capture.PNG98.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/d0d64508-11fa-412d-b1b7-d8d18805c7a9)
