### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1315]
This is for for developers using GitHub only

**Comment by JeremykJAC** [comment]
We are only able to turn this on for ourselves. We will need help from an admin to do this user wide, please.

**Comment by warrensearle** [comment]
Here's a link to the 2FA status for all the JAC github users: https://github.com/orgs/jac-uk/people

**Comment by londonprojects** [comment]
@JeremykJAC @warrensearle Is this still blocked?

**Comment by warrensearle** [comment]
Here's the latest status 
![image.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/753a7c68-17f2-4f3b-abbd-9e9146b0b6ae)

**Comment by warrensearle** [comment]
Status as at 4th October 2021. @joy-ade @HalcyonJAC who is managing this process? Be great to get this ticket closed off!
![image.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/4723930a-480e-4dc3-98a8-f0a4c0598048)

**Comment by joy-ade** [comment]
@warrensearle This was managed by @HalcyonJAC

**Comment by JeremykJAC** [comment]
@joy-ade Jeremy S and JoshKohJAC need to enable 2FA and then the ticket is complete. Who is Josh?

**Comment by joy-ade** [comment]
@JeremykJAC  Josh works in account. I will be in touch with him. Can you send me the link pls.

**Comment by JeremykJAC** [comment]
@JoshKohJAC This is where it is added in GitHub - https://github.com/settings/security
