### ISSUE TITLE
Eligibility Report for for 051 DDJ(MC) 19/5/2021

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1318]
As as admin l want to download eligibility report so that l can do eligibility check on candidates who has through to selection days.

Note
- You need a to created export data button

-  Admin should be able to click and download the report

- Rich field text box Admin search candidate names enter first few letter

we would need the download to show the candidates ‘date qualified’ which appears on their application under qualifications section.  At this stage, we don’t need the download to contain character column.
![Eligibility Report.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/0b787ee1-05c3-4978-ba46-ee7473c24146)

@halcyonJAC @JeremykJAC l will email you a copy of the previous eligibility spreadsheet that was created for the Team.

**Comment by joy-ade** [comment]
@KateMJAC Warren has advised as following. If you want him to create the spreadsheet for the selection exercise team. Its will take up to 2hours to have it ready. But if we want to build the functionality on the platform that will allow the selection team to click on a export bottom to download the spreadsheet its a 1day.

Kate this ticket is yet to be allocated to a developer.

**Comment by KateMJAC** [comment]
Hello @joy-ade , following our discussion this morning with Matt, this ticket can be allocated to Halcyon in place of the non-live assessment item.

**Comment by JeremykJAC** [comment]
Hi, I think this will day us a day and a bit. :)

**Comment by joy-ade** [comment]
@JeremykJAC Thanks for the update. I will forward the spreadsheet that shows the fields that is required to by email.

**Comment by JeremykJAC** [comment]
@HalcyonJAC Tom, the report for this issue is within our internal JAC channel.
