### ISSUE TITLE
Staged Applications

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1341]
Note: this is the first part of the [Combined Exercise Workflow](https://github.com/jac-uk/admin/issues/1294)

Here we are enabling the application process to be in stages so that:
 - We minimise how much information is requested from candidates
 - Information is only requested when it is needed
 - Exercise teams have less data to process in order to progress applications

For example:

During initial registration collect personal details and eligibility from the candidate. No other information is required at this stage.

Once applications have been shortlisted collect further information from the candidate such as Independent Assessor details, Statement of Eligibility, Qualifications etc.

**N.B. This functionality needs to be completed and tested by the end of June, as it will be used for exercises launching in early July.**

**Comment by joy-ade** [comment]
@warrensearle we have got  feedback from Lisa's team. FYI
One point that we wanted to raise was the addition of an export contacts button at the review stage? we have export contacts at apply and we can use this to bulk download the email address/information of all candidates but then when we change their status after test 1 for example and we need to capture some of that data again before the scenario test there is no way to export so it will require us to do manual work on a potential large group of candidates approx 800 in our case.  If there was a way you could export data at review stage at least we could then filter the excel sheet by status to capture the information we need to allow the scenario candidates to take that test

![Capture.PNG83.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/e0aa63c6-e289-4493-bb8b-2c0cc7597fba)
