### ISSUE TITLE
Enable application process to be configured

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1347]
Here we are iterating on the work carried out in [#1345 enable the application form to be configured](jac-uk/admin/1345) and [#1346 Add current state to an exercise](jac-uk/admin/1346).

Now that exercises have states while applications are being processed we can configure which parts of the application content should be requested at each state.

---

As an admin
I would like to configure which parts of the application content are requested at each state of the exercise
So that I have application content when I need it, and
So that candidates are only asked for information when it is actually needed

---

The UI could look something like the following where we can add and remove 'parts' from each state.

![image.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/46c6f1bc-c9a5-49d1-b2e7-4db6cefd45a9)

Note: it should also be clear which 'parts' have not been assigned yet.

---

## Done when

- [x] Admin can configure which parts are needed at each state
- [ ] Candidate is able to provide additional information when exercise has entered that state AND they have progressed to that processing stage

**Comment by KateMJAC** [comment]
Sent to UTG W/C 5 July. Awaiting feedback. Will update when received.
