### ISSUE TITLE
Exercise with welsh  administration question.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1355]
The exercise has posts in Wales, but there are no welsh language requirement posts, therefore when creating the application form, I selected "Welsh administration questions" only. However, we have had multiple queries from candidates saying when they "review application", the "Welsh posts" section gives 3 questions: "Applying for a post in Wales" (which should be there), 

Can we remove
[ ]"Can speak Welsh" 
[ ] "Can read and write in Welsh"

![Capture.PNG46.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/1c99c337-c8ac-47b9-a9b8-d862b31034ba)

So when the Admin click Welsh administration questions while creating the exercise., there should be only one 1 question showing on the apply.

![Capture.PNG45.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/ce778ba1-fdda-4e18-8d15-433a919f616d)![Capture.PNG46.PNG]

**Comment by mbrookeswebdev** [comment]
@joy-ade As discussed, can I please have clarification with regards to the requirements -

- Should 'type of requirement' in Vacancy information be made 'required' as it is not at the moment.
- Should 'Are you applying for Welsh posts?' question be asked if there are Welsh posts (at the moment this question is asked only when Welsh posts and 'Welsh administration question' is selected.

**Comment by KateMJAC** [comment]
Sent to UTG 5/7/21. Feedback to follow.
