### ISSUE TITLE
Additional Preference to be included in handover report for exercise 021

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1388]
As an Admin l want the additional preference information to be  downloaded on an excel spreadsheet for all candidates that has been recommended so that l can include this information in my handover report to the JO.

Note: 

Additional preference data is needed for the JO handover report. I have sent a copy of the spreadsheet to @tomlovesgithub. Can l have this bespoken report for  exercise 021 FtT&ET pls.

Note we also need to include Jurisdiction preferences in this report

**If you are applying for the First-tier Tribunal, please rank your choice of chambers. As business requirements may change throughout the exercise for appointment in the First-tier Tribunal you are required to rank all chambers in order of preference on your application; one being your preferred choice and seven being your least preferred. (Ranked choice)**

@tomlovesgithub can you bring  @mbrookeswebdev up to speed on this issues please.

**Comment by mbrookeswebdev** [comment]
Digital platform branch [is here](https://github.com/jac-uk/digital-platform/tree/feature/1388-custom-report-ex21)
Admin branch [is here](https://github.com/jac-uk/admin/tree/custom-report-dl)

The report was emailed in, waiting for confirmation that it contains everything that was requested.

**Comment by joy-ade** [comment]
@mbrookeswebdev  There has been additional requirement for the tasks we also need to include Jurisdiction preferences in this report.

**Comment by mbrookeswebdev** [comment]
Report updated and emailed to users.

**Comment by mbrookeswebdev** [comment]
Requirement changed to include both recommended and handover stages
