### ISSUE TITLE
Sign-up Alerts

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1438]
As an admin l want the sign up link alert  that was displaying on the exercises l created to be removed when the exercises launches so that candidates knows that the advert is now live. 

Given an Admin create an exercise that shows the sign-up link alert before the exercise is launched
When the exercise launches
Then the sign-up link alert should be removed from the open exercises

**Comment by mbrookeswebdev** [comment]
Update: currently the link is displayed underneath of open vacancies. I've confirmed that the links has to be moved to Future vacancies to be displayed above 'Find out more' link.

**Comment by joy-ade** [comment]
@mbrookeswebdev This is correct the link should be moved to future vacancies.
