### ISSUE TITLE
QT Issues- dry run.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1440]
- [x] The QT Sub dashboard do not display all candidates for example on activate/initialised on the dry run QT. We had 75 dry run candidates added you can only view around 40-50 candidates on the first page the next page is blank although we had 75 the 25 remaining were missing from display.

- [x] Summary/Review page (candidate view) - comes up to show which questions have been answered and those that have been skipped, there are no question numbers next to the question. This is a little off putting if you make a note, as a candidate, about a question you want to go back to- you either have to count the questions or try to work out which one it is- this adds to the candidate time. **Nice to have but this has to be tested by UTG**

- [x] Firefox issue (firefox/chrome/safari)  -  error message pop up “Function DocumentReference.update() called with invalid data. Unsupported field value: undefined (found in field client.deviceMemory in document qualifyingTestResponses/kqqja2JGLtRBkvg57Zyc)”.  Another version of the error code
Function DocumentReference.update() called with invalid data. Unsupported field value: undefined (found in field client.deviceMemory in document qualifyingTestResponses/XVKzoq0BlCwxMjt2cNOz)

**Comment by joy-ade** [comment]
@warrensearle These issues have to be fixed by the 13th of August please.

**Comment by warrensearle** [comment]
Hey @joy-ade as discussed the following items have been removed from this ticket and will be addressed separately. Browser compatibility is already captured in ticket [apply#395](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/395):

- Browser Compatibility: Ensuring all major browsers: Google Chrome, Mozilla Firefox and Safari work on the platform and the live QT. Microsoft Edge is the only browser which seems to work fine with no issues.
- Device Compatibility: Ensuring the platform works effectively with Apple devices: Mac Book Pro and Ipads as well.
- Password Reset: Ensuring the password reset function for candidates is very thorough as candidates still do not receive password reset emails in the first instance.
