### ISSUE TITLE
Ranking Functionality

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1451]
As a one panel member l want to rank candidates doing sift so that l can identify candidates that need moderation.

As a one panel member l want the candidates that have similar grades to be highlighted.

Given a one panel member clicks on candidates 
When a panel member clicks on rank grades
And choose a  grade 
Then the grade should be assign to the candidate.

Given a one  panel member has finished assigning grades to candidates
When a one panel member looks at the grades
Then candidates with similar and top grades should be highlighted.

**Comment by londonprojects** [comment]
@warrensearle Is this story ready to play?
