### ISSUE TITLE
Investigating submitted Applications without any content for - Exercise 070

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1507]
**The Why**

Exercise 070 closed today at 13.00 the team were unable to process the application because there was two submitted applications with any content. This  stop the press processing application button  from working and this error messages appeared on the screen. How is it possible for applications to be submitted with hardly any content in them.
![image (10).png](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/5cb9c215-6aea-4f25-b45d-98c3164ed88a)

SET also reported that the download from applied status has two applications without any names/emails etc. The reference numbers for the applications  are JAC00070-ptk1625 and JAC00070-xby1006 and the two candidates don't seem to have applied for the exercise.  The team provided a screenshot which clearly shows the application was submitted. 

To enable the processing application button @mbrookeswebdev moved the two blank application to draft.

 

Can we investigate further why we had two blank applications in applied?.

@warrensearle There is a QT for this exercise on the 28th of October. Can we update candidate data in the database to enable the candidates search function to work for this exercise please.

**Update: the candidates search function should work now.**

@warrensearle There was a QT set-up for the candidate that submitted their application without content. The candidate was unable to take the test because the candidates was using a work laptop which has firewall issues. I believe the candidates also submitted their application on the work laptop hence we had a blank application.

**Comment by mbrookeswebdev** [comment]
@warrensearle @joy-ade We had an enquiry from one of the candidates, they are trying to find out what happened with their application. They provided a screenshot clearly showing that the application was submitted (see platform-issues-channel 04/11/2021).

**Comment by warrensearle** [comment]
Thanks Maria, I spent a couple of hours looking at this a week or two ago and was unable to replicate. The additional info might help.

**Comment by joy-ade** [comment]
@warrensearle  Do you have any updates on this please?

**Comment by warrensearle** [comment]
Closing this ticket for the following reasons:
 - we spent a significant amount of time investigating and trying to replicate
 - looks like this was down to candidates using restricted work laptops, which we advise against 
 - we need more information in order to be able to replicate and confirm the problem
 - it effected only 2 out of 2000 or so applications (i.e. less than 0.1%)
 - right now there are more effective uses of developer time
