### ISSUE TITLE
Creation of a practice QT

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/admin#1565]
Create a practice QT, accessible via the website, which candidates/potential candidates can undertake to 
1. assess for themselves whether they are yet ready to apply 
2. check their technology is compatible ahead of a live QT 
3. Familiarise themselves with the format and sort of content they can expect in a live QT

**Comment by andrew-isaac** [comment]
@JeremykJAC when can we get this in production

**Comment by JeremykJAC** [comment]
If Francesca signs off the Practice QT we could get this live on Weds, 4th April

**Comment by andrew-isaac** [comment]
I have spoke to Comms and @MattHowley  - He is going to check with SLT on 20/5/22 when we can launch this

**Comment by MattHowley** [comment]
I messaged Jessica earlier. Jessica was intending to demo at SLT next week. Her allocated focus discussion has, however, been moved to 9 June. It makes complete sense for Jessica to use her focus discussion to demo the practice test so unfortunately we will have to wait until after 9 June now.
