### ISSUE TITLE
User Roles Part 2 (Implementation) 

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/admin#1607]
Implement the following User Roles:

- Digital Super User
- Operations Senior Manager
- Operations Team Member
- Other JAC Staff

And assign the rights to each group from the below spreadsheet:

https://docs.google.com/spreadsheets/d/1L2hY0Srix41Gr_IxGSd4goIrnv7-mlAT-btDWVBSZ2g/edit#gid=0

Assign these users to the roles:

https://docs.google.com/spreadsheets/d/1L2hY0Srix41Gr_IxGSd4goIrnv7-mlAT-btDWVBSZ2g/edit#gid=0

Note - List all CRUD operations to each category (exercise, database etc...) This will then give us the option to further tailor user roles and fill in any missing gaps.

**Comment by andrew-isaac** [comment]
@JeremykJAC  as this is rolled out can I close the ticket?
