### ISSUE TITLE
Custom Report - Data returned is missing and can't be exported.

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1630]
When I go onto the production platform and the custom report area under reports, I run a report for the working preferences section, but the data returned states value/blank for some candidates. The users need to provide this data to our stakeholders are currently having to do this manually from each application and be able to show their information ranked.

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/e69be338-f674-41d0-b957-2591a1f3c6c3)

We currently have 3 exercises that need this information:

066 - Circa 216 candidates - https://admin.judicialappointments.digital/exercise/Yt04PxbBde5nfZxNgFWx/details/overview
070 - Circa 400 candidates - https://admin.judicialappointments.digital/exercise/Yt04PxbBde5nfZxNgFWx/details/overview
077 - Circa 069 candidates - https://admin.judicialappointments.digital/exercise/Yt04PxbBde5nfZxNgFWx/details/overview

For 066 - We need all candidates at the recommended stage and need their Jurisdiction and Location Preferences in rank order

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/08a58a26-1514-43b5-af63-163b9ff73595)

For 070 - We need all candidates at the selected stage. We need their answers to the jusdication question and all additional preferences questions. The If you are applying for the First-tier Tribunal, please rank your choice of chambers. As business requirements may change throughout the exercise for appointment in the First-tier Tribunal you are required to rank all chambers in order of preference on your application; one being your most preferred choice and seven being your least preferred. (Ranked choice) question should be returned as ranked in the data.

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/1789103d-792e-4b57-920a-09573c513ab3)

For 077 - We need all candidates at the selected stage nd need their Jurisdiction and Location Preferences. The location preferences should be ranked in the data return.

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/9689aed7-05c2-4ee1-bd2e-727873dab8be)

All data needs to be exported via a button on the platform - this is currently missing.

**Comment by warrensearle** [comment]
Hey @andrew-isaac I have exported the data for the three exercises so the immediate requirements are satisfied. I haven't amended the custom report so have moved this ticket to the backlog to be implemented in the future.

**Comment by andrew-isaac** [comment]
@tomlovesgithub  - Is there any update on when this can be released? I have more teams requesting this type of data now from me for a large exercise.
