### ISSUE TITLE
Custom Report - Export Button is Missing/appearing at the bottom of the page

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1635]
As an admin, I want to be able to download custom reports from the platform. When I go onto the platform and run the report the button is sometimes missing or I have to scroll through a long list of data to find the button.

I would like to go to the platform, create my report and have the download button underneath or near the save button.

The platform currently shows it right at the bottom but has been missing on some exercises:

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/2d9e185f-0388-4155-b9e5-ca0be4cbc601)

I want the button to appear underneath the save button, so I don't have to scroll through a long list of data to start the process:

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/4ea8a4e2-faf5-42ba-ab1c-013a2e2ac31a)

- [ ] Explore reason/s button is missing on some exercises

- [ ] Deploy fix for this issue, if needed

- [ ] Work on moving the button to the top, underneath the "save report button"

**Comment by tomlovesgithub** [comment]
Covered in #1701
