### ISSUE TITLE
Markdown/Formatting in Exercises

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1655]
As a user I want to be able to add further formatting when creating an exercise on my vacancy page.

On the website listing and Vacancy information page there is "Role Summary" box. I want to have the same formatting options I currently have on the about the role section.

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/f6e4860b-b632-4374-8f46-8094205ecab9)

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/22a55868-eb21-453b-9447-482b06cf478c)

**Comment by HalcyonJAC** [comment]
Hi @andrew-isaac, should I also apply the same change on "Role summary (Welsh)" box?

![Screenshot 2022-07-06 at 17.47.05.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/f8fcce77-9308-44af-9213-9024689a2138)

**Comment by andrew-isaac** [comment]
@HalcyonJAC  - Yes please ! Good spot - In my rush to everything else I was sure I missed something
