### ISSUE TITLE
Stages and statuses

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1666]
Improve the stages and statuses that applications can be assigned upon their journey from 'registration' to 'handover'.

See [this google doc](https://docs.google.com/document/d/1b0bQ6O6rhyL2fhmZWq5OaL0owBnlaYvY/) for more information

**To do**
We will approach this work as follows:

**1. Stages and statuses**
- [x] Update the existing stages and statuses screens to support the new stages and statuses
- [x] Centralise the logic
- [x] Add custom page size
- [x] Add search
- [x] Enable EMP to be updated without changing status
- [x] Include a star next to statuses that progress application to next stage
- [ ] Update reports which include stage & status - e.g. diversity report  

**2. Back-fill data / support current and new stages & statuses**
In order to facilitate user testing and trial usage we will support current & new stages and statuses.
When all stakeholders are happy with the new stages and statuses we will back-fill / transform old stages and statuses into the new equivalents. This will help with reporting & stats across exercises.

 - [x] Assess the scope/scale of back-filling data vs supporting old and new model
 - [x] Support current and new stages & statuses
 - [ ] Back-fill / migrate data

**Comment by andrew-isaac** [comment]
@warrensearle  - What is the update with this work? Why is it blocked?
