### ISSUE TITLE
Validation of Application Sections/Questions

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1708]
As a user when setting up exercises on the platform I want to be able to specify if certain questions, sections or data entry points of an application completed by candidates should be mandatory to complete as part of their application process.

A candidate shouldn't be able to complete or bypass a part that has been mark by team as mandatory. This should also flag to the candidate what is missing as a warning on screen.

Currently teams can't do this and it is leading to them having to go back via email and collect information from candidates.

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/ff8a0a3a-2a0a-4fa6-8ed4-bb687e9e68bb)

Hi Andrew 

I am not sure if this is a question that you can answer but in relation to 106 HESCC exercise we had an applicant who did not submit their statement of eligibility. I wanted to know if you are able to see if they did attempt to submit words in that text box or was it intentionally left blank? 

Candidate application form JAC00106-wsg0026 
Here is the link
[Exercise Application | JAC Digital Platform (judicialappointments.digital)](https://admin.judicialappointments.digital/exercise/Elf8nci6pVGuTaB4QF2U/applications/applied/application/PnAr9y2uOVTMIH07aaSi)

**Comment by warrensearle** [comment]
Closing as further work being carried out in another ticket
