### ISSUE TITLE
ACRO Template on Agency Reports

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1714]
As a user when I use the Character Checks function on the platform and receive the ACRO checks back I have to go to Agency section under reports and then t export it into excel sheet copy and paste all the data it to a template supplied by ACRO.

I want the candidates data received back on the character checks to go straight into the template on the reports section for ACRO to just export it and send it to them. All the fields ACRO need should be populated in the export.

[https://app.zenhub.com/files/201485031/c5600bcc-2f59-4efc-ae51-5bd724429bba/download](https://app.zenhub.com/files/201485031/c5600bcc-2f59-4efc-ae51-5bd724429bba/download)

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/a6f5a198-a68b-458a-ab1b-457639bb240e)

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/ba66a234-f912-4774-ab67-12c03f12d874)

**Comment by warrensearle** [comment]
We have agreed to ensure our export for ACRO has columns exactly matching the template excel sheet provided. The teams will then be able to simply copy and paste into the ACRO template then send it off.
