### ISSUE TITLE
Diversity Report - Amendments

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1723]
Hi Andrew and Matt,

I just wanted to reach out about a change to the Platform’s Diversity Report section that we would like to make if possible, which addresses an issue that has come up several times in the last fortnight. Apologies if you prefer Slack for this type of issue Andrew, but I thought with the various attachments an email might be easier.

The issue is that we have noticed that the platform diversity report is not currently consistent with other places w[here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1090127/Judicial_diversity_2022_Tables.ods) we report diversity statistics, most notably the annual Combined Statistics Report. This has t[here](https://admin.judicialappointments.digital/exercise/Yt04PxbBde5nfZxNgFWx/reports/diversity)fore caused some confusion when reading from exercise Diversity Checkpoints (which are produced from the Platform reports page). See the attached emails for a couple of examples.

Most significantly, candidates listing their ethnicity as Other are not being included in the BAME category on the diversity reports. However, our agreed policy with JDF partners is that Other comes under the BAME label, including for EMP consideration. The other main inconsistency is that candidates who choose not to disclose their characteristics (“Prefer not to say”) are being included in percentage calculations, so that, for example, the sum of percentages for disabled and non-disabled candidates is not 100%. A final minor difference is the inclusion of a Gender Neutral category in the Gender section. This has an extremely small number of responses so the Stats report just includes this in the Unknown count, so that the comparison between male and female representation can be easily made. 

See below tables as presented in the statistics report (2022 tables can be found here). Note i) no “Other” category for ethnicity, ii) unknowns not included in percentage calculations and iii) no “Gender Neutral” category in gender. To compare, see the diversity reports here for 066 as an example.

We are keen to make a change to the diversity reports as quickly as possible to prevent further confusion. Would you be able to advise on how best we might be able to do this? Happy to chat through further with Jessica and the developers present to fully illustrate the issue and agree our proposed changes.

-------

Hi Sean,

Thank you for sending over the details. Reading through the detail with develops we think one of the requirements is:

•	In apply when a candidate selects “other”  the diversity section on admin should count this as BAME in the diversity report section.

The others we are not sure what you want and how you want it presented, so think a chat is best? The first link didn’t work but I presume you mean this one - [Diversity of the judiciary: 2022 statistics - GOV.UK (www.gov.uk)](https://www.gov.uk/government/statistics/diversity-of-the-judiciary-2022-statistics) and the attached document from this website?

-----------

Hi Sean, 

We have spoken some more and think point 2 is this:

It looks like the second point is that the actual values (e.g. male, female) should add up to 100% with the Prefer Not To Says being reflected outside of this, probably they’ve used Declaration Rate to indicate this. So, for example, out of 10 cats:

•	6 said they prefer Whiskers
•	2 said they prefer Applause
•	2 preferred not to say

The percent would be:

•	75% said they prefer Whiskers (6 out of 8)
•	25% said they prefer Applause (2 out of 8)
•	Declaration rate was 80% (8 out of 10)

-------------------

Our emails have crossed, but yes, the cat analogy is correct. We’d like to apply this to the whole diversity report section (so Applied, Shortlisted, …, Handover) for each characteristic (Gender, Ethnicity, …, Social Mobility). For Social Mobility, it is not clear if the current numbers for Attending State School and First Gen Uni are including or excluding unknowns from the percentage calculation. It would be good to verify that they are excluding them.

**Comment by andrew-isaac** [comment]
Just picking up from our conversation on Slack, the questions to be included on the application form from 1st April are the three below. These would replace the existing three social mobility questions (around schooling, Oxbridge and university attendance). I know that the last two are very similar to ones we already ask but we have agreed to standardise the exact wording of the questions and responses across all JDF members (JO, Bar Council, Law Society etc).

Happy to chat about this. Aware we have the application working group later today which may touch on similar things.

Best wishes,
Sean

What was the occupation of your main household earner when you were about aged 14?

•	Modern professional & traditional professional occupations such as: teacher, nurse, physiotherapist, social worker, musician, police officer (sergeant or above), software designer, accountant, solicitor, medical practitioner, scientist, civil / mechanical engineer.
•	Senior, middle or junior managers or administrators such as: finance manager, chief executive, large business owner, office manager, retail manager, bank manager, restaurant manager, warehouse manager.
•	Clerical and intermediate occupations such as: secretary, personal assistant, call centre agent, clerical worker, nursery nurse.
•	Technical and craft occupations such as: motor mechanic, plumber, printer, electrician, gardener, train driver.
•	Routine, semi-routine manual and service occupations such as: postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, sales assistant, HGV driver, cleaner, porter, packer, labourer, waiter/waitress, bar staff.
•	Long-term unemployed (claimed Jobseeker’s Allowance or earlier unemployment benefit for more than a year).
•	Small business owners who employed less than 25 people such as: corner shop owners, small plumbing companies, retail shop owner, single restaurant or cafe owner, taxi owner, garage owner.
•	Other such as: retired, this question does not apply to me, I don’t know.
•	I prefer not to say.
 
Which type of school did you attend for the most time between the ages of 11 and 16?

•	A state-run or state-funded school – non-selective
•	A state-run or state-funded school – selective
•	Independent or fee-paying school
•	Independent or fee-paying school, where I received a bursary covering 90% or more of my tuition 
•	Attended school outside the UK
•	I don’t know
•	Prefer not to say
 
Did either of your parents attend university and gain a degree (e.g. BA/BSc or equivalent) by the time you were 18?

•	No, neither of my parents attended university
•	Yes, one or both of my parents attended university
•	Do not know / not sure
•	I prefer not to say

**Comment by warrensearle** [comment]
This has failed user testing please see slack: https://drie.slack.com/archives/C01R6GAAETG/p1689169719020309

**Comment by tomlovesgithub** [comment]
Needs approval from Sean Cuddihy. per discussion retro 3/8/23

**Comment by nickaddy** [comment]
@drieJAC @warrensearle please take a look at  Sean's feedback below, a few tweaks required before we send back to him for final UT:

Some notes on these changes. I think there is still some work to do here but moving in the right direction.

Diversity reports:
•	The new way of reporting percentages, with the declaration rate below, is very clear and exactly what we wanted.
•	I can see that those who have declared gender as “Other” are being treated as if they did not declare, which is what we wanted (even though this is not completely ideal, but it is how it is done in the Combined Stats report and numbers are very small).
•	I’m not able to tell whether “Other” ethnicity is being counted within the Ethnic Minority category as I don’t think any of the example exercises I’ve looked at have any candidates who that would apply to.
•	The social mobility bit is a little bit different as it is showing outputs from two different questions (one about school, one about parents’ education) on top of each other. These should probably have a declaration rate like the others. I.e, it is currently telling me that 56.67% (17) were first generation to attend university, but it is not immediately clear if that is 56.67% of the total applicants, or 56.67% of those who declared.
Dashboard:
•	The percentage reporting here is not working as well. If I go on exercise 00582 and look at the dashboard filtered to Gender, it says 27 candidates applied, but that is wrong I think, there were 30 but only 27 declared their gender. This should ideally be reporting it exactly how the Diversity Report does it.
•	Then underneath Male and Female it still has all the extra categories such as “Gender Neutral”, “Other” and “No answer” which we wanted to get rid of – as on the Diversity report, just display the main categories, and then the declaration rate underneath. Pro
•	The same seems to be the case on the other diversity categories: Ethnicity – we only want White and Ethnic Minority (where Other is included in EM). Disability: we only want Yes and No. Prof background: we only want Barrister, CILEx, Solicitor and Other. Social mobility is a bit different if using the current format of displaying two different questions on the same panel. (it says Undefined candidates applied next to Social Mobility so it is definitely not working quite right.

**Comment by drieJAC** [comment]
Feedback from Sean Cuddihy:
'Stats for 'Other' should be displayed for Professional Background on the Dashboard and the Report
