### ISSUE TITLE
Adding a late application to a closed exercise

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1725]
The exercise team would like the ability to create a draft application for an exercise when the exercise has closed (n.b. candidates can create applications themselves when the exercise is open). This needs to be approved by Senior Leaders **before** the draft application is created.

**Exercise Team: Request a new draft application**
Exercise team would like to request a new draft application 
so that they can allow the candidate to apply for a closed exercise

Exercise team enters the following data into a form on the platform:
 - Candidate name
 - Candidate email
 - Reason for allowing late application

The platform will then check the following and feed back to the exercise team is either fails:
 - check there's an existing candidate account for the provided email (a candidate account is required)
 - check there's not an existing application for that email (multiple applications from the same email are not allowed! plus team can give the extension to the existing draft application)

Providing the checks are successful (i.e. it is a valid request) an email is sent to the senior leaders. In addition a platform Message is created

**Senior Leader: Approve a new draft application**
Senior leader logs into the platform and reads the Message regarding the request, for example (N.B. this is _if_ we do the approval via the message... we might decide to do it via the Application View):

"
Request for a new draft application. 
JAC00007 Exercise Team has requested a new draft application for their exercise, with the following details:
  [ Exercise name ]
  [ Close date ]
  [ Candidate name ]
  [ Candidate email ]
  [ Reason ]
[APPROVE] [REJECT]
"

If approved the platform will create the application and send an email to exercise mailbox (and a Message)
If rejected the platform will update the status of the request/message/task

**Exercise Team: will inform the candidate**
Note that when the draft application exists the exercise team will give an extension and then communicate with the candidate. The platform should **not** contact the candidate or extend the draft application on behalf of the exercise team.

FIGMA design files: https://www.figma.com/file/ZFtPYKv3uxhLRW0EgBK2uv/1725-late-applications?node-id=0%3A1

**Comment by andrew-isaac** [comment]
@warrensearle @lloback - hat is the progress of this piece of work?
