### ISSUE TITLE
Delete Error Exercises

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1749]
Can 0148, 0150 and 0158 please be removed from the admin overview page please

https://admin.judicialappointments.digital/exercises

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/42223661-ab4e-445d-a447-7d36709d0a76)

**Comment by HalcyonJAC** [comment]
The exercises 0148, 0150 and 0158 are removed from the exercises collection in Firestore. No need to make code change.
