### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1779]
Afternoon all, 

I’ve made the amendments Matt has suggested to the Google Form Application and added comments to the Word doc outlining the changes. 

[https://app.zenhub.com/files/201485031/bb582f66-3620-48c9-9547-15fac515f869/download](https://app.zenhub.com/files/201485031/bb582f66-3620-48c9-9547-15fac515f869/download)

The links to the google form can be found on the document or below:

https://docs.google.com/forms/d/1yJ6Qgy5Ndn8pNuuIyFkQY8376bJI004wfnK_1DNlKR0/edit?usp=drive_web

https://forms.gle/DfCCpG2uhfYSisZs8

Kind regards, 

Elliot Koh
Selection Exercise Executive Officer | Judicial Appointments Commission | M:07591 994182 
www.judicialappointments.gov.uk | LinkedIn | Twitter |
 

From: Howley, Matt <matthew.howley@judicialappointments.gov.uk> 
Sent: 17 October 2022 13:46
To: Koh, Elliot <Elliot.Koh@judicialappointments.gov.uk>
Cc: Isaac, Andrew | (He/They) <Andrew.Isaac@judicialappointments.gov.uk>; Russell, Tom <Tom.Russell@judicialappointments.gov.uk>
Subject: RE: JAC Application (Welsh) - Google Forms

This is looking great, thanks Elliot and apologies for taking so long to respond. I’ve made some comments/suggestions against some of your notes on the attached. If you could have a look at these and make any changes I’ve suggested that would be great. 

Copying in Andrew and Tom just for info at this stage, but if you could copy them into your response once the changes are made Elliot that would be fab. 

Andrew/Tom – if Elliot is able to make the changes before the Digital Team meeting on Wednesday 26th Oct, please could you share with Rob and discuss at the meeting whether you think any other changes are required before I send for translation when I’m back from leave the week after next.

Kind regards

Matt Howley
Head of Digital Delivery and Programme Office | Judicial Appointments Commission | M: 07719 098105
If you receive this email outside regular working hours it means I am working flexibly. Flexibility works for me but please do not feel any pressure to respond outside of your own working pattern.
www.judicialappointments.gov.uk | LinkedIn | Twitter |
 

From: Koh, Elliot <Elliot.Koh@judicialappointments.gov.uk> 
Sent: 27 September 2022 16:47
To: Howley, Matt <matthew.howley@judicialappointments.gov.uk>
Subject: JAC Application (Welsh) - Google Forms

Hi Matt, 

I’ve finished creating a generic JAC application on Google Forms. I’ve made some notes on each section comparing the platform and google forms functionality, and raising any issues identified. The links to the google form can be found on the document or below:

Admin Link

Applicant Link

Kind regards, 

Elliot Koh
Selection Exercise Executive Officer | Judicial Appointments Commission | M:07591 994182 
www.judicialappointments.gov.uk | LinkedIn | Twitter |

**Comment by andrew-isaac** [comment]
https://welearnwelsh.com/grammar/how-to-say-yes-and-no-in-welsh/
https://digitalpublicservices.gov.wales/resources/digital-service-standards/#design-in-Welsh-and-English
https://www.gov.uk/government/organisations/valuation-office-agency/about/welsh-language-scheme
https://gov.wales/welsh-language-technology

**Comment by warrensearle** [comment]
Closed as archived in this [document](https://docs.google.com/document/d/1sVNTCw3cZK-Y87KO9CZci5YxCY_a2yiIDTXDGYLRjn4/edit#)
