### ISSUE TITLE
‘Are you Ready for your Selection Day?’ - Word Press Page

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1783]
[https://app.zenhub.com/files/201485031/f74b20ba-28b6-489d-8297-4128a954b237/download](https://app.zenhub.com/files/201485031/f74b20ba-28b6-489d-8297-4128a954b237/download[https://app.zenhub.com/files/201485031/d9a7bd9b-c6bd-4e29-88ea-3bd4b24052ab/download](https://app.zenhub.com/files/201485031/d9a7bd9b-c6bd-4e29-88ea-3bd4b24052ab/download)) 

I am proposing an alternative to technical calls for candidates who have remote interviews.  The outline of my proposal is below.  I have already run this past the Senior Leaders in Ops who are keen for us to go ahead with this idea.  They have suggested that we keep a record of the numbers of candidates who do request a tech call and their reasons and also ask the teams to let us know if there are any technical issues that could have been addressed by a tech call to avoid delay on selection day.  

Please let me have your views by 8 November.  Thank you. 

An alternative to offering all candidates a tech call with a JAC co-ordinator

1.	Background

There are several reasons for changing the help offered to candidates ahead of their remote selection day. 
•	It is less necessary now that most candidates are familiar with conducting conferences, meetings or other work online and can therefore adapt to interviews being done online
•	Due to budget constraints the JAC has had to drastically reduce the number of front of house co-ordinators and this role will now be carried out by E0s on the selection exercise teams
•	Also there is a misunderstanding among many candidates as to the purpose of the technical call – they think it is a part of the selection process and some are under the impression that they will miss out or be penalised in some way if they do not have it.

2.	Proposal

•	When teams invite candidates to their selection day, they include a link that takes them to a page on the JAC website headed ‘Are you Ready for your Selection Day?’
•	This page will contain clear, plainly worded instructions on how to access MS Teams including advising them on how to download the App
•	It will advise them of the recommended speed for a good internet connection (with a link to an external source that provides this information) and a step by step guide on how to test it
•	Advice on what sort of environment they should have for their selection day, namely a quiet location away from distractions and with an appropriate background.
•	Information on using different devices
•	When they will receive their links and when they should access them. 
•	What will happen at registration, preparation and what will happen during the breaks.
•	The web page will cover all the frequently asked questions that we receive.
•	The web page can include links to You Tube demonstrations or anything else that might help.
•	As a final backup, candidates will still be able to request a call with a co-ordinator if they feel concerned.

**Comment by JeremykJAC** [comment]
https://www.figma.com/file/YWlSW6gFpA6AT4VZwVTVMz/The-alternative-webpage-to-Tech-Call?node-id=0%3A1&t=DRFRYzW3ZKh7NqV3-0
