### ISSUE TITLE
Update of Candidate Login Email Address on admin

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1839]
When an admin updates an email address of a candidate under the action tab, if they try to use an email address already on the platform they are shown an error message on screen. This is confusing to admin as they are not sure why the error has occured.

The message should be revised to say "An account already exists with this email address. To update the candidate login email address with this email address the other account will need to be removed. Please contact the Digital Team for assistance."

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/1a2d3c8a-9063-4dd1-a46d-7ca61370f656)

**Comment by warrensearle** [comment]
This has been user tested and passed as:
1. Badly formatted emails are validated correctly
2. Existing email address are highlighted with an appropriate error message
