### ISSUE TITLE
New QT platform Bugs

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1848]
The following bugs have been found by users:

New QT Platform
Admin:
All tests currently being marked as “Dry run”. - There is no tickbox to specify whether the test is a dry run or not. 
When creating a test, the email invite box (previously shown only if you tick “dry run”) will always appear. The test is marked as “dry run” regardless of if you place emails here or not. For live tests, will we be handling invites via this box? i.e pasting all candidate emails in.  

When clicking “Open tests”, green box has a loading circle then says “error” and moves to right hand-side. 
This happened every time I opened tests on the mock tests I created. The tests did create correctly on the candidate-side. Didn’t notice any issues that might have caused. Ran through tests as a mock candidate just fine and answers registered correctly.
 

Candidate:

(Minor and also present on old platform) Formatting on the Important information section of the introduction: 
Double spacing and no period on the first point. 

•	This test contains  3 questions 
•	You have 40 minutes to complete this test.
•	You must submit your test by 17:00 today.
•	Make sure you've got a stable internet connection before you start.
•	Once you have started the test, do not open the test on a second device.
•	Your answers will be saved as you go through the test, but you can still edit them at the end before you submit your test.
•	If you experience any technical issues please contact the helpdesk.
•	If you run out of time, we will submit whatever answers you have completed up until that point.

**Comment by warrensearle** [comment]
Hi @andrew-isaac the following has now been fixed:
> Double spacing and no period on the first point.

**Comment by warrensearle** [comment]
The "Open tests" button moving and briefly showing an error will be addressed in the work to improve the QT admin page flow - where we will tidy up the buttons and make the process of creating and running a QT more intuitive.
(the issue spotted is not a blocker and looks like an issue with having two instances of our `ActionButton` component showing/hiding on the same page)
