### ISSUE TITLE
QT Outage Messages

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1852]
Seniors Leaders have agreed the following outage messages during a QT on the QT Platform and Admin platform:

- [ ] A banner should display to all on admin

- [ ] A banner should only display to the relevant candidates, not to all. Ideally, we should have the option to display a banner on the QT home page/QT listings and the ‘Important information’ pages, and a separate option to display a banner to those taking a test i.e. the pages with a countdown timer.

- [ ] All messages should be customisable

I think we should just focus on having the banners implemented for QTs for now and consider in slower time whether there is value broadening out to the apply side. 

---

The work for this has been moved to QT repo: https://github.com/jac-uk/qt/issues/7

**Comment by warrensearle** [comment]
> The work for this has been moved to QT repo: jac-uk/qt#7

Suggest closing this ticket
