### ISSUE TITLE
Upgrade Admin to use the latest Firebase library

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1898]
**Background**
The Firebase update was planned in the Roadmap for Q4 2023, but it was postponed to early 2024 as lower priority work due to support for our current version still being available to later on in 2024. The plan is to upgrade Admin first, as we’ll get feedback/bug reports quicker from staff and if there are bugs then they’ll be lower impact than on Apply or QT platforms.

**Useful links**

https://firebase.google.com/docs/web/modular-upgrade

**Comment by warrensearle** [comment]
This is paused until the Vue 3 upgrade has been completed (so we don't have two major changes happening at the same time)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1898?planning-poker) with Zenhub @drieJAC @warrensearle @tomlovesgithub
