### ISSUE TITLE
Assessment notifications with apostrophe in the email address are not being sent

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1900]
Assessment notifications with apostrophe in the email address are not being sent

https://admin.judicialappointments.digital/notifications

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/3a2e11da-1ac2-4dbb-8ef1-9e4f952150d6)

**Comment by warrensearle** [comment]
Note, if we can get emails with apostrophes sending then this ticket should also check to make sure the Assessments platform itself supports apostrophe in the email address too as it is sent in a url and _may_ not be being encoded

**Comment by HalcyonJAC** [comment]
Note: I have tested the Notify endpoint and it seems that an email with an apostrophe will be considered an invalid email address.

Here is the screenshot of the API response.

![Screenshot 2023-05-09 at 14.10.26.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/44f452d3-ff7f-4617-910f-8653da20bbc6)
