### ISSUE TITLE
Application Submission Email - Firebase ID

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1943]
Candidates receiving an email confirming their application are also being sent the exercise ID number generate from Firebase.

Candidates only need to see the name of the exercise they have applied for and not the ID - can this be removed please?

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/c730cbe5-a4f4-4ef4-a5fc-c18b23d550d6)

**Comment by HalcyonJAC** [comment]
1. The exercise id can be removed by amending the email template on [GOV UK Notify](https://www.notifications.service.gov.uk/services/0abe6c8e-0b87-4cde-9493-5da4921ccc53/templates/all/folders/2429dce4-6820-454f-a231-199e2a753366).

2. Should we apply the same change on the application reminder email?

**Comment by warrensearle** [comment]
Hey @HalcyonJAC please replace the Exercise ID with the reference number. So we can have, for example:

JAC00129 Judge of the First-tier Tribunal

**Comment by HalcyonJAC** [comment]
Okay, I will replace it with the reference number. Thank you @warrensearle.
