### ISSUE TITLE
Targeted Outreach NINO Issue

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1949]
Just to update you, I am trying to put together updated data for the Targeted Outreach team this week so have just had a go using the tool again.

I’m very happy with the fixes to the title spilling issue and the statuses, thanks they are working fine now. But the report is still missing some candidates for me. I can provide the team with details for examples if that would be helpful. I suspect it might be to do with some of the NI numbers on the platform being saved with line-breaks in the character string – all the ones not working for me that I have sampled have this issue (although I also found a line-break in one that is working! Possibly different kinds of line breaks).

Hopefully, if it is something of this sort, it would be a very easy fix, so if the team were able to have a look at this asap that would be really helpful for me.

**Comment by warrensearle** [comment]
This issue has been fixed. It was a data issue where old records contained uppercase NINO whereas newer records and our search code converts NINO to lower case. We have transformed old data into lower case which is now stored in a dedicated field `computed.nino`.

In testing out this feature we discovered a number of bugs/improvements which have been captured in follow up ticket: #1981
