### ISSUE TITLE
Changes to Equality and diversity Form

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1952]
Just picking up from our conversation on Slack, the questions to be included on the application form from 1st April are the three below. These would replace the existing three social mobility questions (around schooling, Oxbridge and university attendance). I know that the last two are very similar to ones we already ask but we have agreed to standardise the exact wording of the questions and responses across all JDF members (JO, Bar Council, Law Society etc).

Happy to chat about this. Aware we have the application working group later today which may touch on similar things.

Best wishes,
Sean

What was the occupation of your main household earner when you were about aged 14?

• Modern professional & traditional professional occupations such as: teacher, nurse, physiotherapist, social worker, musician, police officer (sergeant or above), software designer, accountant, solicitor, medical practitioner, scientist, civil / mechanical engineer.
• Senior, middle or junior managers or administrators such as: finance manager, chief executive, large business owner, office manager, retail manager, bank manager, restaurant manager, warehouse manager.
• Clerical and intermediate occupations such as: secretary, personal assistant, call centre agent, clerical worker, nursery nurse.
• Technical and craft occupations such as: motor mechanic, plumber, printer, electrician, gardener, train driver.
• Routine, semi-routine manual and service occupations such as: postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, sales assistant, HGV driver, cleaner, porter, packer, labourer, waiter/waitress, bar staff.
• Long-term unemployed (claimed Jobseeker’s Allowance or earlier unemployment benefit for more than a year).
• Small business owners who employed less than 25 people such as: corner shop owners, small plumbing companies, retail shop owner, single restaurant or cafe owner, taxi owner, garage owner.
• Other such as: retired, this question does not apply to me, I don’t know.
• I prefer not to say.

Which type of school did you attend for the most time between the ages of 11 and 16?

• A state-run or state-funded school – non-selective
• A state-run or state-funded school – selective
• Independent or fee-paying school
• Independent or fee-paying school, where I received a bursary covering 90% or more of my tuition
• Attended school outside the UK
• I don’t know
• Prefer not to say

Did either of your parents attend university and gain a degree (e.g. BA/BSc or equivalent) by the time you were 18?

• No, neither of my parents attended university
• Yes, one or both of my parents attended university
• Do not know / not sure
• I prefer not to say

**Comment by warrensearle** [comment]
This following will need to be changed:

- [x] Apply. Changes to the Equality & Diversity Form. See https://github.com/jac-uk/apply/pull/992
- [ ] Apply. Changes to Equality & Diversity on the Review page
- [ ] Admin. Update application view with new social mobility questions
- [ ] Admin. Update diversity report with new social mobility questions
- [ ] Admin. Update custom report with new social mobility questions
- [ ] Admin. Update dashboard with new social mobility questions
- [ ] Admin. Update all downloads with new social mobility questions
