### ISSUE TITLE
164 - Medical Members - Application Changes

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1974]
### 164 Medical Members is launching Tuesday 2nd May but there are a few bug/issues that need to be changed with the application. Can this be done via a hardcode fix as it is only specific to this exercise:

These question appear on the admin and the apply side for this exercise, so both will need to be changed.

Exercise: https://admin.judicialappointments.digital/exercise/60gxK6pV3TeFKYYnAWg3/details/overview

1. Relevant Qualifications - Can this be removed as none apply for this exercise and when opened it is blank 

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/e4c4251e-c517-4375-b569-0d7d334d0ca5)

2. Judicial Experience - There is several changes needed here:

- The  `Are you a fee-paid or salaried  judge` needs to be changed to `Are you a fee-paid or salaried medical member`

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/262104b6-3313-44b5-a0b8-df4acda1f94b)

- If yes is given to the question above about the sitting days it stays as the screenshot below

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/8c55a360-2073-4170-bd4f-2b5e96b55640)

- if no is given to the question about sitting days the `Have you declared an appointment or appointments in a quasi-judicial body in this application` and the link to it should be removed

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/4145d14a-a373-4d31-a7ae-90760d851e70)

- In place of the question removed above the following question should be inserted if someone selects no to sitting days `If you do not have previous experience as a Fee-paid Medical Member in the Social Entitlement Chamber, please tell us what equivalent experience and skills you have in the box below` The candidate should be given a 250 word limit free text box to provide an answer. - It is similar to like a box that is already there

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/670c14f3-c1c4-4ec6-9d6b-946d72ec33a3)

- If no is given to the `Are you a fee-paid or salaried  judge` which will be changed to `Are you a fee-paid or salaried medical member` question as mentioned above then the `Have you declared an appointment or appointments in a quasi-judicial body in this application` and the link to it should be removed

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/f69f8c45-5d87-4b08-b610-50232a1260bb)

- The above scenario should be replace replaced with `If you do not have previous experience as a Fee-paid Medical Member in the Social Entitlement Chamber, please tell us what equivalent experience and skills you have in the box below` The candidate should be given a 250 word limit free text box to provide an answer.

**Comment by warrensearle** [comment]
Then changes to Apply have been deployed via hotfix 1.64.3

The corresponding changes in Admin are in progress [PR TBC]
