### ISSUE TITLE
Recording Feedback on Platform

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1986]
As an admin I want to be able to record feedback requests on the platform instead of holding multiple sheets in sharepoint.

Please note Figma design created - https://www.figma.com/file/rTLBmK3Xwy1ZZhVlMRMpHl/%2Fadmin%2F645-Recording-Feedback?type=design&node-id=1-16726&t=30WvGpumJgS9DhmE-0

One change from the Figma is Teams should be able to select a candidate from a list of those who have applied for the specific exercise instead of having to type in names for each request.

**Comment by warrensearle** [comment]
Please hold off further build until cleared by @MattHowley

**Comment by nickaddy** [comment]
@MattHowley to touch base with @tomlovesgithub on this ticket.

**Comment by nickaddy** [comment]
@MattHowley @tomlovesgithub Can you pls, if possible, touch base before the sprint planning session this afternoon?

**Comment by nickaddy** [comment]
Agreed with Matt and Norma that, based on user feedback, there is no strong demand for this functionality to be incorporated into the platform. Descoped.
