### ISSUE TITLE
Application Deletion

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1994]
The following applications need to be deleted as per request of Senior Leaders:

Hi Matt/Andrew,

 
In reference to the below; the candidate [JAC00086-aan0098]
(https://admin.judicialappointments.digital/exercise/mvfZbVyM8mTFPqUMIqJV/applications/draft/application/gUTQG8XljxrtFTOc5k4F) is currently marked as draft and is displaying in the draft applications tab and the candidate [JAC00086-sgp0221](https://admin.judicialappointments.digital/exercise/mvfZbVyM8mTFPqUMIqJV/applications/withdrawn/application/gETI0PPCEFwrMJG8Io4J) is also marked as draft but is still being displayed in the withdrawn tab. Since the recommendation below is for both those applications to be deleted, is that something that @Isaac, Andrew | (He/They) or @jacdigital can do?

![Image](https://user-images.githubusercontent.com/97609636/238394299-0564b831-427f-4652-b2eb-aa24b2b19e13.png)

**Comment by HalcyonJAC** [comment]
Note: here is the information of applications that need to be deleted:

1. 
Reference number: JAC00086-sgp0221
application full name: Ramola Naidoo
application id: gETI0PPCEFwrMJG8Io4J
applicationRecord id: mKeDTFwbqoTcTB7P3wD1qIGA9RW2

2. 
Reference number: JAC00086-aan0098
application full name: Genevieve Chabot
application id: gUTQG8XljxrtFTOc5k4F
applicationRecord id: ZmSjtfRtqlhek6OMYLYpfDIoQPG3
