### ISSUE TITLE
Exercise Delete Button - Main Overview Page

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1997]
As a Digital Super User I would like a button on the main exercise overview page where I can select multiple exercises using the check boxes and press a button to delete them from either Develop, Staging or Production. 

Ideally it would sit next to the Archive Button and only be visible to those with the Digital Super User Role.

![Image](https://user-images.githubusercontent.com/97609636/238598640-ea844f1a-f6a2-446f-beba-054efa36daea.png)

**Comment by HalcyonJAC** [comment]
@andrew-isaac Should we allow to delete only draft exercises?
