### ISSUE TITLE
Exercise Contacts - Email search/dropdown

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1999]
Currently Admin users need to input their JAC email address when completing the contact details of an exercise. Instead of this and to reduce keying errors can users instead select from a drop down of users to populate this information?

![Image](https://user-images.githubusercontent.com/97609636/238606425-426d86da-63cc-4bc3-ab6d-952aae3d4b19.png)

**Comment by HalcyonJAC** [comment]
Note: the enabled admin users with Microsoft login will be in the drop down.
