### ISSUE TITLE
Exercise Approval - Feedback Chain

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#2008]
If exercise approval is rejected and the SL is able to write a comment/note as to why. When the colleague has made required changes and is resubmitting, a text box reply could also be useful to maintain all comms on the one platform.

Add the option for SET to write text back to SL and keep a log of all comms on the platform

**Comment by warrensearle** [comment]
This is quite close to the exercise approval track changes ticket being worked on by @drieJAC

**Comment by drieJAC** [comment]
No longer need to keep a log of the comms on the platform after conversation between Warren and Matt.
This ticket is currently blocked awaiting a discussion on whether this fn'y is still required.
A PR exists for it. See: https://github.com/jac-uk/admin/pull/2066
