### ISSUE TITLE
Exercise Approval Filter - UT Feedback

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#2009]
On SLs approving exercises - it would be helpful to have a filter on the page with exercises listed where you can filter out exercises that require clearance or if the exercises requiring clearance are identified on the list differently somehow. At the moment, all the exercises that are listed, approved or not, all look the same.

Explore option of adding a filter onto main page of exercises to filter by approval state

**Comment by drieJAC** [comment]
Add a new column to the live exercises table to display the approval status (requested, rejected, approved).
This column should not be sortable.
The data for this column will come from exercise._approval status (doesnt need to sort)

Add a dropdown (or 3 checkboxes) to the table filters. This new filter will allow the user to select an approval status to filter by.
