### ISSUE TITLE
ADMIN: Exercise document uploads.

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#202]
Changes to exercise download pages: 

Please can you "add another" upload facility for Pension Note(s), Competency Framework and Welsh Translation.  This is a temporary measure until we can combined two exercises into one more effectively.  

Please can you a new title and upload fields for another REPEATABLE upload.  Title "Pension documents".  

We may have more than one document so this must be repeatable.  

These need to display and be downloadable to the candidate on the exercise information page under "Related Content".  

Checklist

- [x] Add a new downloadable field for "Pensions Information"

- [x] Allow for unlimited "add another" options for Pensions information

- [x] Add unlimited "Competency framework" upload field

~~- [ ] Keep one independent assessment template and Candidate assessment template only per exercise~~
        ⮑ moved to new ticket #587

- [x] Add a new downloadable field for "Welsh translation"

- [x] Allow for unlimited "add another" options for "Welsh translation"

- [x] Storage names for the additional pension note(s) and competency framework(s), the database can have this type of name pension note 1 or competency framework 2, the welsh translation 1 or translation 2.

**Comment by Rebecca-mcknight1991** [comment]
@ClaireTroughtonJAC need clarity on this. @Rebecca-mcknight1991 write up fully.

**Comment by YaaL** [comment]
@ClaireTroughtonJAC This will be partially done with what I'm doing for #372 - would be nice to clean this up.
