### ISSUE TITLE
Signage for unpublished exercises

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/admin#2023]
An admin raised an issue whereby the updating of details on a live exercise unintentionally caused the exercise to become unpublished and unseen by candidates, this only became evident once candidates contacted to ask if/why the exercise was closed. 
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/21cd51d7-5523-4734-83d0-70dd23405706)
In order to remedy this some changes should be made to the overview page;

- [x] Increase the font size of "Published"/"Unpublished" in the blue status box (top of page)
- [x] Move "Congratulations! This exercise has been approved. Now you can publish it to the website." into a banner component and place at the top of the page.
- [x] Insert a warning banner that appears when an exercise is in an "unpublished" state whilst within the application window.

....Bonus
- [x] fix "webstite" spelling error

**Comment by andrew-isaac** [comment]
@tomlovesgithub  - Please discuss this before implementing these changes, and let us know who gave the feedback and how? @NormaJAC should speak with this user first before we make a change to understand the requirements. To unpublish/publish an exercise is now a function restricted to the SEOs, so around 10 people on the live platform.

**Comment by andrew-isaac** [comment]
@warrensearle  - We discussed this today and I will let you bring @tomlovesgithub  up to speed on what we decided

**Comment by warrensearle** [comment]
@warrensearle and @tomlovesgithub to discuss and simplify this ticket
