### ISSUE TITLE
Application Process

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#2034]
Currently the Application Process section under exercises on Admin is not part of the main Task List "done" check box of an exercise.

This is being missed by Teams when creating new exercises and they are not aware they can customise what sections is shown on an exercise. They are then asking us to manually remove sections of an application when they can do this themselves.

The Application Process should appear in the Task List section and Teams should tick what sections they need. As default all should show but a confirmation is still needed

Warren and I discussed it and will have further details

![Image](https://user-images.githubusercontent.com/97609636/246218916-a43881b3-3934-45ad-9f71-44fcbd36da29.png)

![Image](https://user-images.githubusercontent.com/97609636/246219058-d1a7c39d-66b2-4a43-8b14-867d700653a6.png)

**Comment by drieJAC** [comment]
Needs retesting after making Warren's suggested changes to ensure the Save & Continue button can be pressed without needing to complete all the sections.
