### ISSUE TITLE
Restrict size and type of files that can be uploaded

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#206]
Right now, there are no file size limits or file type restrictions. 

The restrictions we would like for uploads in admin are:
- docx, txt, pdf

See below image for error messages to display:
![image](https://user-images.githubusercontent.com/56963348/72826160-3d429980-3c70-11ea-825d-7d4b0a4f985c.png)

**Comment by ClaireTroughtonJAC** [comment]
Update @warrensearle the file types we would like to restrict to are:

docx, txt, pdf, pages, google docs,

**Comment by londonprojects** [comment]
@warrensearle will break up story

**Comment by warrensearle** [comment]
This issue has been added to the following repos:

- Admin admin#206
- Apply apply#330
- Assessments assessments#42
- Digital Platform digital-platform#327

**Comment by crablab** [comment]
The extensions I'm including for now: 'pdf', 'docx', 'doc', 'odf', 'pages'

(ODF is a open source equivalent to the propitiatory Microsoft formats. Word can open it.)
