### ISSUE TITLE
Statutory consultation report

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2089]
**User story**
As the Judicial Office, I would like candidates’ judicial career history to be separated from their non-judicial career history AND their career history to be automatically reordered in date order (with the most recent post first, working backwards) so that I can better review their experience for the role.

**Background**
We have already built functionality to download candidate information into an excel spreadsheet, the expressed preference of Judicial Office. This information is shared to assist Judicial Office in considering who to involve in the statutory consultation process and to provide those involved with pertinent information about each candidate to assist them in providing relevant information pertaining to the candidates. Judicial Office have asked whether a number of small changes to the format can be implemented, most key is to separate out candidates’ judicial career history from their non-judicial career history. This work is dependent on the review of the application form by the Application Working Group, but some quick wins can be made in the interim by improving the format.

Exercise JAC00136 has content that can be reviewed. Click the Export Data button to review the current format.

![image.png](https://images.zenhubusercontent.com/64a540c0fc632dc95351b78a/61df8c56-74b1-4e23-8dd5-b45dd36f3b86)

The differentiator between judicial and non-judicial is where the candidate selects from the tick boxes; if they select 'the carrying out of judicial functions of any court or tribunal' it is judicial, any of the other options are non-judicial. Gaps in employment do not need to be included.

**Timeline**
Due early-mid August

**Screenshot(s)**
![image.png](https://images.zenhubusercontent.com/64a540c0fc632dc95351b78a/b9ebed8b-0f5d-45eb-adb9-361c1f8eaefb)

**Comment by MattHowley** [comment]
Looks good @HalcyonJAC and @nickaddy

**Comment by nickaddy** [comment]
@MattHowley Are you happy, then, for this to be merged into Production so that you can test with real data?

**Comment by MattHowley** [comment]
Yes please @nickaddy

**Comment by HalcyonJAC** [comment]
@MattHowley @nickaddy Okay thanks. I will merge the PRs and then release them to production.

**Comment by nickaddy** [comment]
Over to you @HalcyonJAC

**Comment by HalcyonJAC** [comment]
@MattHowley @nickaddy It has been deployed to production.
