### ISSUE TITLE
Digital issue resolution ticketing system

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2095]
Background
Currently, users share digital platform issues with the Digital team through a Slack channel, but the system does not allow easy tracking, assigning and monitoring of issue resolution, metrics, etc.

User Story/Stories
As a user, I would like to be able to quickly share an issue on the digital platform with the digital team so that they can be resolved.

As the digital team, I would like to view all the pertinent information about an issue identified by a user so that it can be resolved without any additional correspondence.

**Comment by nickaddy** [comment]
@warrensearle presented a possible solution in GitHub projects 03/08.

**Comment by nickaddy** [comment]
@tomlovesgithub to prepare a prototype for user/digital team input.

**Comment by warrensearle** [comment]
@tomlovesgithub has created a Miro here:
https://miro.com/app/board/uXjVMvZy_gs=/
