### ISSUE TITLE
Vuexfire replacement

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2098]
It appears that vuexfire is no longer supported in Vue 3 and Vuex. This is causing our state to no longer be reactive.

The recommended way forward is to switch to using Pinia instead of Vuex and make use of VueFire, if necessary.

Alternatively we may be able to remove Vuexfire from our Vuex stores and use `firestore.onSnapshot` directly, perhaps with our own helper method (to react to changes).

We need to find a quick solution as state no longer being reactive is a problem being experienced by users on Admin production.

**Comment by HalcyonJAC** [comment]
1. Pinia + VueFire
    - Migrate from Vuex to Pinia
    - Migrate from VuexFire to VueFire (VueFire requires Firebase JS SDK >= 9)
    - Upgrade Firebase JS SDK to 9+ (can keep using the namespaced (`compat`) API but should consider moving to the modular API)


2. Use `onSnapshot` directly
   - Need to implement something like this:
      ![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/e30879aa-f48d-4da7-b532-4bf7bef76b6f)

**Comment by HalcyonJAC** [comment]
@warrensearle I have tried this package. The binding data seems reactive but the table pagination will be broken or sometimes crash the page, e.g. the data is not loaded properly when I click the next page on the exercise list.
