### ISSUE TITLE
If a user already has an account for the DP admin they are not allowed to sign in for candidate.

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#210]

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle please can you confirm if this issue has been superceded?  Can the issue be closed?

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC I think we should get this tested so we know whether there is still work to do or the issue can be closed.

**Comment by Rebecca-mcknight1991** [comment]
Moving to phase 2 due to time limitations and other more urgent priorities. Also want to ensure candidates can 1) edit certain parts of profile/application 2) reset password 3) change email address 4) significant testing on non-mac devices and a range of browsers is done before we stop admin being able to do this. Basically we want there to be no real need for admin to do this and the responsibility to be safely left with candidate.
