### ISSUE TITLE
BUG: Exercise page alignment is breaking after on-screen error messages are displayed

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2120]
The alignment of the Exercise page is sometimes breaking. 

For example see the following screen grab and observe that from "< Back" down the content has shifted to the left and is partly out of sight:

---

<img width="678" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/3422456f-c386-48ba-9acc-4315f9e27a22">

---

**Steps to replicate**

 - Navigate to Exercise > Update timeline
 - Amend the form so that at least one required field is empty
 - Press the Save button to generate an Error Summary and associated Error Messages
 - Observe that the page layout has 'broken'

_Note that there may be other ways to replicate this behaviour and it does not appear to be specific to the Timeline form_

**Estimate**
S

**Comment by nickaddy** [comment]
@warrensearle Small?

**Comment by warrensearle** [comment]
> @warrensearle Small?

Yep Small
