### ISSUE TITLE
Eligibility and character Excel downloads

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2124]
**Issue Title**
Eligibility and character Excel downloads

**[History/context]**
At present, each declaration made by a candidate concerning eligibility and character is included in a single cell on the excel download. This makes the information more difficult for teams to search through. We should look to extract the data so that each declaration shows in a separate row. Admin users would like to see each application form declaration entry in a separate row on an Excel download. Would like to see it exactly as it is on the application form, a row for each question (e.g. Qualification entries should be in separate rows from Post qualification experience, a barrister can be exempt from pupillage - have it as a row stating that they are exempt and have uploaded an exemption certificate.)

**USER STORY** 
As an admin, I want each candidate eligibility and character declaration entry to be in a separate cell on an Excel download so that I can extract the data exactly as it is on the application form. 

**[Acceptance Criteria]** 
Each declaration entry to be in a separate cell on an Excel download

**[User Testing Steps]**
Go to an exercise page, click on reports, click on character issues, click on generate report, click on export to Excel.
Check that all the declaration entries are in separate cells on the Excel download.

**[Ticket Champion]**
Roadmap item.

**[Screenshots / wireframes / designs / pictures]**
**"As is"**
Character download
![image](https://github.com/jac-uk/admin/assets/138654969/8faf0faa-5092-44c5-a664-3ddf32db6311)

Eligibility download
![image](https://github.com/jac-uk/admin/assets/138654969/3ceac970-d657-49ef-9483-6a93e36a6913)

**"To be"**
Character check - column M, O, AH and AI (Character information, Professional background, Qualifications and Post qualification experience)
![image](https://github.com/jac-uk/admin/assets/138654969/c41ff427-7769-47fc-9da7-44a84def13fd)

![image](https://github.com/jac-uk/admin/assets/138654969/1e632106-0426-48f7-90fa-9522cb06f4d9)

![image](https://github.com/jac-uk/admin/assets/138654969/a55faf0d-6944-4840-ae93-f32c79a30b7c)

Eligibility issues - column J and K (Qualifications and Post qualification experience)

![image](https://github.com/jac-uk/admin/assets/138654969/95d28bdd-87a7-4c55-a40f-87492bee6aee)

![image](https://github.com/jac-uk/admin/assets/138654969/2c0f36f8-f94b-4f70-b5ee-be9429ad3e85)
**[Happy Story**
To be able to see each declaration entry in separate cell which allows admins to save time when extracting data. 

**[Sad story]** 
 Admins have to spend time copying and pasting data from one cell into separate cells.

**Comment by NormaJAC** [comment]
@nickaddy, FYI

**Comment by nickaddy** [comment]
@NormaJAC I have moved this ticket to Ready to Play as I believe all the content is there. Over to you @HalcyonJAC :-)
