### ISSUE TITLE
Diversity monitoring report

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2125]
**Issue Title**
Diversity monitoring report - amendments to questions

**[History/context]**
Remove 'gender neutral' and 'other' options from question pertaining to sex in diversity monitoring form. Not in line with Equality Act or best practice. 

**USER STORY**
As an applicant/admin user, I want 'gender neutral' and 'other options' removed from the question pertaining to sex in diversity monitoring form so that it will be compliant with the Equality Act. 

**[Ticket Champion]**
R Collumbell

**Comment by nickaddy** [comment]
@drieJAC This is the other minor change I mentioned in relation to the Diversity Report work. Is there enough info on this ticket for you to action or do you need more detail?
