### ISSUE TITLE
Amendments to Application Counts

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2147]
**User Story** 
As a user, I would like the actual number of applications (those with applied status) to be displayed clearly on the Exercise listings and on the exercise dashboard so that it is clear how many completed applications have been received.

**[History/context]**
Under exercise listings and on the specific exercise dashboard, the total number of applications, including draft, applied and possibly withdrawn is displayed. This provides an inaccurate description of current application status overall.

**Feature** 
1. On the Exercise listings page (Image 1), the number displaying under Applications Count should reflect the number of completed applications, i.e. as per image 2, 6 applications in this case.
2. The column title should be amended to 'Submitted Applications'
3. On the Exercise Dashboard, the Total Applications should feature a breakdown of the applicant status (images 3 and 4)

Image 1:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmJZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--673c18634bf9bf0775c8316856f434129aa0cd91/image.png)

Image 2:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkxZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb381dac040777edacdf1ba79ecb00c60811e2e9/image.png)

Image 3 (as is:)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2pZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d5e6cb93d5f27732ebe6d6165d5b447559b8f5d/image.png)

Image 4 (to be:)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcERZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55b491b91080bf780af85e64b66e839af647d30c/image.png)

**Estimate** 
Small (<2 days)

**[User Testing Steps]**
TBC

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2147?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub
