### ISSUE TITLE
Save and Continue button should scroll to error summary (top of form) if there are errors with the form

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#215]
As I user I want to know where my errors are on the page when I press save and continue. So that I can quickly identify the error and amend it.

**Comment by enoranidi** [comment]
As per GDS guidance here: 
Error summary - https://design-system.service.gov.uk/components/error-summary/
Error message - https://design-system.service.gov.uk/components/error-message/

Those two examples are separated but here is an example (from GOV.UK) with both parts together:

![Error  Card billing address - Pay your Self Assessment - GOV UK.png](https://images.zenhubusercontent.com/5e661c911c5fcd09081b885e/98500dbf-91a7-4bf3-bc08-2d90e0d9abcc)

**Comment by YaaL** [comment]
Note: we do not reload the page to check for errors.

**Comment by warrensearle** [comment]
@enoranidi should we have page transitions? So, for example:

 - click the Save & Continue button
 - the screen transitions into a waiting/thinking state (perhaps an overlay with some fade in/out)
 - after a comfortable delay the screen transitions to the next page

If so then we could use this to have the user end up on the same page displayed from the top.

If not then I guess we just jump straight to the top of the page.

**Comment by enoranidi** [comment]
@YaaL Oh, so what happens then?

Perhaps a demo on your screen so I can make sure I am viewing the correct interactions for this ticket?

**Comment by KateMJAC** [comment]
This appears to have been completed.
