### ISSUE TITLE
Configure working preferences questions

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2154]
See Apply: [Working Preferences questions](/jac-uk/apply/issues/1072)

## Improvements to existing functionality

- [x] Working preferences questions should be mandatory (if configured)
- [x] Ranking. Should not be able to skip numbers - e.g. choosing two answers from five means user can choose 1st and 2nd choice, not 1st and 5th
- [x] Enable multiple location questions. (e.g. this will enable preferred and maybe selections)
- [x] Enable multiple jurisdiction questions. (e.g. this will enable preferred and maybe selections)
- [x] Define how many answers candidates should select
- [x] Enable linked questions
- [x] Enable grouping of answers (two levels)
- [x] Allow re-use of jurisdictions from vacancy information (for jurisdiction questions)
- [ ] Allow questions to be re-ordered (e.g. move question 3 to be question 1) 

<img width="960" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/f0e5327b-8aa1-4944-93d3-0facbe1fe61a">

## Use Jurisdictions from Vacancy Information
In the Vacancy Information part of the exercise SETs configure which jurisdictions are part of the vacancy.
Rather than enter these from scratch for the Jurisdiction question we should offer SETs a way to instead use the jurisdictions they've already configured in Vacancy Information

<img width="957" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/97a1d989-20f6-401d-973a-d1619a4b778d">

## Allow linked questions
Sometimes locations are specific to a jurisdiction (and vice versa).
To facilitate this we will allow answers to have linked questions such that if **Answer A** is chosen then the candidate will be asked the linked question for Answer A

Configure a question to have linked answers:
<img width="956" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/4056e7ae-a648-4e94-a465-a80a183dcb9e">

Link a question to a linked answer:
<img width="1401" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/2692f246-5982-46ff-bd7e-811a69e03eba">

## Allow grouping of answers
On some occasions there are so many answers it is useful to group them
For example clusters (of courts) may be grouped into circuits, such as:
 - North East
   - Newcastle
   - Durham
   - Teesside
   - Bradford
   - Sheffield
 - North West
   - Carlisle
   - Lancaster
   - Bolton
   - Crewe
 - London
   - Fleetbank House
   - RCJ
   - Alfred Place
   - Central London
 - South East
   - Luton
   - Bedford
   - High Wycombe
   - Maidstone
   - Horsham
   - Colchester
 - South West
   - Truro
   - Plymouth
   - Gloucester
   - Bristol

Here the user is choosing the lower level answers (the clusters or courts). The groupings (circuits) are just there to aid navigation.

<img width="953" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/4302b73f-809d-4e70-8e69-5fa4c507dfb1">

---

See the following [visuals](
https://www.figma.com/file/aqILfbMFEy51XDaFZpid8i/Ranked-answers-with-linked-questions?type=design&mode=design)

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2154?planning-poker) with Zenhub @drieJAC @tomlovesgithub @HalcyonJAC

**Comment by nickaddy** [comment]
@warrensearle Will there be a separate ticket to pick up any associated dev work on working preferences or is that assumed in this ticket?

**Comment by warrensearle** [comment]
> @warrensearle Will there be a separate ticket to pick up any associated dev work on working preferences or is that assumed in this ticket?
Here is the sister ticket (on apply)
https://github.com/jac-uk/apply/issues/1072
