### ISSUE TITLE
Amend Situational Judgement Test Instructions

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2156]
As is:

Important information
This test contains 2 questions.
You have 55 minutes to complete this test.
You must submit your test by 21:00 on 1 January 2024.
Make sure you've got a stable internet connection before you start.
Once you have started the test, do not open the test on a second device.
Your answers will be saved as you go through the test, but you can still edit them at the end before you submit your test.
If you experience any technical issues please contact the helpdesk.
If you run out of time, we will submit whatever answers you have completed up until that point.

To be:

**Important information**
• This test contains **2 questions**
• You have **20 minutes** to complete this test
• You must submit your test **by 21:00 on 1 January 2024**
• Ensure your internet connection is stable **before you start the test**
• If you experience any technical issues, please contact the helpdesk
• Once you have started the test, **do not open the test on a second device**
• Your answers will be saved as you progress, but you will be able to edit them at the end before you submit your test, assuming you still have time remaining
• If you run out of time, we will submit whatever answers you have completed up until that point.

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2156?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub
