### ISSUE TITLE
Live Exercise Export bug

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2158]
**Describe the bug**
When 2 or more exercises are selected on the Live Exercises page - image 1 - and the Export Data button clicked, the report features an extra column - see image 2 - columns K and L are duplicates, and the data ends in column AD rather than AC. Furthermore, if 3 exercises are selected, an additional duplicate column is created, with 4 exercises another one, and so on. This is causing lots of issues putting together data for our monthly Rolling Diversity Report, and other purposes.

**To Reproduce**
1. Go to [Live Exercises](https://admin.judicialappointments.digital/exercises)
2. Select multiple exercises, e.g. 130 and 131, and Click 'Export data'
3. Open the download and note that columns K and L are duplicates
4. Repeat with 3 exercises if desired

**Expected behavior**
Irrespective of how exercises are selected, the exported spreadsheet should only contain a single column for 'Attended state or fee-paying school'. Please share with Sean for UT once fixed.

**Screenshots**
**Image 1**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFQxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47eea9c164d603c0c563eced355b087d9fdfc20e/image.png)

**Image 2**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEgxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89424803f5f71dadfefd3c7fb688508f34696a47/image.png)

**Comment by warrensearle** [comment]
Note that if exercises are selected from before **and** after the social mobility questions changed on 01/04/2023 then the download will contain extra columns. We'll need columns for both sets of questions.

In this case I propose we prepend "[pre 01/04/2023] " (or similar [TBC]) to the three older questions as one or two of them had similar titles to the new questions.

**Comment by nickaddy** [comment]
@HalcyonJAC Hi Ryan, I know this is live now, but it should still be code reviewed - can you request approval from other Devs, pls?
