### ISSUE TITLE
Bug: Exercise. Eligibility Information. ASC word limit messaging is illogical

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2165]
In Exercise > Eligibility Information the Additional Selection Criteria can be configured to have a word limit. The label/hint for the word limit field suggests if the field is left empty then the word limit will default to 250. However the field is required which doesn't match up with the labelling.

Here's an image of the field when the form is submitted with no value:
<img width="891" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/24857624-8092-4b41-bb84-5bb2f249a3fa">

**Actual**
Messaging suggests entering a value is optional however validation requires a value to have been entered.

**Expected**
Messaging and validation should make sense. Either:

 - Messaging remains as is and validation does not require a value to have been entered (i.e. field is optional)

Or:

 - Messaging remains as is. The field value defaults to 250 when the exercise is created and also if the user empties the field.

[ @nickaddy please confirm the behavior you'd prefer ]

**Comment by warrensearle** [comment]
There is a [slack thread](https://drie.slack.com/archives/C02QHCFD10C/p1699441287082109) related to this bug so have progressed it to be worked on this sprint

**Comment by warrensearle** [comment]
Please also check whether any recent exercises need to have data back-filled

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2165?planning-poker) with Zenhub @drieJAC @HalcyonJAC

**Comment by nickaddy** [comment]
@warrensearle In addition to unmandating, can we amend the text to: 'The default word limit for this question is 250 words, if you would like to customise the word limit, please add the new figure in the field below.'

**Comment by warrensearle** [comment]
> @warrensearle In addition to unmandating, can we amend the text to: 'The default word limit for this question is 250 words, if you would like to customise the word limit, please add the new figure in the field below.'

@nickaddy this change has been made. Please see PR https://github.com/jac-uk/admin/pull/2218
