### ISSUE TITLE
SPIKE: refactor router tests to split tests for functionality and configuration

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#217]
Would it be possible to clarify our unit tests for the router to test:

1. Custom behaviour / functionality added to the router
  - beforeEach `requiresAuth` navigation guard
  - afterEach page title navigation guard
2. Routes configuration
  - Does each route specify the correct `requiredAuth` value?
  - Does each route specify the correct page title?
  - Does each route have the correct path?
  - Does each route render the correct component?
  - Does each route have the correct children, etc.?
3. Router configuration
  - Is 'history' mode enabled?

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle has this been superceded?  Can the issue be closed?

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC this is still valid so have moved to 'Phase 2' rather than closed.
