### ISSUE TITLE
Independent Assessments

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2173]
**Background**
**Independent Assessments request **
Could the wording in the message displayed just before an IA run is despatched, be changed from "candidate(s)" to "assessors"?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--571b6b7543741689168c68236b694479acd39f81/image.png)

**Independent Assessments request email signature**
If the "Email signature name" field in the Contacts tab could allow the use of a name rather than required an email address, as now IA requests are signed off using an email address, which looks a bit odd.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1JLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f603a81b5b9946a6a1c719d1ea7f42ba2d65bc8/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a59edec81ffab6398cd60fd3238e69c499b80cf/image.png)

**Independent Assessments reminder**
The phrasing also needs to be updated when sending reminders to assessors, as it’s got the "candidate" wording there too. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEpLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a019146229b2903fc2c92eee59943dec44c1898b/image.png)

**User Story** 
As an admin, I would like the word 'candidates' in the Independent Assessments request changed to 'assessors' so that I can see the correct title when sending IA requests.

**User Story** 
As an admin, I would like the "Email signature name" field in the Contacts tab changed to the Selection exercise manager's name, so that IA requests can be signed off using a name.

**User Story** 
As an admin, I would like the word 'candidates' in the Independent Assessments reminder changed to 'assessors' so that IA reminders show the correct title when sending IA reminders.

**Ticket Champion**
Richard Collumbell

**Happy Story**
Admins would be confident that they are sending out the right requests and reminders to Independent assessors, not the candidates.
Emails sent to assessors will have the Senior Selection Exercise manager's name at the bottom of the email sent to Independent Assessors.

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2173?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub

**Comment by nickaddy** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2173?planning-poker) with Zenhub @warrensearle
