### ISSUE TITLE
Redesigned Diversity Checkpoints report

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2219]
## Background
We are looking to automate the calculation of the difference in % points between checkpoints of an exercise and enable the information to be downloadable in the format used in SCC papers and AA reports and by EFT for quality assurance purposes.

Note: this is an old ticket that was parked for some time whilst clarity was gained on the requirements. There are a couple of draft PRs attached that suggest Ryan has done some foundational work here; however, the requirements may have changed enough that it is easier to start afresh. I have removed the original estimate of 10 to allow re-estimation. You'll need to remove yourselves personally from the planning poker and then re-add yourselves.

## User Story
As Diversity & Engagement, I would like the % change in the diversity of candidates at each checkpoint to be calculated so that I can view on screen and download a report in the appropriate format.

## Feature(s) Description
- [x] On the Diversity report page, add a new column to the right of the existing data titled `% Change from previous` 
<img width="913" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1XQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2653de5f66601c046c44254ea181956404429bd4/image.png" alt="image.png" />
- [x] The figures in the column reflect the percentage change in the listed categories from the previous tab - see [Miro board](https://miro.com/app/board/uXjVLXJX9xI=/) for examples
- [x] The additional column does not feature on the Applied page of the Diversity report as this is the first stage
- [x] The additional column is featured on each tab in the Diversity report - including QTs if present
- [x] The percentage change between checkpoints only should be calculated and displayed for the following rows: Female, Ethnic minorities, Disability yes, solicitors, CILEX, Attended UK State, Parents did not attend University
- [x] The summary tab should display columns for all of the checkpoints in the Diversity report dropdown and rows showing the percentage change only for the categories listed in the previous point
- [x] The Diversity report should be reformatted as per the attached spreadsheet and:
- the cells highlighted in yellow should be populated with the relevant exercise data from the diversity report/additional fields, other cells populated with the content shown
- the cells that are blank will be manually populated 
- rows C-E and G-I should reflect the checkpoints in the exercise, i.e. if QT and/or ST are used for shortlisting, there should be columns for those too
- the download should be an excel file 
- the download should be formatted as in the attachment.
[Diversity Checkpoints v3.1.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0f9d6451c0441cef58719ae85033b04379f08d9/Diversity%20Checkpoints%20v3.1.xlsx)

## Ticket Champion
Nick Wood

**Comment by NormaJAC** [comment]
Created a Diversity checkpoint report draft, sent it to Nick Woods for his input, he replied, that he will respond within a week because he has passed it on to Rachael and Sean for their input.

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2219?planning-poker) with Zenhub @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2219?planning-poker) with Zenhub @drieJAC

**Comment by NormaJAC** [comment]
Comments from Rachael: **_For exercises where there are two shortlisting methods, we would have “post-application”, “post-QT”, “post-ST”, “post-selection day”._**

**Comment by NormaJAC** [comment]
This 2nd requirement of this ticket was blocked at the sprint planning meeting on 19/12/2023, requires further information?

**Comment by NormaJAC** [comment]
Charlotte's email gave some specifics: says: the diversity report figures SETs sent around needed redoing as they had only selected those who met the VR even though there were more selectable candidates post SD. e.g. the VR was 10 so they only selected the top 10 for the report even though (say for example) they had 15 selectable candidates. **So the post SD diversity checkpoint should have been for the 15 selectable candidates and then those who were eventually recommended to make the 10 would then form the next checkpoint.**

**Comment by nickaddy** [comment]
This can be delayed until April.

**Comment by nickaddy** [comment]
@NormaJAC Can you please reach out to the secretariat to confirm that this is the best format for all instances of its usage, e.g. SCC paper, JO, other?

**Comment by NormaJAC** [comment]
@nickaddy this was dealt with after diversity checkpoints meeting with the Rachael and Nick W on 08/03/2024
