### ISSUE TITLE
Enforce strong passwords

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#222]
Pen test result:
"The password length is weak when creating candidate accounts, 6 chars, OWASP recommends 12. There also does not appear to be any complexity requirements as 123456 is a valid password."

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md

To apply to new accounts. May send reset link to existing account holders. Or evaluate password when they log in.

**Comment by enoranidi** [comment]
There is some guidance from GDS here: https://design-system.service.gov.uk/patterns/passwords/

**Comment by enoranidi** [comment]
And adding the 'Show' button as mentioned by MOJ here: https://moj-design-system.herokuapp.com/components/password-reveal
