### ISSUE TITLE
Character declaration updates

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2230]
**Background**
At the digital meeting on 28/11/2023, updates to the character declaration were discussed. The overall functionality is not working and needs to be fixed before we can reengage with users on this feature.

**Feature(s) Description** 

- Reword 'Recommendation' to: **Recommended SCC approach**.

<img width="160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc5d82a12c130996c2ba4f4455a33392d131d1b3/image.png" alt="image.png" />

- Force Character issues from the current exercise to be visible onscreen in the default view; at the moment they are not being displayed

- Reword ‘View all issues’ to **_View all character issues from previous applications_**

<img width="394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ef1208c8242ed76af09a277ad475231a4950654/image.png" alt="image.png" />

· Fix recommendation dropdown so that selected option remains onscreen when chosen, it currently remains blank when the an option is selected.

<img width="160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc5d82a12c130996c2ba4f4455a33392d131d1b3/image.png" alt="image.png" />

- Fix offence category dropdown so that selected option remains onscreen when chosen,  it currently remains blank when the an option is selected.

<img width="315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--453f9a8b80c02faa2fa128e5e8eb2c3617e4c534/image.png" alt="image.png" />

- Fix search functionality of search box and add guidance on what can be searched as per other search functionality on Admin

<img width="466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f332e34aed9362ec25a73f9cb0860ae8eabb65e2/image.png" alt="image.png" />

- Where no declaration provided on previous exercises due to the candidate not having been selected and the data not requested, the platform should add **Data not requested** next to each exercise that the candidate has applied for where there is no entry 

<img width="297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTV6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8cbf17a740535cc55b2d67775433af4688a72c8/image.png" alt="image.png" />

- Send the download to the desktop, not a mysterious location on Google drive!

**Ticket Champion**
Digital team

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2230?planning-poker) with Zenhub @drieJAC @warrensearle @tomlovesgithub
