### ISSUE TITLE
Improve Eligibility Report functionality

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2231]
**Background**
At the digital meeting on 28/11/2023, eligibility issues improvements were discussed and a number of bugs on the current platform. The objective of this ticket is to provide comprehensive candidate data on the `Eligibility issues` report page, allowing the SET to make recommendations and then download a document in the format required for the annex to the SCC report (covered in [ticket #2300](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2300))

**Feature(s) Description** 

- Currently the relevant candidate data is not feeding through to the report page; this should be addressed by presenting the information as shown below with `Met `/ `Not met` returned for each criterion (not met would require further manual consideration by the SET)

> For Legal Exercises: 
<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef42c6f26b56795b48829c8a99733fd6d5d67039/image.png" alt="image.png" />

> - **Professional Qualification:** `Met `= the candidate meets the qualification criteria specified in the exercise set-up
> - **PQE:** `Met `= the candidate meets the qualification criteria specified in the exercise set-up (generally 5 or 7 years) 
> - The platform needs to take into account the following when calculating the PQE:
> - It's easiest to work back from current role; if that is equal to the PQE requirement, no need to go back any further assuming it is a full-time role
> - The PQE role must include at least one of law-related tasks a-h to be included in the calculation
> - If PQE role includes only law-related task i, it should not be included in calculations and if the PQE requirement is not met elsewhere, this should flag the PQE as `Not Met`
> - The total amount of PQE should be calculated and displayed after `Met `/ `Not Met` in the format years and months (as a fraction), e.g. 3 years 4.5 months
> - **Previous Judicial Experience:** `Met `= the number of sitting days acquired by the candidate (PQE where option a (the carrying-out of judicial functions of any court or tribunal) is greater than or equal to what is requested AND the experience is Judicial not Quasi-judicial (Quasi-judicial would trigger a `Not Met` return)
> - **Reasonable length of service:** Met = the difference between the candidate age on the date of SCC meeting and 75 is greater than or equal to the RLoS specified in the exercise set-up
> - If candidate has answered No to the RLoS question, the content of the box below should be included:
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fe22cdcce5b7b25354571501da80066dd4a270a/image.png" alt="image.png" />

> For Non-legal Exercises: 
<img width="635" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0VkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--003c1018f8bd21ccbb04fdb03b781540cffc24ab/image.png" alt="image.png" />

> - **Professional Registration:** displays any memberships, e.g. GMC, RICS
> - **Reasonable length of service:**  Met = the difference between the candidate age on the date of SCC meeting and 75 is greater than or equal to the RLoS specified in the exercise set-up

- Fix Recommendation dropdown so that selection is retained on release 
- Remove 'Reject Non-declaration' from the options - this does not apply to Eligibility
- Add checkbox at the top with the text 'Display only candidates with Eligibility issues' - this toggles between all candidates being displayed and just the ones that don't meet some or all of the criteria
- Add a `Download SCC Annex report` link at top of page
<img width="208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--751ffb0aedc667e08e558ac0da0e0d9bdf5e63f6/image.png" alt="image.png" />

**Ticket Champion**
Nick

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2231?planning-poker) with Zenhub @KoWeiJAC

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2231?planning-poker) with Zenhub @KoWeiJAC

**Comment by warrensearle** [comment]
Hey @nickaddy we think this should be split into two tickets. One for the admin UI changes; the other for the downloadable word document/report content. Could you help with this?

**Comment by nickaddy** [comment]
@drieJAC @HalcyonJAC @tomlovesgithub @warrensearle I have now split this out into two tickets; can you pls reestimate the effort on this one?
