### ISSUE TITLE
Diversity dashboard 

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#224]
- As an admin I need to be able to see diversity data for the close of an exercise and at every stage of shortlisting. This is a statutory requirement. 

- This needs to have the categories suggested below by the statistics team and shown in the mock up which Claire has made on Balsamiq (below). 

- The information needs to be accessed on the list of options on the left at this link https://admin.judicialappointments.digital/exercises/AaWKfpkKdSWOQryCgn1T/. This should have Overview with exercise options under. It then has Applications in the same style as Overview. And then it should have 'Exercise Reports'. This will fall under Exercise Reports as 'Diversity'. Eventually there will be further reports. 

- There will need to be the option to link back to Exercise Reports from Diversity and to Overview from Exercise Reports. 
__________________________________________________________________

**An example of what is required below provided by statistics:** 

![image](https://user-images.githubusercontent.com/56963348/73072609-51bfa580-3ead-11ea-9aac-aa48ed15ca35.png)

**The aim is for this to be provided in a dashboard - see Claire diagram below:** 

https://balsamiq.cloud/s156m8n/pe2ips8/r2278

____________________________________________________________________

**For discussion.**  We need to identify what is doable before close of applications on 4 February. 

1. Best case scenario is a dashboard like the balsamiq that admin can easily copy from and distribute. 
2. If a dashboard is not possible a CSV download which shows admin the answers from each candidate and calculates the numbers and percentages. 
3. If the numbers and percentages are not possible at minimum admin needs all the answers in a CSV and may need assistance with formulas to calculate numbers and percentages.

**Comment by warrensearle** [comment]
Can this task be marked as done yet?
Any remaining work can be covered by other tickets

**Comment by londonprojects** [comment]
@ClaireTroughtonJAC
