### ISSUE TITLE
Amend Handover report

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2255]
**Background**
This ticket is to fine tune the existing report for Handover, create a separate handover report, keeping the all the recommended candidates' HR details, (information that Judicial Office require to include on their judiciary HR system).
Currently the Handover report combines HR and deployment details. JO's preference is for the information to be separated into two reports.

**User Story** 
As a Judicial Office admin, I would like to receive a handover report containing the recommended candidates' HR details, so that the relevant info can be sent to the relevant department.

**Feature(s) Description** 
- Remove the location and jurisdiction details from the current _Handover_ report
- Create new link under Handover in LHS reports menu

## Acceptance Criteria
 - [ ] **Scenario: Handover report with HR details only**
  - Given the Handover report contains HR details of recommended candidates, when the report is sent to the Judicial Office, then the Judicial Office receives a report with HR details only
   
**Ticket Champion**
Judicial Office

Deployment report (dealt with in [this ticket](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2260))

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2255?planning-poker) with Zenhub @warrensearle @tomlovesgithub @drieJAC @HalcyonJAC

**Comment by HalcyonJAC** [comment]
The location and jurisdiction details have been removed from the Handover report
