### ISSUE TITLE
Virus Scanner Check

### ISSUE THREAD

**Issue by Franceswog** [jac-uk/admin#2257]
## Background
The virus scanner has been checked and is running well. It is running in what we might call a 'light touch' mode: in that files can be downloaded unless the scanner has marked them as having a virus. We should consider moving to a stricter configuration where files can only be downloaded if they have been marked as not having a virus. Perhaps also we enforce a re-scan policy where a file is re-scanned for viruses if someone is trying to download and it hasn't been scanned for X amount of time.

The problem right now is if our virus scanner stops working, for some reason, all files are still downloadable. If we take a stronger approach then if the scanner stops working our files will stop being available to download. So this helps ensure we keep the scanner up and running.

## User Story
As the digital team, I want files to be downloaded only if they are verified as virus-free, ensuring the security of the system.
As the digital team, I want a re-scan policy implemented for files not scanned within a defined time frame to ensure ongoing security. 
As the digital team, I want the system to enforce strict download restrictions to ensure that if the virus scanner stops working, files become unavailable for download.

## Feature(s) Description

- [x] Implement strict file download verification: files must be downloadable only if marked as virus-free 
- [x] Document the updated configurations and policies for future reference
- [x] Prepare and put in place user guidelines explaining the file download process and re-scan policy

## Acceptance Criteria
- [x] Files must not be downloadable if they have been marked as containing a virus by the scanner.
- [x] Files should be available for download only if they are marked as virus-free by the scanner.
- [x] Implement a configuration where files are only downloadable if marked as virus-free by the scanner.
- [ ] **If the virus scanner ceases to function, prevent all file downloads as a fail-safe measure.**  
- [x] **If a file hasn't been scanned for viruses within the specified time frame (X amount of time), trigger a re-scan before allowing download.**
- [x] **Define the time interval (X amount of time) for triggering re-scans.**

## Definition of Done
- [x] Files downloadable only if virus-free - logic implemented to allow downloads only for virus-free files.
- [x] **Re-Scan policy enabled - policy set up to trigger re-scans for files not scanned within a defined time.**
- [ ] **Fail-Safe for Virus Scanner - files become unavailable if scanner fails.**
- [x] Documentation and guidelines - updated configurations and user guidelines documented

## Ticket Champion
Frances

## Happy Story
The system's integrity will be strengthened, reducing the risk of potential malware threats.

## Sad story
Malicious files can accidentally be downloaded if strict policies are not in place

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2257?planning-poker) with Zenhub @warrensearle @tomlovesgithub @drieJAC @HalcyonJAC

**Comment by tomlovesgithub** [comment]
Currently: 
- Files are scanned upon upload -> marked as either 'clean' or 'infected'
- Every hour a scheduled action scans all files which have not been scanned
- Files are only downloadable if a file is marked as 'clean'. 'infected'' or unscanned files are not downloadable

Changes in new PR: 
- Every hour a scheduled action scans all files which have not been scanned OR **have not been scanned in 6 months**
- Groundwork for checking scanner status
 
Proposed future changes:
- Every hour a scheduled action scans all files which have not been scanned
- Check scanner is online using a https request, use result to mark a flag in the database, use this flag in storage rules to enable or disable downloads. Schedule the running of this script.
  -  Alternatively check if a EICAR file can be scheduled to test full functionality of the scanner, as well as online status.
 - There is another concern with the current system which cannot currently be discussed in github/zenhub, but needs to be addressed.
________

User Guidance
All files uploaded to the database are scanned for viruses. Should the scanner find a malicious file, it will be quarantined by our system and will not be able to be downloaded. When this is the case, users will see the message 'file not available', this message can also be shown under other circumstances.

If your team or a candidate have encountered an unavailable download such as above, please alert the digital team and we will investigate. If you are concerned about potentially malicious files, do not download or share them, please alert the digital team.

**Comment by nickaddy** [comment]
@tomlovesgithub I noticed that the estimate had gone from 8 to 13. Was 13 your amended estimate on completion?

**Comment by nickaddy** [comment]
@tomlovesgithub I'm closing this ticket in anticipation of a new ticket covering the next steps we discussed today.
