### ISSUE TITLE
Panel Packs (sift) 

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#226]
- As an admin I need to be able to download the candidate applications including any attachments such as statements of suitability and self-assessments in one document in an easily accessible format for panel members. 

- This needs to be something I can easily load to Google Drive or email to panellists and print. 

- This needs to have name blind capability. By this the admin needs to be able to remove the names and replace with a reference number to ensure panellists do not know who each candidate is. 

- I need to be able to find this at the applications tab. https://admin.judicialappointments.digital/exercises/AaWKfpkKdSWOQryCgn1T/applications

**For discussion - do we need to have a conversation with staff about this. And how well formatted can it be in time for applications close on 4 Feb**

**Comment by KateMJAC** [comment]
superseded by #410 and is currently being progressed.
