### ISSUE TITLE
Update reports which include stage & status - e.g. diversity report

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2275]
**Background**
As part of #1666 we need to ensure reports, for example the diversity report, are updated to use the new stages and statuses. Likewise there may be stage and status selector dropdowns which need updating with the latest stages. Many have been fixed and will update automatically but we should check for any stragglers. 

**Features(s)**

1. Identify all places in our code base that use hard-coded stages and statuses so we have a 'hit list' of places to fix and then test, reports, report tabs, filter dropdowns, etc.
2. Make the necessary updates

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2275?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by nickaddy** [comment]
@HalcyonJAC (FYI @warrensearle) The final ticket containing details of new S&S is not quite ready yet, but that should not stop you doing the locate part of this ticket to produce a list of hard-coded Ss&Ss on the platform. Is it possible to replace hard-coded locations with dynamic links or is that another piece of work entirely?

**Comment by warrensearle** [comment]
@nickaddy yes this ticket can be completed anytime - it is not blocked by anything - and yes part of this ticket will be to finish centralising the stages & statuses. Most instances have been done but there are a few pesky ones to track down and sort :smile:
