### ISSUE TITLE
Embed new version of application form for future exercises

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2280]
**Background**
The amendments to the application form - mainly the PQE section - need to be embedded on future exercises so that the new version (3?) is automatically used going forward. There are currently no Legal exercises open for application. The next Legal exercise to open for applications is 188 on 23 January; it closes on 13 February. The one after that is 168, which is set to open for applications on 27 February. We can either move forward, excluding Ex.188 or wait until it closes and use the 2 week window before the next one opens.

**User Story** 
As the Digital team, I would like to see the new version of the application form being used in future exercises so that the candidate experiences a more seamless application experience and the platform receives all the data required.

**Feature(s) Description** 

- Perform a final check that anything likely to be impacted by the changes has been updated, e.g. panel packs, reports, downloads etc.
- Set up all future legal exercises to use the new version of the application form 
- Set up all exercises created but not yet launched to use the new version of the application form

**User Testing Steps**
Internal testing only

**Ticket Champion**
Nick

**Happy Story**
The new application is automatically used in all current draft and future exercises and integrates seamlessly with related functionality on the platform.

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2280?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2280?planning-poker) with Zenhub @KoWeiJAC
