### ISSUE TITLE
Add MS Word guidance to Self-assessment Exercise Downloads

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2283]
**Background**
In order to minimise user-generated issues with the new SA upload extraction process, we would like to share guidance with SETs so they can lock down their Word document before adding to the Downloads section

**Feature(s)**

- Add link to Word guidance on modal that appears when users click on Add to upload their SA template

<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9UQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9870582871626a5e223e6d3ab4412eaccc8ed4e1/image.png" alt="image.png" />

<img width="871" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8deb59cb115edeb50e1ca531c318e4b2440e55c/image.png" alt="image.png" />

- Link to this file to open in a new window/download [How to restrict access to selected sections of Word documents.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4f3d832e2b6834535639c38b7dfaf674bf263e9/How%20to%20restrict%20access%20to%20selected%20sections%20of%20Word%20documents.pdf)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2283?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
The PDF may need to be stored in firebase storage.
