### ISSUE TITLE
Remedy issues with Character checks

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2285]
**Background**
Cindy M raised an issue with sending character checks to a candidate with multiple email addresses. On investigation, Nick found that the search functionality is not working and also there is a minor process issue: when you send reminders to a candidate/candidates and click **_I confirm, please send reminder_**, the modal should disappear, once clicked (possibly there should be a second modal to confirm reminder sent). Likely the same issue applies on the Not Requested tab. Currently, it just stays there until you click Cancel.

<img width="935" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDNaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60427380ffb3d483ca86c27ff77071a277f1bd74/image.png" alt="image.png" />

**Feature(s)**
- Fix search functionality on Character Checks

<img width="631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a67aa281b03aae4252f8080115f8ef1eaff731b2/image.png" alt="image.png" />

- When you click **_I confirm, please send reminder_**, make it clear that request has been actioned and close modal

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2285?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
@nickaddy is there any fix needed with regards the original issue from Cindy?
> Cindy M raised an issue with sending character checks to a candidate with multiple email addresses.

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2285?planning-poker) with Zenhub @KoWeiJAC
