### ISSUE TITLE
Character Annex Report

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2293]
**Background**
Following work in January, the Character functionality on the platform is now operating as it should, but is pending the addition of a download containing content that a user can simply paste directly into the SCC report character annex.

**User Story** 
As an Admin user, I would like to be able to export the relevant character content from the candidates so that it can be readily pasted in to the SCC report character annex.

**Feature(s) Description** 
- The report has a 3-level sort:

1. First sort is according to the **_Offence Category_**, set by the Admin user under the Character Issues Report, in this order: Historic Motoring offences, Single Motoring offence, Multiple Motoring offences, Single Criminal offence, Multiple Criminal offences,  Single Financial issue, Multiple Financial issues, Single Professional conduct issue, Multiple Professional conduct issues, Single Other matter, Multiple Other matters, Mixed 
2. Second sort (within each section above) is in this order: **_Proceed, Reject, Reject non-declaration, Discuss_**
3. Third sort is by **_candidate surname_**

- The offence category sections are highlighted as in image below
- Each entry id numbered chronologically on the left hand side of the page
- The relevant content is pulled from the platform as per image below
- The additional fields (Nature and date of issue, Declaration, Guidance Reference) are created as blank fields in the document (these will be manually populated later by the user)
- The download format is a Word document

- One additional requirement outside the report: **_Historic Motoring_** needs to be added to the Offence Category dropdown

<img width="1202" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebc6142b36fc1dd0c7600e750ff77f1bd23f6975/image.png" alt="image.png" />

**Acceptance Criteria** 
* It's done when the user can download a report that is correctly formatted, comprehensive, and can be pasted directly into the SCC report character annex.

**User Testing Steps**
Add instructions here

**Ticket Champion**
Arti Sherry

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2293?planning-poker) with Zenhub @KoWeiJAC

**Comment by warrensearle** [comment]
@nickaddy we think it's worth exploring which mechanism is best for providing users with the content they can paste into their report. Suggest a separate spike ticket to explore options like:
 - On screen copy & paste
 - Downloadable excel
 - Downloadable word
 - Export to google drive (as word document)

**Comment by nickaddy** [comment]
@drieJAC @HalcyonJAC @tomlovesgithub @warrensearle I'm happy with a downloadable word document, let's go with that. Can we reach an agreement on the estimate pls?

**Comment by nickaddy** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2293?planning-poker) with Zenhub @drieJAC

**Comment by drieJAC** [comment]
Note: Exercise Reports Commissioner Conflicts currently uses a package in the frontend on Admin
