### ISSUE TITLE
Admin: Download and print Independent Assessments

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#230]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to download independent assessments on the platform and print them in PDF or word.

**Describe the solution you'd like**
Independent Assessment page: button to download assessment for each candidate.

**Comment by warrensearle** [comment]
This is blocked by apply#135

**Comment by Rebecca-mcknight1991** [comment]
Add screen grab of where this goes. @enoranidi @ClaireTroughtonJAC @Rebecca-mcknight1991
