### ISSUE TITLE
Prepare Panellists' App

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2303]
**Background**
Currently, the process for importing candidate scores onto the platform is extremely laborious and time-consuming: the panels provide marking sheets and the SETs add the scores manually to the platform. This activity has to be manually QA'd to ensure there is no user error. An app for panellists will circumvent this process, allowing the panel chair to input the candidate scores directly to the platform. The panellists' app prototype is already built for the most part and needs to be prepared for internal and external testing before deploying on a live exercise.

**Feature(s) Description** 

- [ ] Update app to align with platform
- [ ] Create data for testing purposes
- [ ] Test app internally
- [ ] Demo app to SETs/Have SETs test app

**Acceptance Criteria (optional/delete if not used)** 
It's done when the panellists' app has passed all internal and external tests and is ready for deployment on a live exercise.

**User Testing Steps**
Add instructions here

**Ticket Champion**
Warren

**Comment by nickaddy** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2303?planning-poker) with Zenhub @warrensearle

**Comment by tomlovesgithub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2303?planning-poker) with Zenhub @drieJAC @HalcyonJAC

**Comment by tomlovesgithub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2303?planning-poker) with Zenhub @KoWeiJAC
