### ISSUE TITLE
Firestore permissions error following upgrade to latest firebase sdk

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2306]
This was originally raised on PR https://github.com/jac-uk/admin/pull/2287 but has been moved here so that the code in that PR can be merged into `main` (as there are lots of changes which we don't want to go stale).

**Before** (fresh install of Admin running from previous `main` branch)
All looks fine, no console errors
<img width="1098" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/0f3e87fe-af84-4547-9338-c3725bd2d67b">

**After** (fresh install of Admin running the upgraded firebase lib)
Console error
<img width="1097" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/8ca473d9-f5af-471a-9273-ba1cf73fe607">

The back-end this is connecting to is unchanged however the error looks like a firestore permission error. Perhaps the new code is trying to access more from firestore than the previous code.

**Comment by drieJAC** [comment]
Another warning that I noticed is here:

<img width="1728" alt="Screenshot 2024-02-12 at 14 21 27" src="https://github.com/jac-uk/admin/assets/115651787/0dcba046-e148-4f5a-bb58-2871a8eb59d5">

**Comment by drieJAC** [comment]
And also the link doesnt seem to be working, see the video below:

https://github.com/jac-uk/admin/assets/115651787/6990745a-4ce2-4a51-93a0-40f8441bf0f0
