### ISSUE TITLE
Address candidate naming inconsistencies

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2326]
## Background
Sam M-E and Jasprit K highlighted inconsistencies in how candidate names were displayed on the platform. A fix was implemented for Exercise JAC00117, but the issue has not been permanently resolved. [This application](https://admin.judicialappointments.digital/exercise/HdvJaVf4QIpGTDJDmeYz/applications/applied/application/XzNIQpSuLtoy2CIx0orV) is a good example on Exercise JAC00172. The candidate's name should appear consistently as Charlotte R****, however, under `Stages` and in the `Selection Day report`, the candidate appears as Charlotte N**, their `Other name`.

## User Story
As an Admin user, I would like all candidates names to be displayed consistently across the platform using the `First name` and `Last name` fields so that I do not have to spend substantial time QAing to identify these anomalies. 

## Feature(s) Description

- [x] The `Stages` tab consistently uses the candidate `First name` and `Last name` fields in the display names

<img width="974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d17c39c14f9120d928fe45c1f2bc2db634a23b59/image.png" alt="image.png" />

- [x] The `Selection Day report` consistently uses the candidate `First name` and `Last name` fields in the name column

<img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWlFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b161fc478667790be565ee8e8b4e6459be19ec0c/image.png" alt="image.png" />

- [ ] Any other locations where the candidate `Other name` is used are remedied

## Acceptance Criteria (optional/delete if not used)
It's done when the candidate `First name` and `Last name` fields are consistently displayed across the platform.

## User Testing Steps
TBC

## Feature Champion
Sam Marzan-Esher

**Comment by nickaddy** [comment]
@warrensearle Should the names always come from the candidate or application record - haven't we created another issue for ourselves by having multiple places to update some of the data?

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2326?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2326?planning-poker) with Zenhub @KoWeiJAC

**Comment by KoWeiJAC** [comment]
> @warrensearle Should the names always come from the candidate or application record - haven't we created another issue for ourselves by having multiple places to update some of the data?

@nickaddy 
Currently, in the database, only applications have first name and last name, but the places needs to be change are using application records which have full name field only. 
I'm thinking we can have a version that parse first name, last name from full name of application records, and also add a logic that using first name and last name of application records if these 2 fields exist.
So, in the future, when the first name, last name fields being added to application records, system can display those 2 fields without further change.

**Comment by KoWeiJAC** [comment]
@nickaddy 
- There are other places using full name that not included in the `feature(s) description section`, would we need to change those places to be first name, last name ? such as agency reports, application list
<img width="1558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ee5d558f601a3afdd2235fa54b6878859210166/Screenshot%202024-03-07%20at%2016.01.53.png" alt="Screenshot 2024-03-07 at 16.01.53.png" />

<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef8a54c05f42918684373927697b9ef5a8c7331c/Screenshot%202024-03-07%20at%2016.02.55.png" alt="Screenshot 2024-03-07 at 16.02.55.png" />

- There are some places use `Other names` as additional information of `Full name`, would we need to change all `Full name` in these places to First name, Last name ? such as application summary
<img width="1110" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3JBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee82d964a1c774ff7224cece4ee18f21b2e5912a/Screenshot%202024-03-07%20at%2015.59.44.png" alt="Screenshot 2024-03-07 at 15.59.44.png" />

-

**Comment by nickaddy** [comment]
@KoWeiJAC It was only the cases identified in the ticket features where there appeared to be an issue with the consistent name not being used.

**Comment by nickaddy** [comment]
@HalcyonJAC I only heard back from Sam today, this was his comment: I tested by changing the forename field but that only updated once I changed the surname field. Would the same code need to be applied to both fields i.e surname and forename? 

Does that make sense and can you let me know the answer to the question when you have a moment pls?

**Comment by nickaddy** [comment]
@HalcyonJAC Has Sam been looped in to this regarding the issue we raised last week?
