### ISSUE TITLE
Amend authorisations under Eligibility

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2331]
## Background
In conversations with Leadership and Senior Appointments teams, it became apparent that the current authorisations listed under Eligibility are incorrect. Minor changes on Admin are detailed below.

<img width="317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5daf40cb5f5b407338ec885e4aba64cd7cae8316/image.png" alt="image.png" />

## User Story
As the Leadership and Senior Appointments teams, I would like the correct authorisation options to be displayed on Admin so that any authorisations required are clearly displayed under `Eligibility information`.

## Feature(s) Description

- [x] ADMIN: Under `Eligibility information` amend _**s9(4)**_ to _**Class 1 ticket**_
- [x] ADMIN: Remove _None_ box - it doesn't make sense that you could have a situation where, e.g. both s9(1) and None could be ticked; if neither of the other boxes are ticked, by implication that means None.

## Acceptance Criteria (optional/delete if not used)
It's done when the correct authorisations detailed above are embedded on Admin.

## User Testing Steps
TBC

## Feature Champion
Thomas Wolfe

**Comment by KoWeiJAC** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2331?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by tomlovesgithub** [comment]
`authorisations` are collected but not currently utilised within the platform. 
Perhaps we should consider removing them or expanding this ticket to include some use for them.

**Comment by warrensearle** [comment]
Hey @nickaddy the question asked in Apply comes from the ASC custom question that SETs enter in admin. This gives full control over the title asked - e.g. Do you currently have a s.9(4) authorisation?
So I'm not sure there's much here for the devs to work on, unless we want to start using the authorisations.

**Comment by nickaddy** [comment]
@warrensearle Will look into this further. It seems a bit obtuse that we are providing SETs with the option to choose authorisations that apply but then that is not reflected in the application form unless they create a separate question under ASC.

**Comment by nickaddy** [comment]
@warrensearle @tomlovesgithub @drieJAC @HalcyonJAC @KoWeiJAC Ticket has been amended, it now simply involves two minor cosmetic changes on Admin. Please reestimate.
