### ISSUE TITLE
Character Report functionality v2

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2352]
## Background
Character reporting has been recently iterated in February and March, however, in conversations with SETs and Secretariat, it is clear that we need to go further to provide a workable solution that fully delivers on the promise of an SCC-ready Annex B1.  

**There is a little info outstanding below, but it would be helpful if you could produce an approximate estimate as we will be working on this item in the next sprint.**

## User Story
As an Admin user, I would like to be able to input all the data necessary on the platform so that it can be presented to the Secretariat for review prior to export directly for the SCC report.

## Feature(s) Description

- [x] Make the character information displayed to the users (application record on Admin) editable and formattable. The candidate's original application data should be retained on the application record.
- [x] The character information presented to the user on screen should be played back in the following format (Motoring example given, but same applies to all offence types - see full Miro [here](https://miro.com/app/board/uXjVKb0Ep0o=/?moveToWidget=3458764584228542233&cot=14))
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--585b2c62bac99fef07281413cf23235fd266bee5/image.png" alt="image.png" />

- [x] The character information should be played back on screen in the following order: Motoring Offences, Fixed Penalty Notices & Penalty charge notices, Criminal Offences, Financial issues, Professional Conduct, Other matters.
- [x] Add an edit button that allows the onscreen content to be edited and reformatted and a Done button that allows the edited content to be saved.
<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d305f05c173774be3e537c76a1739c74b9b6722/image.png" alt="image.png" />

- [x] Add the following options to the `Offence Category` dropdown: `Single Fixed Penalty Notices & Penalty Charge Notices`, 'Multiple Fixed Penalty Notices & Penalty Charge Notices'

- [x] Rename the following options to the `Offence Category` dropdown:
- Single financial offence > Single financial issue
- Multiple financial offences > Multiple financial issues
- Single professional conduct > Single professional conduct matter
- Multiple professional conduct > Multiple professional conduct matters

- [x] Reorder the items in the `Offence Category` dropdown as shown in the image below

<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e2de4b5ca54a3e42d7903ffb13caaf4ae88d562/image.png" alt="image.png" />

- [x] Create a new `Guidance reference` tickbox (multiple selection permitted) section **after** `Offence category` and populate with these options:
- Criminal offences: paras 21-24
- Motoring offences: paras 25-30
- Fixed penalty notices: paras 31-34
- Financial insolvency and debt: paras 35-38
- Financial VAT and Tax: paras 39-43
- Professional conduct: paras 44-57
- Further disclosures: paras 58-65

- [x] Create a new field `SCC decision` dropdown containing options Proceed, Reject, Defer - this follows the `Recommended SCC Approach` field

## Acceptance Criteria (optional/delete if not used)
It's done when users can download an SCC-ready Annex B1 from the platform.

## User Testing Steps
TBC

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2352?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by nickaddy** [comment]
@drieJAC @warrensearle @HalcyonJAC @tomlovesgithub  Suggest you might want to re-estimate this one now that I have filled out the additional info

**Comment by HalcyonJAC** [comment]
@nickaddy We've displayed the Character information on the application view page which is editable. Should I just format it?

**Comment by nickaddy** [comment]
@HalcyonJAC It's important that we retain the original candidate's data on the application view page. Here we are giving the SET to opportunity to edit that info for presentation in the SCC annex, e.g. where candidate has written a lot of information that can be cut down to sthg shorter.
