### ISSUE TITLE
Improvements to the Diversity Report

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2356]
## Background
Following on from the work on a new version of Stages & Statuses, the Diversity report needs iteration to: 1) minimise additional analytical work by correctly capturing the statistics, and 2) expanding the shortlisting tab to include separate breakdowns for sub-tasks where there are multiple shortlisting steps (usually on larger exercises.) 

NOTE: there is an additional request  to automate the calculation of the difference in % points between stages and enable the information to be downloaded in Excel format so that it is compatible with SCC papers and AA reports. It may make sense to get the report fixed first and then conduct that work under a separate ticket, open to suggestions.

## User Story
As a user, I would like additional tabs for sub-tasks in a multiple task shortlisting exercise so that I can see the correct breakdowns for diversity statistics after each task.

## Feature(s) 

- [x] Review and correctly align the new statuses with the appropriate tabs on the Diversity Report
- [x] On exercises where there are multiple shortlisting tasks (i.e. QT, Scenario test and Sift) add additional tabs that capture the statistics for the relevant statuses
- [x] On exercises where there is a single shortlisting task, maintain a single Shortlisted tab
- [x] The gender statistics on the Dashboard need to also be updated in line with the changes to the Diversity Report (see image below) - this could be separated out into an additional ticket

<img width="613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWp5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5e36ac9726aa331bc64accc4f133be627299243/image.png" alt="image.png" />

- [ ] The Outreach report also needs to be updated in line with the changes to the Diversity Report (see image below) - this could be separated out into an additional ticket

<img width="983" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c41106c20437a0577e8e0496d4e0e8f15ac5d4ec/image.png" alt="image.png" />

## Acceptance Criteria (optional/delete if not used)
It's done when the Diversity Report (and other areas identified above) correctly reflect the Diversity statistics and include additional sub-tabs for multiple shortlisting stages.

## User Testing Steps
TBC

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2356?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
@nickaddy I have a question about the second feature. What are the names of the additional tabs?
