### ISSUE TITLE
Grading - Enter grades and flag candidates PAUSED

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2385]
## Background
During the grading stage, panellists want to be able to select applications for moderation, flag or unflag candidates for moderation and enter reasons for moderation.
SETs would like to see the flagged candidates and the reasons for moderation. 

<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9JQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3d8282fb22eca5d07cadccbaba8589f564dfe51/image.png" alt="image.png" />

## User Story
- [ ] As a panellist, I want the sift score page to include a tick box so that I can flag and unflag candidates for moderation.
- [ ] As a panellist, I want a text box so that I can enter reasons for moderation

## Feature(s) Description
- [ ] Flag and un-flag candidates for moderation
- [ ] Display panel reason for requesting moderation

## Acceptance Criteria
- [ ] Panellist flags or unflags a candidate for moderation, then the candidate's status should be updated accordingly
- [ ] Panellist clicks on the "moderation" tick box to select the candidate for moderation

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2385?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle
