### ISSUE TITLE
Create SCC Eligibility download covering 3 annexes for legal exercises

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2396]
## Background
This ticket is connected with [#2387](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2387), in which the `Eligibility report` display has been reconfigured to focus on specific areas of eligibility for legal exercises only, due to the fact that non-legal exercises are problematic thanks to the lack of distinction between statutory and ASC criteria, and reviews that are currently taking place. Hence, we aim to automate production of the following annexes for legal exercises only: Statutory eligibility criteria (Professional qualification and PQE), PJE and RLoS.

## User Story
As an Admin, I would like to be able to download SCC Annex-ready eligibility annexes so that I can expedite production of the SCC paper.

## Benefit(s) to user (if not already clear from User story)
Admins will be able to produce a Word download from the platform that covers some of the eligibility annexes required for the SCC report.

## Feature(s) Description

- [ ] The annexes described below should be produced as a single Word document download which is downloaded to user's desktop when you click the Download SCC Annex report button
- [ ] Each section of the report should be preceded by a page break
- [ ] The first section of the annex 'Candidates who do not meet the Statutory Eligibility Criteria' includes candidates who are 'Not met' for Professional qualification and/or Post-qualification experience **sorted alphabetically by candidate surname**
<img width="799" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy9VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c10b58803f5e1e2c9b24fd24c87f54a4664b665/image.png" alt="image.png" />

- [ ] The content for the 'Reasons Statutory Eligibility Criteria is not satisfied' column is drawn from the 'Reasons not satisfied' field for Statutory eligibility criteria
<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--734d52a9ee458bf608e9e3796a597131459f5db6/image.png" alt="image.png" />

- [ ] The content for the next two sections is Candidate Previous Judicial Experience and plays back this section of the Eligibility report

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0hWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--808bc82a97fc6f1451fb4cca8f48807f255fb855/image.png" alt="image.png" />

- [ ] It is split into 3 sections 'Recommended to proceed', 'Recommended to discuss', and 'Recommended to reject' according to the Recommendation selected from the dropdown in that section

<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6435a1b7a8389fe9904426c4611768d8f8d4e2c8/image.png" alt="image.png" />

<img width="791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzNWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb57f3c2b46c4c00b0db9f489a55dafe28022b66/image.png" alt="image.png" />

<img width="785" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeERWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6250775e1e2436190355693da1f77cb825164de/image.png" alt="image.png" />

- [ ] The final section relates to Reasonable Length of Service and includes all candidates with a Not Met flag under RLoS **ordered alphabetically by their surname**

- [ ] It is formatted as below

<img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ee9fb56ca0593dee00ae2444950871a30ce0533/image.png" alt="image.png" />

- [ ] Column C returns candidates' ages at date that SCC is scheduled for (this has already been calculated by the platform to determine whether they meet the RLoS criteria or not)

## Acceptance Criteria 
It's done when for legal exercises only:
- [ ] Users can trigger a download to their desktop based on the criteria described above
- [ ] Each section starts on a fresh page
- [ ] Each section is ordered alphabetically by candidates' surnames
- [ ] Each section is formatted according to the images presented
- [ ] Each section included the content as described
- [ ] The PJE section is split into Proceed, Discuss and Reject sub-sections

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
This feature is designed to automate as much of the production and formatting of the eligibility report as possible for legal exercises. Does the functionality deliver what is required to produce the annexes covering: 1) statutory eligibility criteria, 2) PJE and 3) Reasonable length of service?

## Feature Champion
Nick

**Comment by KoWeiJAC** [comment]
@nickaddy 
I'm not very sure about these 2 places, could you help me to confirm them ? Thanks
1. Is ok that we use number (1, 2, 3 ...) for represent years in this place? Currently, it seems that we don't have functions for convert numbers to words (1 -> one, 2 -> two). And if we use same format for the same field, it may be more consistent. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74f3f1fba38f0e9368663ee03a71488904b57213/Screenshot%202024-05-15%20at%2010.18.13.png" alt="Screenshot 2024-05-15 at 10.18.13.png" />
 
2. Is this field the age of candidate at `Character and selection SCC` date? I've found a logic in our existing code, but not sure if it is the right one.
<img width="1614" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlBnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b457991039e8b037ed33c24f6a8d11cea4656940/Screenshot%202024-05-15%20at%2010.26.34.png" alt="Screenshot 2024-05-15 at 10.26.34.png" />

<img width="1035" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlRnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0853a1f43f38e431881c0d382e9918d1388dfcda/Screenshot%202024-05-15%20at%2010.12.10.png" alt="Screenshot 2024-05-15 at 10.12.10.png" />

**Comment by nickaddy** [comment]
Thx @HalcyonJAC - this appears to work well. Can you pls set up say 5 exercises that can be used independently at UT tomorrow (this has not been UT'd yet?) Unless we can use those exercises that you set up previously for the character annex download?

**Comment by nickaddy** [comment]
@HalcyonJAC This failed UT yesterday with the following responses from users: 'Couldn't download - network issue.' See screenshot. It worked fine for me, but multiple users experienced the issue. Can you pls test with @Franceswog who also experienced the issue above?
<img width="353" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dafad889c5e79087d3512957b9d163cf070584f/image.png" alt="image.png" />
