### ISSUE TITLE
Link panellist data to panel set-up

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2401]
## Background
Panellist data is now stored and editable on the Digital Platform, however, it is not currently linked to panel set-up.

## User Story
As as Admin, I would like to be able to add panellists from the database to the panel(s) I have set up on my exercise.

## Feature(s) Description

- [ ] Link the panellists stored in the database with `Sift` under `Reports`, e.g. [this exercise](https://admin.judicialappointments.digital/exercise/IiaXjmpDQd7BQx7ovlv0/reports/sift/view/DBUfwThCQWKTAFP8DwEH#members)
- [ ] Replace the current Add a member button/modal with a dropdown menu (populated from the panellist database and sorted alphabetically desc by name) with an **`Add a member`** button next to it
- [ ] When clicked, the button adds onscreen the selected panel member
- [ ] Next to the panel member name, there are Edit and Delete buttons - Edit allows the user to choose a different name from the dropdown menu
- [ ] There is an Add another member button that allows additional panellists to be added

<img width="1181" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d35ca5a5c737efc37775c9d84c8f30faddf7908c/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when Admins can:
- select panellists from a dropdown menu on the Panel > Panellists tab
- add selected panellists to a panel
- edit or delete panellists added to a panel
- add/edit/delete multiple panellists from a panel

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Panellist data is now stored and editable on the Digital Platform, however, it is not currently linked to panel set-up. This item allows Admins to add panellists from the database to a panel they have set up in an exercise. They can also edit and delete those panellists from the panel.

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2401?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Have kept this ticket open as, whilst the work was done a long time ago, it hasn't been tested or released yet. So this ticket is useful to keep track of testing & deployment.
