### ISSUE TITLE
Generate basic programme Gantt chart view

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2406]
## Background
Matt and Programme Office (PO) would like to have a 'live' programme view across all exercises on the Digital Platform.

## User Story
As PO, I would like to have a 'live' Gantt chart view across the entire programme so that I can easily view resource bottlenecks, QT clashes and other useful information quickly and easily.

## Benefit(s) to user (if not already clear from User story)
- Allows easy viewing of all/multiple exercise timelines
- Allows programme view filtered by, e.g. exercise type, team, for resource considerations etc
- Allows easy viewing of, e.g. QT clashes
- Provides up to date view according to 'live' dates in Admin
- Potentially replaces Programme Live spreadsheet

## Feature(s) Description
[Miro discussion board](https://miro.com/app/board/uXjVKE47RsE=)

- [x] Create a Gantt chart view of the exercise programme 
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0tOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7790cb3f70770e0989da4eb69c9e143e070e56e0/image.png" alt="image.png" />
- [x] The top row of the chart must be always visible onscreen, i.e. when you scroll down the page it remains in place, however it is possible to scroll left and right
- [x] The top row displays a 6-month period starting from one month in the past and continuing to 5 months in the future (default view)
- [x] It is possible to scroll to the left (the past) as far back as the opening date of the oldest live exercise
- [x] It is possible to scroll to the right (the future) as far forward as the final outcome to candidates date of the latest live exercise
- [x] Below the timeline row, each live exercise has its own row with the first column being the exercise reference number 
- [x] The reference number column should also be locked on screen, i.e. you can scroll left or right, but the reference column remains in place
- [x] On hover over the exercise reference, the name of the exercise appears
- [x] On each row, a sequential list of activities appears, each in a separate lozenge
- [x] The length of the lozenge aligns with the start and end dates of the activity
- [x] One-day events, e.g. Eligibility SCC, are shown as a line
- [x] On hover over the line, the name of the activity appears
- [x] The default sort of exercises is by launch date
- [x] Activities use the same terminology as the timeline but we might want to rephrase the titles of some activities if they are too long to fit in the box
- [x] When you hover over the activity, the full title and the start and end dates appear
- [x] The activities to be included on each timeline are shown below, along with their colour-coding
<img width="1079" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm1OQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdd54e704e7b00673cfcb0dc64af464b4348500b/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when the above criteria are met.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Matt, Gemma and Adela only
Interact with the Gannt chart and share any observations where it falls short of requirements.

## Feature Champion
Matt (Gemma/Adela)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2406?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub

**Comment by drieJAC** [comment]
@nickaddy we will need to liaise with the product team to choose a gantt chart library. It could be that, for the features you want available, we need to pay for one. Building one from scratch will take longer than using a pre-rolled library.
