### ISSUE TITLE
Correcting source of candidate SA data for panel packs

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2408]
## Background
On [a recent exercise](https://admin.judicialappointments.digital/exercise/IiaXjmpDQd7BQx7ovlv0/dashboard), it emerged that the panel packs were pulling the candidate SA data not from the extracted content on Application view, but from the uploaded original SA document, which is only there as a back-up. This needs to be remedied.

## User Story
As an Admin, I would like the SA data appearing in the panel packs to be based on the content extracted from candidate uploads **after they have made edits** and submitted so that I can be sure the final candidate version is shared with panels.

## Feature(s) Description
- [ ] Pull the SA content for the panel packs from the extracted and edited content in Application view NOT from the uploaded Word document

## Acceptance Criteria 
It's done when the panel packs display the final, edited candidate SA data output onto Application view from the extraction process.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Create a panel pack, compare the candidate self-assessment content with what is on Application view and confirm that it is identical.

## Feature Champion
Akua/Abbey

**Comment by tomlovesgithub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2408?planning-poker) with Zenhub @drieJAC @HalcyonJAC @warrensearle
