### ISSUE TITLE
Eligibility report

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#241]
It is a requirement for every exercise that candidates meet what is called eligibility. This could just comprise of a citizenship requirement but is often more complex and involves a certain number of years as a barrister/solicitor post-qualification. 

You can read more about the specific requirements here: https://www.judicialappointments.gov.uk/eligibility

The admin needs to be able to quickly see which candidates may have eligibility problems. The suggested mechanism for this is a flag which appears by the candidate which indicates to the admin that there may be an issue. This flag would also have a short explanation as to why the candidate may not be eligible. 

They will then check each of these candidates to assess whether they are eligible or not. They will need to be able to download the information relating to eligibility to share with Commissioners and internal Senior staff. 

The conclusions made after this assessment of eligibility are put into a paper which goes to the Selection and Character Committee and the Commissions ultimately decide whether the candidates are eligible. Candidates who are not eligible will not be able to proceed in the process. 

This epic compromises of:
1) Flags to indicate where a candidate may not be eligible digital-platform#247
2) The ability to view on screen and print in a friendly format (general feature) #286
3) The ability to mark candidates as 'ineligible' as discuss in #316

The will enable the team to make the appropriate recommendation to the Commission and the Commission to then decide whether candidates are eligible. The teams can then update the platform accordingly.

**Comment by Rebecca-mcknight1991** [comment]
Linked to epic #316
