### ISSUE TITLE
Update status in Stages when a candidate is withdrawn

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2410]
## Background
When working with Roshni on JAC00184, Nick noticed that candidates that have been withdrawn by SETs are correctly moved to the `Withdrew` tab under `Applications`, but do not appear to have a status, i.e. there is no entry in the status column. 

<img width="1085" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1WQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47e8bff2c280094a2b58adf7d30eb302d2d3bac5/image.png" alt="image.png" />

The status column on the Stages tab is also empty:

<img width="612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlVWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0e419e483903526ff1b234c1ef8f657d3fee891/image.png" alt="image.png" />

## Feature(s) Description
- [x] Update the code that is triggered with the `Withdraw Application` button is pressed so that the application status is updated to Withdrew - this status must be displayed in the status column under `Applications` and under `Stages`
- [x] Run a script on JAC00184 that will update the statuses of candidates that have already been withdrawn
- [x] Two candidates withdrew after successfully passing the QT and they appear correctly under Applications > Withdrew, however, in both cases, their status shows as `Critical Analysis Test Passed`, whilst it should show as `Withdrew` - can these statuses be updated and the reason why this is happening resolved?

[Candidate 1](https://admin.judicialappointments.digital/exercise/phf3iabh5KDhRiw4f4xm/applications/withdrawn/application/KtDJZQvGzFSzNkBtBPg1)
[Candidate 2](https://admin.judicialappointments.digital/exercise/phf3iabh5KDhRiw4f4xm/applications/withdrawn/application/WSqJfz976nj12JVV6MTY)

## Acceptance Criteria 
It's done when withdrawn candidates status is displayed in the status columns on the pages stated and the two anomalous candidate status issues have been resolved.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Internal testing only

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2410?planning-poker) with Zenhub @drieJAC @KoWeiJAC @tomlovesgithub @warrensearle

**Comment by tomlovesgithub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2410?planning-poker) with Zenhub @HalcyonJAC

**Comment by NormaJAC** [comment]
I just tested this, I withdrew the below candidate, however even though it shows as withdrawn, 
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFk2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f4077dda02c9127f76969b6e8a226d66e44189e/image.png" alt="image.png" />

the status doesn't show as withdrawn, am I missing something?
<img width="1737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGc2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5eaad09e3f4bf121547e86a1bd7a16eabfc03402/image.png" alt="image.png" />

**Comment by tomlovesgithub** [comment]
Hi @NormaJAC Please try again

**Comment by NormaJAC** [comment]
@tomlovesgithub It worked. 
<img width="720" alt="image" src="https://github.com/jac-uk/admin/assets/129379537/a5ae8da5-0d44-4174-822c-4a6738257050">
<img width="878" alt="image" src="https://github.com/jac-uk/admin/assets/129379537/be122d2b-0bde-4682-af83-0a0c88656989">
