### ISSUE TITLE
Admin refresh - Changes to Navigation

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2412]
## Background
The Admin interface has grown organically over time and, in response to user feedback, there is a desire to group tasks, reports and other activities on the platform more intuitively to support both experienced and novice users. Additionally, this is an opportunity to refresh the display and make better use of screen space.

## User Story
As an Admin, I would like the tasks, reports and functions to be grouped more intuitively and logically on the platform so that I can quickly find what I am looking for.

## Benefit(s) to user (if not already clear from User story)
Make better use of screen real estate.
Dispense with unused functionality.

## Feature(s) Description
- [x] Reorder figures in Applications box on Dashboard
- [x] Change `Withdrawn` > `Withdrew`
<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWowQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f802ddb9b3db17e79c6322b9ed7a81b26feaa0c6/image.png" alt="image.png" />

- [x] Link to [Applications/Applied page](https://admin.judicialappointments.digital/exercise/K684SxTmTIwsRWnPefqm/applications/applied) from Applied number on Dashboard
- [x] Link to [Applications/Withdrawn page](https://admin.judicialappointments.digital/exercise/K684SxTmTIwsRWnPefqm/applications/withdrawn) from Withdrawn number on Dashboard
- [x] Link to [Applications/Draft page](https://admin.judicialappointments.digital/exercise/K684SxTmTIwsRWnPefqm/applications/draft) from Draft number on Dashboard
- [x] Clarify (as a comment on this ticket) if `Applied` figure includes withdrawn candidates
- [x] Remove `Applications` from top navigation
- [x] Amend `Exercise` to `Exercise Set-up` in top navigation
- [x] Replicate the new onClick menu for Reports as per [2480](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2480)
- [x] Replicate the new onClick menu for Stages as per [2480](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2480)
- [x] Sort the options in the `Reports` menu a-z
- [x] Rename `Character issues` and `Eligibility issues` links to `Character Annex` and `Eligibility Annex` respectively

[Miro board](https://miro.com/app/board/uXjVKE_NKAQ=/)

## Acceptance Criteria 
It's done when the above feature requests have been implemented.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2412?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by drieJAC** [comment]
Presumably we need to ensure this looks ok on smaller screens

**Comment by drieJAC** [comment]
@nickaddy the addition of the Search doesnt really make sense as the Dashboard page doesnt have a table displaying search results.
If we add this table to this page then I think it becomes a bit convoluted.

**Comment by nickaddy** [comment]
> Presumably we need to ensure this looks ok on smaller screens

@drieJAC Certainly, we can test that, but we are not really adding here, more taking away/moving around.

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2412?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by KoWeiJAC** [comment]
> Clarify (as a comment on this ticket) if Applied figure includes withdrawn candidates
I tested it, the applied figure does not includes the withdrawn candidates.

**Comment by nickaddy** [comment]
@KoWeiJAC I'm not seeing these two requests:

- Remove Applications from top navigation
- Amend Exercise to Exercise Set-up in top navigation

Additionally, I realised that I forgot to request on the ticket for the side navigation menus on Tasks, Stages and Reports to be removed.

**Comment by KoWeiJAC** [comment]
@nickaddy 
Sorry, it is because I was merging changes of [2480](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2480), so the Application link and Exercise were change to the original version again.
I've fixed both places.

Sure, I'll change Tasks to onClick menu and remove those sidebars.
