### ISSUE TITLE
Reference statuses in Independent Assessments task

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2419]
## Background
Since the **Review** stage was consolidated into **Shortlisting**, users are unable to select only candidates that have passed the QT in order to request IAs for those candidates only. This relates to the recent changes to Stages & Statuses.

## User Story
As an Admin, I would like to be able to select only candidates that have passed the QT so that I can request Independent Assessments ahead of the sift taking place. Currently, the dropdown is linked to Stages, however, it needs to be linked to Statuses.

## Feature(s) Description
- [x] When initiating the IA task, the dropdown menu must reference candidate statuses, e.g. QT passed, and candidates with the select status should appear in the list on screen when `Start assessments` button is pressed
<img width="919" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d955fdc717cde366561abad5534cebedbf2f9915/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when Admins can select candidates by status and then send IA requests to assessors for those selected candidates.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Tracey

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2419?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub

**Comment by HalcyonJAC** [comment]
@nickaddy Do we need to support the ability to select more than one status?

**Comment by nickaddy** [comment]
@HalcyonJAC I don't think so, but let's take an iterative approach with v1 being just one status at a time. I guess they could do the task multiple times each time using different statuses if they needed to.
