### ISSUE TITLE
Admin refresh - Consolidate screen space on Exercise pages

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2427]
## Background
The Admin interface has grown organically over time and, in response to user feedback, there is a desire to group tasks, reports and other activities on the platform more intuitively to support both experienced and novice users. Additionally, this is an opportunity to refresh the display and make better use of screen space.

## User Story
As an Admin, I would like the tasks, reports and functions to be grouped more intuitively and logically on the platform so that I can quickly find what I am looking for.

## Benefit(s) to user (if not already clear from User story)
Make better use of screen real estate.
Dispense with unused functionality.

## Feature(s) Description
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--719588fe8a1bfa62d2796ce741baac2c2a046f0c/image.png" alt="image.png" />

- [ ] Remove the `This is a new service...` line on Exercises pages
- [ ] Move Exercise reference to right hand end of navigation row
<img width="1435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ceda6cfa3440cc48904a2c06de033374a039bfb/image.png" alt="image.png" />
- [ ] Move `Create exercise` under `Archived exercises` in `Exercises` submenu
- [ ] Move `Copy to clipboard` to `Exercises` submenu and rename to `Copy exercise to clipboard` - it is currently a button - it should come after `Create exercise`
- [ ] Move `Archive exercise` to `Exercises` submenu - it is currently a button - it should come after `Copy exercise to clipboard`
- [ ] Move Add to favourite (and Remove from Favourite and Favourite label when they appear) under exercise title as below:
<img width="912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm96QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3b1c67f4c8f1e96ceaa8bc659602fdbccc6c00c/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when the above feature requests have been implemented.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Internal testing only

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2427?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub

**Comment by drieJAC** [comment]
Note that the changes for this ticket are in: https://github.com/jac-uk/admin/pull/2480
