### ISSUE TITLE
SPIKE: Test improvements to navigation

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2429]
## Background
As part of the Admin refresh, we'd like to experiment with bringing the left hand menus up to the top of the screen so that we can use the full width of the screen to display exercise content. We'd like to achieve a layout like this:
<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU9BQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed445720e545861abaa30fc55da773eb3e7cf431/image.png" alt="image.png" />

## Feature(s) Description
Experiment with the Exercise sub menu with the aim of delivering the above configuration. Ideally, we'd like to: 
1. Have the items in the sub-menu display in a grey box underneath the top navigation
2. Have the selected item in the sub menu appear next to the top level menu item separated by a >
3. Have a blue line delineating which menu items are selected
4. The menu that appears could either float on top of screen content or push the screen content down

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2429?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub

**Comment by drieJAC** [comment]
See the following packages if required:

https://www.npmjs.com/package/vue3-tabs-component
https://cristijora.github.io/vue-tabs/#/

**Comment by drieJAC** [comment]
Tasks will need some logic to decide which items should be visible
