### ISSUE TITLE
Search Filter Sort

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#243]
A number of colleagues will use the candidate search function including complaints, policy and selection teams.   This is an ADMIN (staff) only function.  

We need a quick way to search for candidates across exercises and within individual exercises.  We need to be able to type in a candidate's name or email address.  

This should return an alphabetical list of likely candidates, their phone number, their NI number and date of birth and allow the user to select the most relevant person.  When available it would be useful to see current status of the candidate and the exercise they have applied for.  

We also need to be able to click into the candidate's record and see information about their current and passed applications. 

Tasks here are:

1. Wireframe and prototype the list. - early example needs UI work https://balsamiq.cloud/s156m8n/pe2ips8/r2DB2
2. Wireframe and prototype the candidate record - early example needs UI work
https://balsamiq.cloud/s156m8n/pe2ips8/r876E
3. Allow filters
4. Consider positioning
5. Consider and develop missing content from the candidate applications
6. Allow candidate record to link to exercises but remain independent function

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by warrensearle** [comment]
Closing as all tickets and now complete and closed
