### ISSUE TITLE
Updates to Outreach report

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2450]
From Jan 2025  Roadmap - Provides richer data by reporting on the diversity characteristics of candidates attending Outreach events.

Discussions so far; Rachael finds them useful to understand how many people attended an outreach event. Doesn't use them much currently but plans to use them more.
Diversity and Comms use this for analysis and reporting.
Judicial Office organise Outreach events and the Outreach report is used to monitor attendance at the events and analyse it.

**Comment by NormaJAC** [comment]
Outreach video guidance no longer required, not used by Admins.
