### ISSUE TITLE
Add filters to Gantt chart

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2458]
## Background
This ticket relates to the incorporation of filters into [the new Gantt chart](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2406).

## User Story
As Programme Office, I would like to be able to filter the Gantt chart view so that I can easily view resource constraints, QT clashes, etc.

## Benefit(s) to user (if not already clear from User story)
- Users can condense the number of exercises displayed on screen to easily view a specific period of time

## Feature(s) Description
- [x] Create filters for the Gantt chart visual display as below
<img width="773" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85ace56c5a0348beeea039af92c4de6356bacda8/image.png" alt="image.png" />

- [x] Date filter: Launch date from/to
- [x] 3 tickboxes for exercise types, which are all ticked by default
- [x] Staff filter for Senior Selection Exercise Manager - the content should be filtered to include only users with the Ops Senior Manager user role
- [x] Staff filter for Selection Exercise Manager - the content should be filtered to include only users with the Ops team member user role
- [x] Both staff filters should include a blank option and be mutually exclusive, i.e. if a name from Senior Selection Exercise Manager is selected, Selection Exercise Manager filter should be reset to the blank option and vice versa
- [x] Tickbox that excludes any exercises in Draft status

## Acceptance Criteria 
It's done when users can interact with the filters specified to influence the Gantt chart display on screen.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Matt, Gemma and Adela only
Interact with the Gannt chart and share any observations where it falls short of requirements.

## Feature Champion
Matt (Gemma/Adela)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2458?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub

**Comment by drieJAC** [comment]
Note that I think the filters will need to be put into their own component from the JAC Table component as a part of this ticket.
