### ISSUE TITLE
Fix preview URLs for admin

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/admin#2467]
Preview URLs for admin are not working - the domains need to be added into the settings under hosting > domains in the firebase console.

This was working previously and evidently something in the background (most likely not within our codebase) has broken this. 

This functionality should be restored to avoid the necessity for manually adding the domains.

**Comment by tomlovesgithub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2467?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC

**Comment by warrensearle** [comment]
@drieJAC @HalcyonJAC @tomlovesgithub 

I have just added 'web.app' to the list of authorised domains and the preview URL now works. Please check if this has solved the issue.

Potentially this opens up the preview URLs to allow authentication from more domains than we need as we are allowing any subdomain of web.app. However we are also checking verified email domain so I don't think this is a security risk just potential for more traffic.

Let me know if it works for you and if you have any concerns

**Comment by HalcyonJAC** [comment]
I have tested it when creating a new PR (new preview link is generated) and it works for me.
