### ISSUE TITLE
SPIKE: Explore Gantt chart options that integrate with Vue3.js

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2469]
## Background
Omar made the point that it will be much quicker to source a pre-built Gantt chart library than building one from scratch. The focus of this ticket is to investigate Gantt chart library options. Chart.js does not have Gantt chart support so we'll need to look at alternatives, both free and paid. If paid, capture details on the pricing.

## User Story
As the Digital team, I would like to know what ready to roll Gantt chart libraries are available and what they cost.

## Feature(s) Description
- [ ] Gather details on Gantt chart libraries available off the shelf that will meet the majority of the requirements detailed in [the main ticket](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2406)
- [ ] Gather pricing details
- [ ] Pull the info together to present to the Product team

**Comment by nickaddy** [comment]
@drieJAC I've written this ticket on GC libraries research; does it make sense?

**Comment by HalcyonJAC** [comment]
Here are possible options: https://docs.google.com/presentation/d/1dQn1VU_4ZxoHWg443Kg50QvYjH5Lq6mMYD687SKA26U/edit?usp=sharing

**Comment by nickaddy** [comment]
@HalcyonJAC Out of the options provided, I think only Ganttastic is an option. However, it's hard to ascertain how many of [the requirements](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2406) would be covered. Are you able to shed any light on that?

**Comment by HalcyonJAC** [comment]
I outline the functionalities from [the requirements](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2406):
- The top row and left column can always be visible onscreen.
- The timeline is scrollable.
- The UI (e.g. text, hover effect) and style (e.g. colour, background) of the item in the timeline can be customised.

I found another library [vis-timeline](https://visjs.github.io/vis-timeline/examples/timeline/) that might be more suitable for our needs.

**Comment by nickaddy** [comment]
@HalcyonJAC This looks promising. I have a few questions:

1. Free or paid (how much?)
2. The boxes all appear to be the same size - can they be customised according to the start and end date of the activity?
3. How do we manage one day events, e.g. QT?
4. Do the boxes have rollovers that can display add'l info each start/end dates, longer title if it doesn't fit in the box? 
5. Can we set the default sort order of the rows?
6. Will we be able to code the inclusion of specific (not all) timeline activities only?

**Comment by HalcyonJAC** [comment]
@nickaddy 

1. Free
2. Yes
3. We could show it as a line.
4. We can make the long text visible or only show it if you hover over it.
    
    <img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVhKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60c2611ffaf1d376b685f39e1e79282efb85ad24/image.png" alt="image.png" />
 
5. Yes
6. Yes

**Comment by nickaddy** [comment]
@HalcyonJAC Following this morning's meeting, I am happy for you to move forward with vis timeline and for this ticket to be closed. Good luck!
