### ISSUE TITLE
Introduce a mechanism to distinguish exercises to be excluded from statistics

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2483]
## Background
There are certain exercises that should be excluded from JAC stats. There are: 

- External (non-JAC) exercises and 
- Welsh government exercises. 

External exercises are already identifiable as a different ad-type, but Welsh gov exercises will require a separate question to distinguish them.

## User Story
As Programme Office, I would like to create a mechanism to distinguish certain types of exercises so that it is clear which exercises should be included in JAC statistics.

## Feature(s) Description

- [ ] Add a question in the Exercise set-up under `Vacancy Information` - Is this a Welsh government exercise? with Yes/No radio buttons
- [ ] Add a new column `Type` to the Live Exercises page as the first column
- [ ] Add 'flags' in the Type column as follows:
1. EXT - appears when exercise is an external vacancy (identified by advert type)
2. GOW - appears when exercise is a Welsh vacancy (identified by answer 'Yes' to Welsh government exercise question)
3. JAC - appears when exercise is a JAC exercise, i.e. neither of the above

<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5dec1b6c20e7c6686d432df2c47960e5a5f3b00/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when it is possible on the Exercises Live page to clearly identify which exercises should be included in JAC statistics by their flags.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Matt

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2483?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by drieJAC** [comment]
@nickaddy to confirm will the radio buttons default to 'no' to indicate its not a welsh exercise?

**Comment by warrensearle** [comment]
This may be a silly suggestion but I'll make it anyway... Would it be worth combining this into the Reference field? So have:
 - **JAC00xxx** for JAC exercises
 - **EXT00xxx** for external exercises
 - **GOW00xxx** for Government of Wales exercises

**Comment by nickaddy** [comment]
> @nickaddy to confirm will the radio buttons default to 'no' to indicate its not a welsh exercise?

It is only by the user completing this question that the platform will know if it is a Welsh exercise or not. Having it default to 'no' seems sensible.

**Comment by nickaddy** [comment]
> This may be a silly suggestion but I'll make it anyway... Would it be worth combining this into the Reference field? So have:
> 
> * **JAC00xxx** for JAC exercises
> * **EXT00xxx** for external exercises
> * **GOW00xxx** for Government of Wales exercises

@warrensearle I like this idea but don't want overcomplicate matters; would it be a lot of work in terms of allocating the reference with the correct prefix and maintaining the consecutive number count, e.g. JAC0010, EXT0011, GOV0012?

**Comment by warrensearle** [comment]
> @warrensearle I like this idea but don't want overcomplicate matters; would it be a lot of work in terms of allocating the reference with the correct prefix and maintaining the consecutive number count, e.g. JAC0010, EXT0011, GOV0012?

This would be easy to do and maintaining the number count would work automatically: currently we get the 'last used number' from our db, increment it by one and then prepend with 'JAC' and 00s. Here we would simply collect the answer to whose exercise it was and determine what to prepend.

The only downside I can see is sorting exercises by reference number would take account of the prefix so we could 'lose' exercises... but then maybe it would be good to have the three types of exercise listed separately anyway?

Do the external or welsh exercises already have their own reference numbers and would there be any benefit in everyone using them rather than us creating the 'JAC00xx' one?

**Comment by nickaddy** [comment]
@warrensearle I don't think we want separate listing pages. Good point re the sort. Couldn't we just strip out the prefix and use the number only to do the sort?

**Comment by warrensearle** [comment]
> @warrensearle I don't think we want separate listing pages. Good point re the sort. Couldn't we just strip out the prefix and use the number only to do the sort?

That does start to complicate it as, rightly or wrongly, we currently store the full reference number including the 'JAC00' prefix in our db so to sort without the prefix would mean changing how we store this. 

**However**, thinking on this some more, we could make use of the `createdAt` date which we also store and so when the user wants to sort by reference number behind the scenes we instead sort by created date. (that's very easy to do in our Table component)

So what I am proposing is:

**Create exercise form** 
 - [ ] Include the 'Is this a Welsh government exercise?' question.
 - [ ] On save, set the prefix for the reference number as follows:
    - JAC00xxx for JAC exercises
    - EXT00xxx for external exercises
    - GOW00xxx for Government of Wales exercises

**Exercises list**
 - [ ] Amend the Reference column to use `createdAt` as the sort column. It should give the same behaviour but we ignore the reference number prefix so sorting is by the number part of the reference number
 
 _Note: in this ticket we are not updating the stats export to exclude any exercises. This is based on the understanding that here we are simply introducing a visual mechanism to make it easier for the user to select the correct exercises for stats purposes_


Current create exercise form:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/5eddda7f-57c5-4fc0-9ce6-0177aa70bbc9">

**Comment by nickaddy** [comment]
@warrensearle Thanks for the suggestions. Things are always more complex than on the surface! Happy with all the above - let's proceed on that basis.

**Comment by warrensearle** [comment]
@drieJAC @HalcyonJAC @tomlovesgithub please check through the above proposal and comment or update your estimate if necessary 😄
