### ISSUE TITLE
Remove CV as assessment option from Admin/Apply

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2486]
## Background
Following a decision at the July board, CVs will no longer be an assessment tool used on selection exercises (they were previously used on Senior/Leadership exercises only.) Instead, we have included a `career highlights` section on the candidate self-assessment form. Candidates' responses will be extracted from the .docx document, word counted and fed through to Application view as per the answers to the selected Skills & Abilities questions. Ideally this work will be completed prior to the launch of [JAC00213](https://admin.judicialappointments.digital/exercise/pRhlC8Ij2Aw0hEa001E6/details/overview) on 25 July and would apply to all future exercises, including those currently in Draft status. 

Clearly, any past or current exercises using CVs should be unaffected by this change.

**Pls note: the Career highlights section has already been included as an option in the skills and competencies dropdown under Assessment options.**
<img width="801" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5VQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e34e2c7fa44c78867dfdd7da5791aa13d676480c/image.png" alt="image.png" />

## User Story
As the Ops team, I would like the CV upload option to be replaced by the career highlights section so that candidates still have the option to provide relevant information on their suitability.

## Feature(s) Description
- [x] Remove CV as an option from Assessment options
<img width="802" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e376e540fea15671ce6b540764d20ea2604d52e7/image.png" alt="image.png" />

- [x] Ensure that candidates are not presented with an option on Apply to upload a CV in any circumstances
- [x] Test that candidates can input content to the Career Highlights question on the SA upload and are given the opportunity to edit, having been informed of the word count, before submitting
- [x] Test that the content added under Career Highlights in an upload is correctly word counted and pulled across to Application view on Admin
- [x] Confirm that this covers all instances related to CVs?

## Acceptance Criteria 
It's done when Admins are no longer able to add CV as an Assessment option and candidate are unable to upload a CV but instead complete the Career highlights section of the SA upload.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by drieJAC** [comment]
@nickaddy We may need to add a follow-on ticket to refactor this code to remove the code from Apply to support legacy applications that use CVs

**Comment by drieJAC** [comment]
New Developer Tasks For This Ticket:

- Remove the cv option on Admin
- On Apply if the CV option is present then display the CV section otherwise dont
- Check that the career highlights display when added to the SA template

**Comment by nickaddy** [comment]
@HalcyonJAC Are the other aspects of this ticket going to be picked up in another PR?

**Comment by HalcyonJAC** [comment]
@nickaddy I have created an exercise to test that candidates can input content to the Career Highlights question on the SA upload. It works fine. Here is an [exercise](https://apply-develop.judicialappointments.digital/vacancy/aD8YKYEYhQbPThjcaKsM/) on Dev if you would like to test it.

**Comment by nickaddy** [comment]
@HalcyonJAC That all works as it should. I noticed a minor display issue on Apply; when you are prompted to review your application, some of the meta-data is presented at the top of the self-assessment content section:
![image](https://github.com/user-attachments/assets/7987a472-db89-4269-a55b-468ff2eaaf3c)

**Comment by HalcyonJAC** [comment]
@nickaddy Thank you for spotting that. A [PR](https://github.com/jac-uk/apply/pull/1202) has been created to fix it. Could you test it, please?
