### ISSUE TITLE
Audit of Excel downloads on Admin

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2488]
## Background
There are numerous places on the platform from which data can be downloaded. The objective of this ticket is to compile a list of all the locations to support a review of which, if any, can be removed and which are still necessary. There are two aims here: 1) to limit the downloads to just the essential so that Admins use the functionality on the platform, and 2) limit the data downloaded from the platform to the essential only from a data protection perspective.

## User Story
As the Digital team, I would like a record of all downloads on the platform so that I can audit which are necessary to retain.

## Feature(s) Description
- [ ] Create a spreadsheet of all downloads on the platform with the following columns: Name of page (e.g. Eligibility report), Link (link to relevant page on the platform.)
- [ ] Save the spreadsheet in [Documentation](https://drive.google.com/drive/folders/1qBAKXxeRnbl__7T_4Ojvm2dL5qaek7S6?usp=sharing)

## Acceptance Criteria 
It's done when we have a comprehensive list of all downloads from Admin.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
@NormaJAC I've created a ticket for the piece of work we were talking about yesterday.

**Comment by NormaJAC** [comment]
Thanks Nick, just looking at it now.

Norma Taiwo
Business Analyst | Judicial Appointments Commission | M:07355 739557 | Pronouns: She/Hers
www.judicialappointments.gov.uk<http://www.judicialappointments.gov.uk/> | LinkedIn<https://www.linkedin.com/company/judicial-appointments-commission/> | Twitter<https://twitter.com/becomeajudge> |
***@***.***

**Comment by NormaJAC** [comment]
I've created and saved the spreadsheet and added it to Documentation.

**Comment by NormaJAC** [comment]
I've compiled the list of Excel downloads on the Admin platform; Develop, Staging and Production.
