### ISSUE TITLE
Transfer NINos from candidates to their applications on JAC00203

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2492]
## Background
Elliot Koh observed that there are 124 candidates that managed to submit applications on JAC00203 with missing NINOs. Admins use the NINo as a unique identifier to check, amongst other things, for duplicate applications. NINos, if populated in a candidate's profile, are auto-populated in any applications they make. Elliot has sent a message out to candidates with missing NINos in their applications to update the field in their profiles.

## Feature(s) Description
- [x] Write and run a script that copies the NINos from candidates to their applications on JAC00203

## Acceptance Criteria 
It's done when the all candidate applications on JAC00203 with previously blank NINos have been updated with the NINo from their profiles.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
No testing required.

**Comment by HalcyonJAC** [comment]
@nickaddy I have run the script to update NINO in 96 applications.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3Z1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b699c40ce0d379780e9c93aff01e320ddaaf2830/Screenshot%202024-07-18%20at%2012.32.09.png" alt="Screenshot 2024-07-18 at 12.32.09.png" />

**Comment by nickaddy** [comment]
@HalcyonJAC Happy for you to close this ticket, thank you.
