### ISSUE TITLE
Amendments to Additional settings page

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2494]
## Background
There is a draft 'Additional settings' page that will be used to set up the grading format in order to support input of scores for sifts and selection days on the platform. This ticket proposes a few tweaks to the set-up.

## User Story
As the Digital team, I would like to make it as straightforward as possible for Admins to set up the grading format on exercises so that there are fewer opportunities for human error.

## Feature(s) Description
- [x] Change the page name (and side navigation link) to `Selection set-up`
- [x] Introduce a radio button question at the top of the page - neither option is selected on initial visit
<img width="524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85721347ec5ca14fe0f0ab063fa9da45263d690f/image.png" alt="image.png" />
- [x] If Competencies is selected, the following options are displayed below, all ticked by default:
<img width="318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2060edad0f21a3a0cc55cdfbe5e1db49b62f71f3/image.png" alt="image.png" />
- [x] If Skills & Abilities is selected, the following options are displayed below, all ticked by default:
<img width="302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49a1e8f0575f26b5d69c196925a0bcb617aa4441/image.png" alt="image.png" />

Note: we will build in the 'Overall' columns to the marking sheet by default.

## Acceptance Criteria 
It's done when Admins can select one of two options and the relevant criteria and tools are displayed below, all ticked by default.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2494?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2494?planning-poker) with Zenhub @KoWeiJAC
