### ISSUE TITLE
Support inclusion of additional columns in Merit list download

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2495]
## Background
As part of the Merit list MVP, we aim to support Admins choosing additional columns to be included in the Excel spreadsheet for download.

## User Story
As an Admin, I would like to be able to select additional columns to be added to the Merit list download so that I can conduct additional tasks off platform.

## Benefit(s) to user (if not already clear from User story)
Admins can include only the columns necessary to their exercise rather than having to download all and delete the unnecessary columns.

## Feature(s) Description

- [ ] On the final screen of the merit list task in question, include the option for Admins to add the following additional columns to the download
- [ ] The columns that are ticked appear in the excel spreadsheet that is downloaded
- [ ] It is possible to return to this page and add additional columns at a later date
- [ ] Add `Download` button to all Merit list task pages

<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7392ac89d09f336c631057c359ba34af3b290c7/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when Admins can select from a range of additional columns to be added to the download and those columns appear in the downloaded excel spreadsheet.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2495?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2495?planning-poker) with Zenhub @KoWeiJAC
