### ISSUE TITLE
Exercise. Application Process. Update to use new Stages and Statuses

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2496]
Exercise Application Process allows teams to collect additional application data from candidates who are successful in reaching specific 'Steps' in the application process.

'Steps' are very similar to Stages however there are additional steps for Registration and Passed Tests.

Here we are reviewing our configured 'Steps' to ensure they align with the new Stages and Statuses

**Comment by nickaddy** [comment]
@warrensearle Can you give this some story pts pls? Reckon it ate up most of a day!
