### ISSUE TITLE
Support input of grades for Sifts/SDs directly to the Panellist app

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2501]
## Background
At the end of August, we will be running a workshop with a group of panellists with the objective(s) being to gain their buy-in and input on a mechanism through which they upload the grades for sift and SD activities to the panellist app. This ticket focuses on that mechanism.

## User Story
As JAC, I would like Panellists to be able to input grades for sift and SD activities directly to the platform so that there is a single source of the truth and the process becomes much more efficient.

## Benefit(s) to user (if not already clear from User story)
- Human error is reduced
- The merit list can be produced, ranked and downloaded directly from the platform

## Feature(s) Description
- [ ] Panel chairs that have been allocated sift or SD grading tasks on the panel portal are able to upload scores directly from the clipboard (mirror the mechanism currently utilised for the Scenario Test task, only on the Panellist app)
- [ ] The format of grading on the screen reflects that which has been set up on the Additional settings page of the exercise (ticket [2494](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2494))
- [ ] Any additional columns requested by the Admin (ticket #[2500](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2500)) have been added to the online scoresheet

## Acceptance Criteria 
It's done when the grading onscreen reflects the grading set up by the Admins in Additional settings.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2501?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Hi @nickaddy please find below a link for you to log into the Panellist app which has been amended to support pasting scores from clipboard:

https://jac-panellists-develop.web.app/

If you log in with your nick.addy@judicialappointments.digital google account you should have a Sift to complete.

Please could you in particular look at the wording on the screens involved, including:

Login
<img width="1581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73b09dd6e4605dda3c0b0fc77fc7f575652dbdd7/image.png" alt="image.png" />

Home
<img width="1708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28ebbf8ea0fcd3ff71066a4efcb2b020e26496b0/image.png" alt="image.png" />

Paste instructions
<img width="1579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49f483a9d65a997e38b015c3022033e5c872ed8b/image.png" alt="image.png" />

Review uploaded grades
<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74a3d424cec24d36134a239bd734237dadd78465/image.png" alt="image.png" />

Completed
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1SQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a369a3fba9230347c41fbf7cd609c9fcd20ba748/image.png" alt="image.png" />

Re-visit completed task
<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHVSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a07bba29175344f183b81f854a0a3dbcf6f82a3/image.png" alt="image.png" />

**Comment by warrensearle** [comment]
This ticket was more about testing and preparing data for the user workshop (the functionality being covered by other tickets) therefore I think we can close this as completed.

@nickaddy please can you close if you agree with the above.

**Comment by nickaddy** [comment]
@warrensearle I need to share some changes required following the pilot; is this the best place?

**Comment by warrensearle** [comment]
@nickaddy 

We used to store User Research results on google drive for future reference (e.g. so we know where they are if we have a service assessment)

I'd suggest any changes go in a new ticket (you can refer back to this one) and we can then review and, if needed, break it down into smaller tickets.
