### ISSUE TITLE
Identify And Fix NPM Vulnerabilities In All Repositiories

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/admin#2513]
## Background
Identify and fix npm vulnerabilities in all repos

## User Story
For all repositories, on a monthly basis and as a developer, I want to run npm audit checks to expose any new npm vulnerabilities and fix them to prevent ongoing security issues from package dependencies.

## Feature(s) Description

Ensure there are no vulnerabilities in the following repos:
- [ ] admin
- [ ] apply
- [ ] digital-platform
- [ ] assessments
- [ ] qt
- [ ] qt admin
- [ ] qt platform

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2513?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @KoWeiJAC
