### ISSUE TITLE
Create Internal Exercise Process Stalls

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/admin#2516]
## Describe the bug
When an internal JAC exercise is created and we specify to add ALL information the process stalls because the page we navigate to when we press the Save And Continue button matches the one we're already on.

The following line of code seems to be causing the issue:

this.$router.push(this.$store.getters['exerciseCreateJourney/nextPage']('exercise-details-summary'));

... because the getter returns the 'exercise-details-summary-edit' route which is the page we're on.

## To Reproduce
See video:

https://github.com/user-attachments/assets/12b9a731-9077-4157-aa5d-280a7a0e850b

**Comment by nickaddy** [comment]
@drieJAC @KoWeiJAC Could this be connected with the recent approval change?

**Comment by nickaddy** [comment]
Closing as legacy issue
