### ISSUE TITLE
Write tests for and tidy our helper libraries

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2529]
## Background
At the moment, there are some growing helper libraries which are duplicated between Admin and DP. This is inefficient. The focus of this ticket is to write tests for and refactor/tidy our helper libraries.

## User Story
As the Digital team, I would like to eliminate duplication of libraries between Admin and DP so that I can work more efficiently.

## Feature(s) Description
- [x] Write tests for our helper libraries: Exercise helper, Tasks helper, Merit list helper
- [ ] Refactor helper libraries: Exercise helper, Tasks helper, Merit list helper

## Acceptance Criteria 
It's done when our helper libraries are nice and tidy!

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Internal testing only

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2529?planning-poker) with Zenhub @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Please base this work on the following branch and focus on writing tests first then tidy/refactor later (some of the functions are liable to be moved/changed in the coming day or two):

https://github.com/jac-uk/admin/tree/feature/2247-selection-day

**Comment by KoWeiJAC** [comment]
@nickaddy @warrensearle 
I'm trying to find merit list helper functions, but I can't see files named merit list, could you should with me how I can find them? Thanks

**Comment by warrensearle** [comment]
> Please base this work on the following branch and focus on writing tests first then tidy/refactor later (some of the functions are liable to be moved/changed in the coming day or two):
> 
> https://github.com/jac-uk/admin/tree/feature/2247-selection-day

Hey @KoWeiJAC did you see this comment? The meritlist helper is in Exercise/Tasks/Finalised/ folder (or thereabouts)

**Comment by KoWeiJAC** [comment]
> Exercise/Tasks/Finalised
@warrensearle 
Thanks for your sharing, I saw merilist helper by following the path you mentioned.
Thank you so much!
