### ISSUE TITLE
Combined exercise workflow

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#253]

**Comment by KateMJAC** [comment]
@warrensearle is this something that has been achieved. I know we need workflow for combined QTs, which would appear to be a seperate issue?

Combined QT workflow will be dealt with under the QT Epics.

**Comment by warrensearle** [comment]
Hey @KateMJAC I know we ran a combined exercise in 2020 and part of the work we did to enable that was to allow Invite-only Exercises (see admin#915). I would guess there is more we could do to help. Do you know if the current workflow has been documented for others to follow? Let's discuss.
