### ISSUE TITLE
Identify And Fix NPM Vulnerabilities In All Repositories - mid-September 

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2532]
## Background
Identify and fix NPM vulnerabilities in all repos. This should be **conducted in the middle of the month** to ensure it is regular. **Once completed, the ticket should be duplicated and renamed for the next sprint.**

## User Story
For all repositories, on a monthly basis and as a developer, I want to run NPM  audit checks to expose any new NPM vulnerabilities and fix them to prevent ongoing security issues from package dependencies.

## Feature(s) Description
Ensure there are no vulnerabilities in the following repos:
- [ ] admin
- [x] apply
- [x] digital-platform
- [x] assessments
- [ ] qt
- [ ] qt admin
- [ ] qt platform

**Comment by nickaddy** [comment]
@HalcyonJAC @tomlovesgithub I've created a duplicate of this ticket for September - perhaps we could make that the responsibility of whoever is working on the current ticket to make a duplicate for the next month?

**Comment by tomlovesgithub** [comment]
New tickets will be created for any vulnerability that are found by running audit checks against each repo, and will be estimated individually.

**Comment by drieJAC** [comment]
Fixes were applied to the following repos:

**apply**: https://github.com/jac-uk/apply/pull/1222
**assessments**: https://github.com/jac-uk/assessments/pull/190
**digital-platform**: https://github.com/jac-uk/digital-platform/pull/1194

**Comment by nickaddy** [comment]
@drieJAC Is this task complete for September? If so, can a duplicate be created for October and this ticket closed pls?
