### ISSUE TITLE
Character agency report

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#254]
As an admin I need to be able to download information about candidates for each agency that undertakes character checks, for example ACRO who conduct criminal record checks. This is part of the process if checking candidates have declared all relevant character issues and is information that is put to the Commission when making decisions on character. 

I need to be able to download different information depending on the agency and export this to an excel file to then send emails to those agencies. 

This Epic consists of: 
1.) Create a consent form on admin #519
2.) A webform opens up with consent form on apply apply#298
3.) Candidate fills in and submits consent form apply#299
4.) The information is displayed under applications in their accounts apply#300
5.) Different tabs for different agencies on admin #520
6.) Each tab populated with the information candidates input #521
7.) Information exportable in excel file #522
8.) Add Agency tab to candidate record #523

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC and @Rebecca-mcknight1991 do we have a definition of the fields you need to be able to download for each agency?

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC and @Rebecca-mcknight1991 what should be configurable when creating a consent form?

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC and @Rebecca-mcknight1991 how is information from each agency entered back into the system?
- Edit form
- Import a file
- Automated
