### ISSUE TITLE
Custom report data overflow

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2544]
## Background
When users run a custom report, they often find that the data has overflowed across multiple rows. Additionally TRUE appears in some cases; it's not really clear what that means. For example, on JAC00082 (Archived,) when Candidate Reference # and Employment gaps are selected, the data looks like this onscreen and in the download:

<img width="1178" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2w5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--192806abb8822c9df3d2e4c5b7907d7a3ca0644c/image.png" alt="image.png" />

<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3A5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--741a9ad6288d1fab0e37528dc0e6875f56e0a7e3/image.png" alt="image.png" />

## User Story
As an Admin, I would like multiple entries for a candidate to appear in the same row rather than overflowing into multiple rows so that the report is easy to read.

## Feature(s) Description
- [ ] Explore and resolve the reasons for the data overflow
- [ ] Clarify what TRUE means and look to substitute with clearer wording

## Acceptance Criteria 
It's done when custom report data is not overflowing over multiple rows.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Sean

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2544?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub @warrensearle

**Comment by drieJAC** [comment]
@drieJAC Why is this ticket closed? The issue has not been remedied, if anything it is worse than before...view report [here](https://admin.judicialappointments.digital/exercise/27XRfjOU65Nd1enzLsLt/reports/custom)

**Comment by drieJAC** [comment]
@drieJAC Here's [another example](https://admin.judicialappointments.digital/exercise/K684SxTmTIwsRWnPefqm/reports/custom); I've only added one field and I've got rollover rows...
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25DQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--556e09a16d0290ecefee875bc16aab5f0bd6c88a/image.png" alt="image.png" />

**Comment by drieJAC** [comment]
I've changed this ticket estimation to an 8 due to the extra work off the back of @nickaddy's comments

**Comment by drieJAC** [comment]
@nickaddy has requeted we set the 'Applied' tickbox as checkjed by default when the custom report page loads as it looks like candidates only get an app reference number once it has been submitted. This will prevent scenarios where the reference number is incomplete.
