### ISSUE TITLE
Update application view in line with the character updates to the application form

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2551]
## Background
[Changes have been made to the Character](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1209) section of the application form; the Application view on Admin should align with these changes.

## User Story
As an Admin, I would like the Character changes to be reflected in the Application view so that I can see the updated version of character there.

## Feature(s) Description
- [ ] Application view displays the updated questions
- [ ] Application view displays the updated text
- [ ] It is possible to edit and save the new fields

## Acceptance Criteria 
It's done when:
- [ ] The application view on Admin Character section aligns with the changes to the character section of the application form on Apply
- [ ] The new fields are displayed in the application view on Admin
- [ ] The new fields are editable in the application view on Admin

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Joanne Dixon/Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2551?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by KoWeiJAC** [comment]
@nickaddy 
The wordings in admin site are different from apply site.
In Admin site, it will remove you or your, and the wording will be shorten.
In Apply site, it will be the same as the [document attached](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1M4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4429012590020540647844f8e8bd5ab193bd29ae/Amendments%20requested%20to%20Character%20questions.docx).

If it is ok that we add critical changes to Admin site ? Or the wordings in Admin site needs to be identical to the document ?

- Old
<img width="1789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUQvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--113260080b3735a4a231edd408689e586d2e806a/Screenshot%202024-09-25%20at%2016.32.51.png" alt="Screenshot 2024-09-25 at 16.32.51.png" />

- Updated
<img width="1605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUwvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1c93ed99c3fbd8f0998a504a1190fa877939640/Screenshot%202024-09-25%20at%2016.35.36.png" alt="Screenshot 2024-09-25 at 16.35.36.png" />

**Comment by nickaddy** [comment]
@KoWeiJAC It's important, I think, that the key changes are captured, i.e. where an additional clause has been added at the end of the question. Obviously, the new questions (and section) need to be added in Admin.
