### ISSUE TITLE
Updates to Character Annex following pilot

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2557]
## Background
The Character report has been piloted on a live exercise - [JAC00187 ](https://admin.judicialappointments.digital/exercise/lB0dht6mY4kSXTQusGqd/reports/character-issues)- and there are a few tweaks resulting. 

## Feature(s) Description
- [x] Fix the typo in the displayed response to the 'Has any other character issues' question
<img width="571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWV3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ff273b6c25b330a900f5c6896c17327adf1e8d/image.png" alt="image.png" />

- [x] Fix the issue with the page number links at the bottom: when you click 3 or 4, the page content stays the same (however, the next (page) link does work
- [x] Numbers are displaying incorrectly next to S&S dropdowns (shows 18 in this case, but should not be 39)
<img width="472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJ3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6aadc30633f3304a1519158f3a5aa1a560838f43/image.png" alt="image.png" />

- [x] Can the stage and status filters be set to default to `SCC` and `Recommended to SCC` respectively?
- [x] When the Recommended SCC approach filter is used, it only filters the entries on the page - it should search the entire report and then paginate if necessary
<img width="478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemF6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b76529d912ff4c121ed898fe999adf743bb55091/image.png" alt="image.png" />

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2557?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
@nickaddy I have one question. If candidates don't have any character issues, should they appear in the table? For the exercise JAC00187 there are 39 candidates in the SCC stage but only 18 candidates with character issues.

**Comment by nickaddy** [comment]
@HalcyonJAC Only candidates with character issues should appear in the character annex report, is that the way it works now? In this case, there are 39 candidates that fall into that category.
