### ISSUE TITLE
Handover report

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#256]
Most candidates who are "Recommended for appointment" or "approved for immediate appointment" their data will need to be transferred to Judicial Office to complete their appointment. This happens in the the handover stage. 

We create a handover report for the Judicial Office.  This consists of some details from the consent form and application information that the candidates provides.

There is an exception in terms of diversity data.  We can only share diversity data where candidates agreed on their application. 

<img width="619" alt="Screenshot 2020-07-13 at 13 42 11" src="https://user-images.githubusercontent.com/27224574/87305629-b976b500-c50e-11ea-8b19-4c8d7ab58778.png">

The transfer of data happens in two parts:  

1) A CSV that can be downloaded from the platform and emailed to Judicial Office
2) A file in format that can be either automatically transferred to the Judicial Office system or can be downloaded into a format that can be emailed and uploaded to the Judicial office system (previously this was an XML file)

For the first part of this epic we need

- The ability to display the handover information #663 
- Create two handover CSV #666 
- The ability to exclude diversity data where the candidate does not want it shared #664 
- The ability to export the handover information into a csv #665 

The content of the report is shown here:  
Please note there are TWO versions one for Legal and Leadership exercises and one for non legal exercises

https://docs.google.com/spreadsheets/d/1ZhkahRre49AEtTZ-_-WkNjY70KHCg5fh4_NZwBik-FU/edit?usp=sharing

For the second part of the epic we need to complete a spike with Judicial Office to look at the options available.  There is some discussion of whether we can transfer data via an API.  

So for this part of the epic it will fall into two parts:

1) A spike to determine options
2) Tickets to produce the option chosen

**Comment by KateMJAC** [comment]
@warrensearle, can this ticket now be closed as I have created a new JO handover automisation Epic #1167 and linked #617 and #615 to it?

**Comment by warrensearle** [comment]
@KateMJAC yes it can :)
