### ISSUE TITLE
Updates to phone number fields on Admin

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2560]
## Background
In [this ticket](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1220), we have made some changes to fields on Apply; these need to be reflected in the Application view and edit on Admin.

## Feature(s) Description
- [ ] Existing phone number field no longer appears in Application view
- [ ] New mobile phone number field appears in Application view
- [ ] New mobile phone number field is editable on Application view

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

**Comment by drieJAC** [comment]
@nickaddy dont we need to support **both** mobile phone number **and** phone number for new and legacy applications?
Also we will need to have validation for the new mobile phone number field

**Comment by nickaddy** [comment]
@drieJAC I think so, yes, that's why I suggested just not displaying the old phone number field rather than deleting it. Admins will still see the number on Admin only not the candidates on Apply.

The validation for the new field is covered in the [2FA ticket](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1220).

**Comment by drieJAC** [comment]
@nickaddy this also needs to be implemented in the candidates page in admin so I'm going to up this ticket estimate to a 5
