### ISSUE TITLE
Admins have access to the candidate assessments and or CVs

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#257]
Is your feature request related to a problem? Please describe.

Admin staff need to access candidate assessments and or CV to share them with panel members

Describe the solution you'd like

- They need a central store to see them - preferably on google drive or somewhere in the platform.  
- They need to be printable
- They need to have the candidate name and reference number display if possible.  

Describe alternatives you've considered
Automating the three elements that the panel needs to see into one electronic document that can be shared on Google Drive that the panel access to review applications and create a report about the candidates.

**Comment by warrensearle** [comment]
On the Application Details page there are now direct links to the files the candidate uploaded. This is a basic/initial fix in order to meet today's deadline. We will need to revisit in order to include
- [ ] moving the files across to google drive
- [ ] virus checking
