### ISSUE TITLE
Admin portal improvements to Merit list MVP 

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2573]
## Background
As a result of internal testing and UT, we need to make some improvements to the Merit list MVP functionality on Admin.

## Feature(s) Description

- [x] Add character limit of 40 for Title field for Custom column
- [x] Change ‘Exclude from score’ to ‘Include in overall score’ and make it unticked by default (flip the logic accordingly)
- [x] Exclude from score tickbox only appears if `Grade` selected as option type
- [x] Reinstate back button to aid navigation in the panel set-up task
- [ ] ~Panel packs should be created in the exercise root folder: a standard nomenclature has been agreed - exercise reference number, i.e. JAC00XXX (separate DP ticket?)~
- [ ] ~If the root folder is not found, an error message is generated: 'Folder not found - please rename root exercise folder according to the reference number of the exercise, i.e. JAC00XXX.  (separate DP ticket?)~

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2573?planning-poker) with Zenhub @warrensearle

**Comment by nickaddy** [comment]
@warrensearle I'm thinking that we should release what we have so far and then I'll write another ticket for the next iteration, I think we're ready do you agree?

**Comment by warrensearle** [comment]
@nickaddy yes I agree with the above

**Comment by warrensearle** [comment]
The included changes can be seen on this preview URL:
https://jac-admin-develop--pr2537-feature-2247-selecti-u2d4m3ls.web.app/

They are part of the following PR:
https://github.com/jac-uk/admin/pull/2537
