### ISSUE TITLE
Updates to QT tasks on Admin

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2577]
## Background
In line with the other updates to the QT platform, there are a few minor points related to QT tasks on Admin that would benefit from updating.

## Feature(s) Description
<img width="1192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZ0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ada11241940afa933ccf13411d2c910954fe445/image.png" alt="image.png" />

- [x] ~Present stats on test Task pages consistently: the order should be Not started, failed, passed~
- [x] ~Fix typo on 'Send report notfication' button on both SJT and CAT pages~

- [x] Test and confirm 'Send report notification' functionality is still working

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2577?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Hey @nickaddy I have ticked off the items in this ticket that have already been addressed in the Merit List MVP work https://github.com/jac-uk/admin/pull/2537

So that just leaves:
- [ ] Test and confirm 'Send report notification' functionality is still working
