### ISSUE TITLE
Exercise dashboard iteration 

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2579]
## Background
The iteration of the exercise dashboard is a Roadmap item aiming to simplify the overview page. The main update is to include the total number of candidates at each stage in the tabs under the diversity charts.

## User Story
As an Admin, I would like the dashboard overview page to include candidate total numbers so that I can quickly view the number of candidates at each stage of an exercise.

## Benefit(s) to user
Admins would be able to see at a glance at the bottom of the page, an overview of the figures, i.e. number of candidates at each stage.
It will be clearly displayed that withdrawn candidates will be included in the total counts.
 
## Feature(s)

- [ ] Withdrawn candidates should ~~not~~ be included in the counts (currently they are excluded)
- [x] `(includes withdrawals)` to be added after 'Applied' as shown in the image below

<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e518d8fa2005f2c470d33e6f8841b799683ea0b/image.png" alt="image.png" />

- [x] Following the text in each tab for Applied, Shortlisted, Passed SD, Recommended to JO, the total number of candidates at that stage should be included in brackets as in the image below
<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3daQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e59c8163fcf396b8da18e678713a97d4b3be7e94/image.png" alt="image.png" />

## Acceptance Criteria
It's done when 
- [x] withdrawn candidates are included in counts
- [x] the text 'Applied' (includes withdrawals)' appears on the dashboard
- [x] the total number of candidates at each stage are displayed in the tabs for each stage  
   
## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Sean C

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2579?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle
