### ISSUE TITLE
Ability for panel to see a modified application view with reference number

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#258]
**Is your feature request related to a problem? Please describe.**
Panel members and the exercise teams need to see a modified application view with reference number

**Describe the solution you'd like** (goes in order of application except personal details at the top)

This view should NOT include:

- personal details, 
- equality and diversity 
- character information
- location preferences
- jurisdictional preferences
- interview preferences (new ticket)

The information should be grouped by the pages the information is stored. i.e all judicial experience should be together in one section.  

**Describe alternatives you've considered**
A download that the teams could amend if necessary.

**Additional context**
Ultimately this view should be exportable

Linked to ticket #360

**Comment by ClaireTroughtonJAC** [comment]
@YaaL This is only paused because I need to confirm whether reasonable length of service should be included.  Am checking and will come back asap.

**Comment by ClaireTroughtonJAC** [comment]
@YaaL Please can you remove the "reasonable length of service" information from the panel view.  Then this is good to go.

**Comment by YaaL** [comment]
@ClaireTroughtonJAC "reasonable length of service" now removed from panel view.
