### ISSUE TITLE
Merit list MVP Iteration 3.0 DRAFT

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2582]
## Background
Some helpful feedback came out of Nick's demo to Rob, Meena and Matt on 3 October. We have time to further iterate and incorporate these improvements ahead of the live exercise pilots in November.

## Feature(s) Description
- [x] Leadership (although not used frequently) should appear as an option - unticked by default - under Competencies > Selection Criteria
<img width="585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c074b98d141f4422214ab87c2f80311c37d63c6/image.png" alt="image.png" />
- [x] Working effectively should appear as an option - ticked by default - under Skills & Abilities > Selection Criteria
- [ ] ~~In the panel set-up task, the Judicial assessor needs to be added manually as they vary from one exercise to another and will not be included in the panellist database - that is lay panellists only - i.e. we need to have an email address free text field next to Judicial assessor~~
- [ ] ~~The previously mentioned email address box should be validated to confirm an @judicialappointments.digital email address has been input~~
- [x] We need to ensure there are applications for the Task, particularly at the Panel set-up stage. As when there are 0 applications the user is able to proceed without setting up any panels!
- [x] On non-legal exercises, chosen competencies may be split and only tested once at interview and situational questions, e.g. EJ & PBK tested at interview, ACI, WCO & MWE tested at situational questions. At the step where Admins are prompted to confirm/remove columns, we need to find a way to facilitate this set-up
- [x] It is possible that a candidate could withdraw after the sift has been set up (the same applied to selection day) and we need to provide a solution for that scenario - one possible solution is for all cells to include a Withdrew option in the dropdown, otherwise grading sheet will be incomplete and panellist will be unable to submit
- [x] Candidate full name should be displayed on Admin rather than reference number (In panel packs and on panel portal, candidate reference number should be used
- [x] Merit list download should be a carbon copy of what is onscreen, i.e. include all the grade etc columns from the grading sheet
- [x] Once panel chair has submitted grades, users on Admin should have an opportunity to edit the grades with a reason box alongside containing the following options: Moderation, human error, changed by SCC, other
- [x] Replace true/false with yes/no in merit list download

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2582?planning-poker) with Zenhub @warrensearle

**Comment by warrensearle** [comment]
Hey @nickaddy with regards:

>On non-legal exercises, chosen competencies may be split and only tested once at interview and situational questions, e.g. EJ & PBK tested at interview, ACI, WCO & MWE tested at situational questions. At the step where Admins are prompted to confirm/remove columns, we need to find a way to facilitate this set-up

This is how the page currently looks:
<img width="563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bfd345e71521dee61a2640f5c36234f88605e4c/image.png" alt="image.png" />

This enables the user to remove columns from each of the selected tools, which I think already achieves what you're looking for.

Please could you check the requirements for 'Overall' grades as I'm not sure I've got it right at the moment. As in currently for Selection Day there will be an 'Overall' grade within each of the chosen Tools plus there will be an additional 'Overall' group containing all of the chosen capabilities plus another 'Overall' grade. That's a lot of 'Overalls'!

**Comment by nickaddy** [comment]
@warrensearle Here's my shopping list!

I have scrubbed out a couple of tasks from the original ticket above, but there are some unticked tasks still required. I've got a feeling you've actioned some of them already, but you've not ticked them off.

ML MVP additional requests:
Admin
•	Amend options in Reason for moderation dropdown to: Human error / Moderation / SCC request / Write-up change
•	SD grading sheets, generated by the platform into panel packs, should include candidate names as well as/instead of candidate reference numbers
•	Candidates that withdraw after a sift has commenced, i.e. after grading sheets have been generated, should be withdrawn by Admins (not panellists) and the panel portal should be updated to not expect grades for that candidate
•	Hide the ‘include in scoring tickboxes in the sift and SD tasks – scoring appears to be working as it should and this will confuse users when setting up the grading sheets
•	When Skills & Abilities framework is selected, the columns are in the correct order onscreen, but not on the grading sheet created – the correct order is L&J, PQ, L; this needs to be corrected 
•	Add location prefs and jurisdiction prefs as columns that you can turn on/off on the merit list, this will help Admins to produce multiple merit lists in such cases (would these appear as 1. Wales, 2. Western, etc.?) all the content doesn’t have to appear onscreen, but they can download and then manipulate the ML.
 
Panel portal
•	Candidates that withdraw after a sift has commenced should not appear on the online grading sheet when pasted in (panel chairs will be instructed to leave row blank in the grading sheet)
•	Add Full screen button to score upload page of panel portal (as per on Admin pages)

Happy to discuss if any of these unclear. Could we get these closed and merged once we have tested internally? Any additional incremental items we can create as new tickets.

**Comment by nickaddy** [comment]
@warrensearle I think I may have Slacked these to you previously, but just going over my notes, I found one or two other points to flag:

- Hide judicial member row from panel set-up screen (we may revisit later, so hide probably better than delete)
- On Admin under the Sift/SD task, on the Merit list tasks, candidates names rather than reference numbers should be displayed
- In relation to previous point, Find should be by candidate name rather than reference number
- On sift/SD tasks, can we hide the 'Not started' metric at the top of the page; this should only display on the QT tasks

**Comment by warrensearle** [comment]
> @warrensearle I think I may have Slacked these to you previously, but just going over my notes, I found one or two other points to flag:
> 
>     * Hide judicial member row from panel set-up screen (we may revisit later, so hide probably better than delete)
> 
>     * On Admin under the Sift/SD task, on the Merit list tasks, candidates names rather than reference numbers should be displayed
> 
>     * In relation to previous point, Find should be by candidate name rather than reference number
> 
>     * On sift/SD tasks, can we hide the 'Not started' metric at the top of the page; this should only display on the QT tasks

@nickaddy these are all done

**Comment by warrensearle** [comment]
> @warrensearle Here's my shopping list!
> 
> I have scrubbed out a couple of tasks from the original ticket above, but there are some unticked tasks still required. I've got a feeling you've actioned some of them already, but you've not ticked them off.
> 
> ML MVP additional requests: Admin • Amend options in Reason for moderation dropdown to: Human error / Moderation / SCC request / Write-up change • SD grading sheets, generated by the platform into panel packs, should include candidate names as well as/instead of candidate reference numbers • Candidates that withdraw after a sift has commenced, i.e. after grading sheets have been generated, should be withdrawn by Admins (not panellists) and the panel portal should be updated to not expect grades for that candidate • Hide the ‘include in scoring tickboxes in the sift and SD tasks – scoring appears to be working as it should and this will confuse users when setting up the grading sheets • When Skills & Abilities framework is selected, the columns are in the correct order onscreen, but not on the grading sheet created – the correct order is L&J, PQ, L; this needs to be corrected • Add location prefs and jurisdiction prefs as columns that you can turn on/off on the merit list, this will help Admins to produce multiple merit lists in such cases (would these appear as 1. Wales, 2. Western, etc.?) all the content doesn’t have to appear onscreen, but they can download and then manipulate the ML.
> 
> Panel portal • Candidates that withdraw after a sift has commenced should not appear on the online grading sheet when pasted in (panel chairs will be instructed to leave row blank in the grading sheet) • Add Full screen button to score upload page of panel portal (as per on Admin pages)
> 
> Happy to discuss if any of these unclear. Could we get these closed and merged once we have tested internally? Any additional incremental items we can create as new tickets.

@nickaddy these are almost all done so I propose closing this ticket. We can take care of adding location/jurisdiction preferences via a new ticket, as we need to discuss further anyway.
