### ISSUE TITLE
Ability to print the modified application view 

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#259]
**Is your feature request related to a problem? Please describe.**
The teams need the ability to print the new modified panel view. Ideally we need the ability to download as PDF

**Describe the solution you'd like**
Ability to print the panel application view 
Ability to download as PDF

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle why is this blocked?

**Comment by warrensearle** [comment]
Hi @Rebecca-mcknight1991 this is related to #258 which needs to have been built before this issue can be worked on fully (see dependency link added to this issue)
