### ISSUE TITLE
Correct exercise-type field misalignment

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2600]
## Background
The type of exercise is misaligned with what is being displayed on the dashboard and the vacancy information page; it should show Leadership as per what is specified in the Vacancy info:

<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7b6d77f253e5a1454c41f252938f67e7151d0f3/image.png" alt="image.png" />

<img width="1241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8c006533a4e968c0eccf49e88852601ca9fc4d9/image.png" alt="image.png" />

<img width="1189" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79323eeac83cfbbec3c03b698de6f0b3239c6d59/image.png" alt="image.png" />

## Feature
- [ ] Correctly align display of exercise type - should read 'Leadership'

## User Testing Steps
Internal testing only

**Comment by HalcyonJAC** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2600?planning-poker) with Zenhub @drieJAC @KoWeiJAC @tomlovesgithub
