### ISSUE TITLE
Add Page Which Lists User Raised Issues

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/admin#2608]
Build a page which only digital super users can see that displays a table of bug reports in descending order of when they were created (newest first).

**Comment by nickaddy** [comment]
Is this not what the [ZH page](https://app.zenhub.com/workspaces/platform-issues-65310000d7eb371741bcfe5e/board) displays?

**Comment by drieJAC** [comment]
@nickaddy I guess the idea is that this page would be a catchall in case any of the api calls fail and there is a disconnect between what's in the repo and what's in our database.

**Comment by drieJAC** [comment]
@nickaddy we should have a chat about this to decide whether to remove the ticket or not
