### ISSUE TITLE
SPIKE: Investigate Slack functionality for issues channel

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2626]
## Background
Following the session on 28/11/24 when we reviewed how the issues channel is working, we would like to investigate some potential improvements on Slack.

## Feature(s) Description
- [x] Check whether it is possible to block direct posts into the Slack channel, except for our automated alerts when an issue is reported
- [x] If it is possible to block direct posts into the Slack channel, as above, check if it is possible to allow users to respond only in a thread under the issue alert post
- [x] Investigate the possibility of having a developer rota in Slack
- [x] If a rota is possible, can the developer on duty be automatically assigned to tickets that are posted, or can we hook into a rota list outside of Slack?
- [x] If we had multiple options from the report an issue button, e.g. ask a question, could we have have those assigned to a different person or not assigned to anyone?

## Feature champion
Nick

**Comment by HalcyonJAC** [comment]
**1. Check whether it is possible to block direct posts into the Slack channel, except for our automated alerts when an issue is reported**

Yes, it’s possible to set posting permissions to adjust who can post to channels.
https://slack.com/intl/en-gb/help/articles/360004635551-Manage-channel-posting-permissions

**2. If it is possible to block direct posts into the Slack channel, as above, check if it is possible to allow users to respond only in a thread under the issue alert post**

It seems not possible to restrict users from responding only in a thread.

**Comment by nickaddy** [comment]
@HalcyonJAC I've followed those instructions, but I don't see the Posting permissions link in the Slack channel settings. Are you able to see it?

It seems like the control is not granular, either all members can post to the channel or individual members can be prevented from posting, but if you block direct posting, they would not be able to reply in a thread, is that correct?

**Comment by HalcyonJAC** [comment]
@nickaddy It seems that we can set posting permissions in the [#general channel](https://slack.com/intl/en-gb/help/articles/220105027-Use-the-general-channel-to-share-announcements) as our subscription is Pro.

**Comment by HalcyonJAC** [comment]
@nickaddy Yes, we can check which option it is first and then decide whether we should create a ticket on Zenhub/GitHub. I have tested it is doable to post a message via Slack API.
