### ISSUE TITLE
Continue to build the report as per template

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#263]
**Is your feature request related to a problem? Please describe.**

Continue to build the remaining stages of the diversity report including the comparison as per template

**Describe the solution you'd like**
I want to display the data as per template.  
Link to template: 
https://drive.google.com/open?id=1-qtlAObuVz4cTFvqDCORldgezWsx7QcsPgtgdtDdKEQ

**Describe alternatives you've considered**
A interactive screen that records the Equality and Diversity team checkpoints 
The final report screen is exportable.  

**Additional context**
Begins of a wireframe for the full functionality.  
https://balsamiq.cloud/s156m8n/pe2ips8/r2278
This ticket will relate to how application statuses are updated as this will affect the calculations at each stage.

**Comment by warrensearle** [comment]
The current diversity report is generated in-browser and not meant for exercises with more than ~100 applicants.
Before we continue to build this report and others we should consider the most appropriate stack to power our reports.

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle Do we also need to consider how we define candidates going forward i.e who passed the stage we are reporting on.  Joe Bloggs passed the sift and Mickey Mouse didn't.  I will be adding a ticket for status updates.

**Comment by warrensearle** [comment]
The report has now been updated so that all the heavy lifting is done in the cloud (via a callable function).

Updating the styling has been moved to a future ticket - the styling is being prototyped, which will then result in the new ticket.

We've gone as far as we can with regards application stages. Follow up work is captured in #356

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle I am having problems with the diversity report I have tried a couple of exercises on two devices but the screen is blank and even when I press refresh nothing happens.

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC this is fixed now. Needed to deploy some related changes to our back end.
