### ISSUE TITLE
SCC Report Summary page

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2631]
## Background
The SCC report has recently been streamlined and a lengthy intro section has been replaced by a short summary page. This ticket aims to save time for Admins by automating some of the content; the rest will require manual population.

## User Story
As an Admin, I would like the SCC summary page to be auto-populated where possible so that I can save time.

## Feature(s) Description

- [ ] Create a Word download as per the format attached
- [ ] Auto-populate the fields according to [this Miro board](https://miro.com/app/board/uXjVL8_J9Js=/?share_link_id=21951296007)
- [ ] Add a new link to the Reports menu as below

<img width="1661" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3IrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38966634e867c0aac65b5b1d6b88f2a73f9822fb/image.png" alt="image.png" />
[SCC Summary page.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHIrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6cde520a6d70b0820dde1c4523422fc61e7e125/SCC%20Summary%20page.docx)

## Acceptance Criteria
It's done when Admins can produce an SCC summary page at the click of a button.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2631?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle @KoWeiJAC

**Comment by HalcyonJAC** [comment]
https://github.com/user-attachments/assets/08b8ce44-52c4-468c-a81c-aab5f9c1195e
