### ISSUE TITLE
Export function for the diversity report

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#264]
The teams will need to share the diversity outside of the JAC so they need an ability to export the diversity report at each stage of the exercises.  This can be shared with Commissioners or partners in the appointments process.

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC should this feature be:
**1. An export**
  e.g. a PDF document that can be downloaded and shared with anyone, with no tracking
_or_
**2. A share** 
  e.g. a page within the app that invited users can log in and see

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle There are two needs here.  I am happy that as a starting point the page is within the app and users can log in and see it.  

However there will be points that a copy of the diversity form will need to be shared with Commissioners and other stakeholders so it would be helpful to have a PDF download at various points.

**Comment by warrensearle** [comment]
Ok, for now I think the best way forward is to make sure we have printer-friendly css styles set up.

This will mean that on any page the user can use their browser's Print command to obtain a print/pdf ready page.

Lots of modern computers & devices enable PDFs to be created when printing. If our Admin users do not have this capability available to them then we can offer an 'Export PDF' button on this and other pages.

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC are you happy with the approach outlined above

**Comment by ClaireTroughtonJAC** [comment]
> 
> 
> @ClaireTroughtonJAC are you happy with the approach outlined above?

Thanks @warrensearle I am content
