### ISSUE TITLE
Create flags which appear to indicate a candidate may not be eligible

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#267]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to see a flag attached to each candidate where there may be an issue with their eligibility. For example if somebody does not have the requisite citizenship a flag would appear which tells me as an admin that there is an eligibility issue. There would also be an accompanying explanation by the flag such as 'Citizenship'. 

Other eligibility flags would includes PQE (post-qualification experience), and reasonable length of service. 

**Describe the solution you'd like**
Update the firebase function that flags up candidates.

**Additional context**
This spreadsheet outlines how the Eligibility logic is calculated and how the candidates are flagged.
https://docs.google.com/spreadsheets/d/1Qi_-fX8As1GfGtxKDryZw5TwfjyKxKDW9NYy1bbs6C0/edit#gid=0

**Comment by warrensearle** [comment]
This has the following dependency:
- [ ] Need to activate the firebase function to flag applications

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle @YaaL please let me know if this provides sufficient clarity.
