### ISSUE TITLE
SPIKE: Search. Choose most suitable tech stack

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#269]
In order to enable admin to search for candidates and applications we need to consider the most suitable tech stack to use.

Firestore does not support full-text search so either we live without it (e.g. we could offer 'starts with' searches) or we consider using a search service such as ElasticSearch or Algolia.

See firestore documentation for more information:
https://firebase.google.com/docs/firestore/solutions/search

**Comment by crablab** [comment]
All of these solutions have the disadvantage that they are another platform we have to maintain (ie. it's not part of Firebase). 

[**Algolia** ](https://www.algolia.com/products/search/)

Algolia is a SaaS search API which you just integrate with. 

- Pricing: starting at $29/month, PAYG. Enterprise plans are available - not sure how many queries we're looking at. 
- There is a bit of an art to transforming data to pipe it into Algolia. I don't think this will present a huge issue given the current structure of our data, but it's something to bear in mind. We'll definitely want to exclude most fields which won't be relevant for searching by. [More details...](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/prepare-data-in-depth/)
- We can separate out the different running environments by either using separate apps in Algolia, or different indices within the same app. The former provides direct isolation, the latter you provide isolation by restricting API key privileges. The former would require multiple subscriptions for each application, thus environment. 

[**Elastic Search**](https://www.elastic.co/app-search/)

Elastic App Search would seem to be the most appropriate product - it is available as a PaaS option [here](https://www.elastic.co/app-search/service). You index some data and then can search it, using the ES API. 

It appears to be available on GCP [here](https://console.cloud.google.com/marketplace/product/endpoints/elasticsearch-service.gcpmarketplace.elastic.co)

- Pricing: calculator [here](https://cloud.elastic.co/pricing)
- We'd might need to manage our own ES nodes running on GCP. This adds additional maintenance complexity in setting up, managing and updating these nodes. 
- It is possible to use a "managed" PaaS option if you do it through the Elastic Cloud. But this is then another billing platform and place where infrastructure lives. 
-  If we run our own nodes on GCP, it does mean that all the indexed data is held on our platform:so potentially more secure, and better assurance about where the data is. 
- I think we'd need to run a separate set of instances for each environment (dev, staging, production)

**Comment by crablab** [comment]
We should probably consider this too: https://www.ncsc.gov.uk/collection/saas-security/saas-security-principles

**Comment by warrensearle** [comment]
Closing this issue.
We are using 'starts with' style searches as these are supported by firestore and we expect will be sufficient for the actual search requirements.
