### ISSUE TITLE
New page:  Interview preferences

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#271]
**Is your feature request related to a problem? Please describe.**
We need to create a new page using the "Working preferences" page as a template 

**Describe the solution you'd like**
The teams need the ability to add and title bespoke questions about interview preferences .
with an add another option not just one question and choose the type of list - single, multiple and ranking.  

- The ability to add a title 
- The ability to add a question about dates the candidates are unavailable for interview.  This could include blocks of interviews i.e Preston 1-15 March, Newcastle 15-18 June etc 
- a text area to record those dates.
- The ability to add several bespoke questions with checkbox answers about the location of the interviews they'd prefer (these can be single or multiple options)
- The ability to add about wording about whether a location can be guaranteed
- The ability to add  text prompting candidates to contact the team if they have any additional info/queries to provide about their venue prefs.

**Describe alternatives you've considered**
Collecting the information later and being able to re-open applications for candidates to submit new information at later stages of the exercise.  Ideally we want the candidates to self select their interview date via a booking system.  

**Additional context**
We have a large exercise for disabled members of a tribunal.  There are a number of factors including their own accessibility that the team need to prepare for in terms of location.  It would be good to know that up front so that they can get arrangements in place. 

Links to apply#196

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC please double check which issue on apply this is related to as #197 doesn't seem to exist

**Comment by warrensearle** [comment]
Scratch that, got it it's apply#196

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC lets discuss this. Would the team like to ask open questions where the candidate will see a question and corresponding textarea? Or will all questions have set answers the candidate chooses from?

**Comment by ClaireTroughtonJAC** [comment]
> 
> 
> @ClaireTroughtonJAC lets discuss this. Would the team like to ask open questions where the candidate will see a question and corresponding textarea? Or will all questions have set answers the candidate chooses from?

Hi @warrensearle getting some feedback from the teams on your questions then we can discuss.

**Comment by ClaireTroughtonJAC** [comment]
Hi @warrensearle I have received feedback from the teams and amended the ticket accordingly.  I hope its clear but we can discuss again.

**Comment by Rebecca-mcknight1991** [comment]
@ClaireTroughtonJAC potentially not needed. To discuss.
