### ISSUE TITLE
The application form for 00011 needs to be able to allow the candidate to fully explain why they meet the Additional Selection Criteria

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#280]
https://admin.judicialappointments.digital/exercises/EMZEoUTXaqhUBvvrPEyv/

**Is your feature request related to a problem? Please describe.**

The non-legal team need to be able to assess a candidates Additional Selection Criteria and present the application form does not allow sufficient flexibility to be able to do this. 

**Describe the solution you'd like**
The text within the Statutory Eligibility box needs to be formatted.

There needs to be three boxes under the heading of additional criteria:
i) statutory eligbility critera 
ii) Additional selection criteria where the Welsh speaking requirement is addressed, with an associated yes/no field placed underneath for applicants’ response.
iii) Additional information

**Describe alternatives you've considered**

If the boxes cannot be added the last three could be put into one box but the titles will need to be formatted in bold and a yes/no field incorporated.

**Additional context**

**Comment by warrensearle** [comment]
Hey @Rebecca-mcknight1991 or @ClaireTroughtonJAC please can we discuss what is needed here. It's not quite clear to me yet.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle ticket #198 is a similar ticket - does that one make more sense?

**Comment by warrensearle** [comment]
Hey @Rebecca-mcknight1991 both tickets are valid:
- admin#280 to cover the required changes to Admin
- apply#198 to cover the required changes to Apply
It's just that they're not quite clear yet - I think it's best to talk through the requirements then we can refine the tickets together.
