### ISSUE TITLE
Ability to tailor the Welsh Questions on each exercise

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#284]
Monika when she starts

**Is your feature request related to a problem? Please describe.**
I am always frustrated when I can't adapt the help text for the welsh questions because the standard text is not relevant to my exercise

**Describe the solution you'd like**
I want to be able to 
1) indicate if I want to include any text
2) If I do want to, I need a space to add the text to be displayed to the candidate
3) I want the option to add an additional text box and/or 
4) I want the option to just ask a question with a yes/no response.  

**Describe alternatives you've considered**
Adding the question to the additional selection criteria but it is currently limited to only two options.  This is not sufficient for Welsh questions as well

**Additional context**
For exercise 00005 this caused issues and meant we needed last minute fixes.  It would be helpful to all exercises to have this function.

**Comment by Rebecca-mcknight1991** [comment]
Related to Linked to #198

**Comment by Rebecca-mcknight1991** [comment]
Will delete this story and create new story for admin to be able to add new functionality which is customising the application form by adding yes/no question, long text box and short text box with questions of their. choice.
