### ISSUE TITLE
View eligibility report

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#286]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to have a print-friendly version of the eligibility information that I can print to put into papers and share with colleagues. 

**Describe the solution you'd like**
A table with the eligibility information displayed which can be printed as word document or PDF. 

The report needs to show the:  
- application reference
- applicant name
- why they were flagged - PQE, RSL or Citizenship 
- the calculation of the PQE on the back end displayed as day months and years
- Any mitigation provided for Reasonable length of service where candidate has clicked "No"
- What Citizenship they have declared under "Other"

An example of this is as below:
![Screenshot 2020-03-10 at 11.22.59.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/0906bb58-501c-4264-9cfd-73ff192c5389)

**Describe alternatives you've considered**
An on-screen display that can be exported to share with Commissioners.  
Add the ability to export the document.  

Giving access to external stakeholders however this has the potential for information security breaches.  

**Additional context**
When creating the flag and display for #267 the need for this will need to be taken into account. The way in which the report displays will need to be printer friendly.

**Comment by Rebecca-mcknight1991** [comment]
Does not include the drop downs that will be a separate task.

**Comment by warrensearle** [comment]
Hi @ClaireTroughtonJAC looking at the example report above, how should we handle an application having being flagged up with more than one eligibility issue? 

e.g. the candidate fails Reasonable Length of Service and also Citizenship. 

Should each of these issues have a Recommendation dropdown to Proceed, Reject, Discuss... or should there be just one Recommendation dropdown covering all issues?

**Comment by ClaireTroughtonJAC** [comment]
Hi @warrensearle thanks for this I would like each of the issues to have the Proceed, etc.  That way if we export this to an electronic document the issues for discussion would be clearer.

**Comment by ClaireTroughtonJAC** [comment]
From @warrensearle 
Implementing the dropdown actions is in another ticket…. so when we get to it we’ll consider handling multiple issues
