### ISSUE TITLE
Change  the default name for "candidate assessment" on Admin

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#298]
**Is your feature request related to a problem? Please describe.**
In the exercise download page the "candidate assessment" is coded as "null.doc"  This is causing confusion.  

**Describe the solution you'd like**
Please can "null" change to "candidate assessment.doc"

**Additional context**
![Screenshot 2020-02-20 at 09.50.22.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/18080e4a-d81b-45a0-8540-4e759b1186a8)

**Comment by YaaL** [comment]
Deprecated with #372
