### ISSUE TITLE
Change to summary title on Application view page

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#302]
**Is your feature request related to a problem? Please describe.**
In the diversity information candidates answer the following question: Gender is the same as sex assigned at birth: Yes. 

On the admin side on the application view it shows as Changed Gender: Yes. This will probably lead to confusion so they need to match. 

**Describe the solution you'd like**
Amend the "Changed Gender" label to "Gender same as birth"

**Additional context**
Can't add screen shot for Information Security reasons.

**Comment by Rebecca-mcknight1991** [comment]
This might involve changing our database field name.

**Comment by YaaL** [comment]
@Rebecca-mcknight1991 As of #258 the title is no longer generated from field name.

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC or @Rebecca-mcknight1991 please can you verify that this is still an issue, since we have the new application view?
