### ISSUE TITLE
Need to allow candidates to download templates on mobile devices 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#305]
**Describe the bug**
Candidates are unable to download templates, such as self assessments, on an iphone. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to to JAC website on iphone
2. Click on Vacancies
3. Apply for any exercise 
4. Go to uploads section
5. Download the template
6. Nothing happens

**Expected behaviour**
The template would appear and the candidate could save it or begin typing into it. 

**Smartphone (please complete the following information):**
 - iphone 6, iphone XR, Nokia 
 - Browser mobile Safari

**Comment by ClaireTroughtonJAC** [comment]
@YaaL I have tested the download template functions on my iphone but as you can see from the screenshot from my phone the link to download the template is inactive.  I have PDF, Word and google docs installed on my phone. 

Please see screenshots below.  

![IMG_4194](https://user-images.githubusercontent.com/27224574/77333486-67b9dd00-6d1b-11ea-85e8-c0b828bc6862.PNG)

Additionally I tried to see if this was a global issue with the download link and I also got it on my laptop too - where the link to download is inactive.
<img width="750" alt="Screenshot 2020-03-23 at 14 20 39" src="https://user-images.githubusercontent.com/27224574/77333580-8f10aa00-6d1b-11ea-8ada-f987586fb4f2.png">
