### ISSUE TITLE
The spelling of disciplinary needs to be correct on the Character page 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#309]
**Describe the bug**
From the team: 'I know this is a very small thing - I just wanted to check that we had used the correct spelling of Disciplinary'.

It is currently Diciplinary - the C should be an S. 

**Expected behavior**
Should be 'Disciplinary

**Screenshots**
image.png 
image.png

**Additional context**

**Comment by YaaL** [comment]
@warrensearle we have this typo all over the place!

**Comment by YaaL** [comment]
BTW shouldn't this live in apply?

**Comment by warrensearle** [comment]
@YaaL oh dear I can see that, even in variable names!
Let's address the low impact changes as part of this ticket and create a log / seperate ticket for any variable name changes. Other issues will lead to variable name changes, so I think it makes sense to approach them in one batch.

**Comment by warrensearle** [comment]
Issue moved to [jac-uk/apply #250](https://github.com/jac-uk/apply/issues/250) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Rebecca-mcknight1991** [comment]
![image.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/4d288b65-fc3f-49fc-9cda-024b3424a02c)
