### ISSUE TITLE
Admin should be able to send a request for Independent Assessment (references) 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#318]
**Is your feature request related to a problem? Please describe.**
As part of the application process candidates have to nominate an independent assessor or referee who will write an assessment about the candidate. The admin needs to be able to send a request to all the assessors at once with a link for them to complete an assessment. 

**Describe the solution you'd like**

The admin goes onto the platform at the stage they want to send the Independent Assessments. They then can either: 
(i) Select and individual candidate record and press a button that says 'send independent assessment requests'
(ii) Bulk select candidates, probably be a tick box, and press a button that says 'send independent assessment requests' 

The request email template is on Notify (contact information for assessors is pulled from the application) and needs to:

- be secure, nobody other the specific assessor should be able to access the link or see the candidate name 
- it should be address to the assessor by name
- it should contain the exercise name 
- it should contain the candidate name 
- guidance for what they are assessing the candidate against e.g. a link to the competency framework
- due date for the assessment 
- a link to write it 
- contact information 

https://www.notifications.service.gov.uk/services/0abe6c8e-0b87-4cde-9493-5da4921ccc53/templates/37093b3e-3743-45bb-b2d6-9e8465d97944

**Describe alternatives you've considered**
Google drive currently used but there some problems when the assessment are actually written with exporting for large exercises. 

**Additional context**
Nothing further.

**Comment by warrensearle** [comment]
@YaaL lets discuss this task. I've been working on the data model and cloud functions for sending IA requests & reminders.

**Comment by warrensearle** [comment]
The following cloud function should be used for sending a request to assessors:

`sendAssessmentRequests`

An object containing the following data should be provided as a single parameter:
- `exerciseId` (required) ID of exercise
- `assessmentId` (optional) ID of an assessment
- `assessmentIds` (optional) array of assessment IDs
- `resend` (optional) boolean if true sends to 'pending' assessments as well as 'draft'


**Example: send a request for a specific assessment** 
```
sendAssessmentRequests({
  exerciseId: 'exercise123',
  assessmentId: 'assessment56',
})
```

**Example: send assessment requests for a selection of assessments** 
```
sendAssessmentRequests({
  exerciseId: 'exercise123',
  assessmentIds: ['assessment1', 'assessment5', 'assessment56'],
})
```

**Example: send assessment requests for all assessments in an exercise** 
```
sendAssessmentRequests({
  exerciseId: 'exercise123',
  resend: true,
})
```

**Example: send or resend assessment requests for a selection of assessments** 
```
sendAssessmentRequests({
  exerciseId: 'exercise123',
  assessmentIds: ['assessment1', 'assessment5', 'assessment56'],
  resend: true,
})
```
