### ISSUE TITLE
Admin needs to be able to send email reminders to Assessors

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#320]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to send reminder emails to Assessors where the Independent Assessment is outstanding. 

**Describe the solution you'd like**
Issue #319 gives a solution for monitoring returns. It is suggested there would be a way from this table to:
1. Filter out assessments which are completed only leaving the outstanding ones
2. Select all the candidates remaining 
3. Send a bulk reminder email to their assessors 
4. Alternatively click send reminder on a specific candidate 

See mock up below (purple buttons) 

![Screenshot 2020-03-10 at 15.43.23.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/984dcba2-2bc0-4123-b191-20bcefac1a21)

**Describe alternatives you've considered**
Google drive but there is not an easy way to monitor and send reminders from here. 

**Additional context**
Nothing else.

**Comment by warrensearle** [comment]
The following cloud function should be used for sending a request to assessors:

`sendAssessmentReminders`

An object containing the following data should be provided as a single parameter:
- `exerciseId` (required) ID of exercise
- `assessmentId` (optional) ID of an assessment
- `assessmentIds` (optional) array of assessment IDs


**Example: send a reminder for a specific assessment** 
```
sendAssessmentReminders({
  exerciseId: 'exercise123',
  assessmentId: 'assessment56',
})
```

**Example: send assessment reminder for a selection of assessments** 
```
sendAssessmentReminders({
  exerciseId: 'exercise123',
  assessmentIds: ['assessment1', 'assessment5', 'assessment56'],
})
```

**Example: send assessment reminders for all assessments in an exercise** 
```
sendAssessmentReminders({
  exerciseId: 'exercise123',
})
```
