### ISSUE TITLE
Admin needs to be able to resend Assessor requests 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#321]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to resend Independent Assessment request emails to Assessors. 

**Describe the solution you'd like**
Issue #319 gives a solution for monitoring returns. It is suggested there would be a way from this table to resent Independent Assessment emails: 
1. Either by bulk (tick relevant candidates and send) or
2. Individually by clicking resend 

See mock up below (purple buttons) 

![Screenshot 2020-03-10 at 15.43.23.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/984dcba2-2bc0-4123-b191-20bcefac1a21)

**Describe alternatives you've considered**
Notify but it would take too long to resend one by one. 

**Additional context**
Nothing else.

**Comment by warrensearle** [comment]
The following cloud function should be used for sending a request to assessors:

`sendAssessmentReminders`

An object containing the following data should be provided as a single parameter:
- `exerciseId` (required) ID of exercise
- `assessmentId` (optional) ID of an assessment
- `assessmentIds` (optional) array of assessment IDs


**Example: send a reminder for a specific assessment** 
```
sendAssessmentReminders({
  exerciseId: 'exercise123',
  assessmentId: 'assessment56',
})
```

**Example: send assessment reminder for a selection of assessments** 
```
sendAssessmentReminders({
  exerciseId: 'exercise123',
  assessmentIds: ['assessment1', 'assessment5', 'assessment56'],
})
```

**Example: send assessment reminders for all assessments in an exercise** 
```
sendAssessmentReminders({
  exerciseId: 'exercise123',
})
```
