### ISSUE TITLE
Enable unit tests as part of CI pipeline

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#336]
- [x] Update CircleCI config to include a job to run unit tests and add to relevant workflows
- [x] Exclude 'old' tests using `xdescribe`

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle Is there any testing I need to do for this?

**Comment by warrensearle** [comment]
Thanks @ClaireTroughtonJAC no there's no user testing required for this one. The tech team reviewed among ourselves. Have move to Released.
