### ISSUE TITLE
Diversity report shows data for each exercise stage

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#356]
**Is your feature request related to a problem? Please describe.**
I need to be able to see diversity information at each stage of exercise processing.

**Describe the solution you'd like**
The current dashboard but it shows the numbers at each exercise stage. 

**Describe alternatives you've considered**
Some kind of export but this is more efficient. 

**Additional context**

**Comment by warrensearle** [comment]
A few refinements to the Diversity report:
- [ ] Include 'Last refreshed' date near the Refresh button
- [ ] Include 'Summary' tab containing text 'Summary coming soon' as a placeholder for future comparison/summary data
- [ ] Include 'Export data' button on each tab 
- [ ] Include 'Export all data' at the top of the report
