### ISSUE TITLE
A filter function on the diversity dashboard 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#358]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to filter candidates in the diversity dashboard depending on whether they have passed or failed each stage. The automated view should only have the candidates who have passed. If possible there could be filters for looking at specific target groups like women or BAME candidates. 

**Describe the solution you'd like**
An option in the dashboard headings to click the heading and then filter. Probably a tick box or something similar to excel filters as staff are used to this.

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC can we move this to phase 2?
