### ISSUE TITLE
Ability for admin to switch between restricted panel view and full application

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#360]
**Is your feature request related to a problem? Please describe.**
Exercise teams need to see a modified application view with reference number OR the full application with all information. 

**Describe the solution you'd like** (goes in order of application except personal details at the top)

One view should include everything

One view should NOT include:

personal details,
equality and diversity
character information
location preferences
jurisdictional preferences
interview preferences (new ticket)
The information should be grouped by the pages the information is stored. i.e all judicial experience should be together in one section.

**Describe alternatives you've considered**
A download that the teams could amend if necessary.

**Additional context**
Ultimately this view should be exportable

Linked to ticket #258

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle @YaaL does this summarise the need. This is the ticket linked to #258. If so please let us know estimate and we will move to Ready to Play.

**Comment by warrensearle** [comment]
Perfect, thanks @Rebecca-mcknight1991. Let's put this down as an estimated 2 story points for the following reasons:
- 41 + 2 = 43 story points, which is another prime number
- the sister story is a 5 so a total of 7 points feels about right
@YaaL that sound agreeable to you?

**Comment by YaaL** [comment]
@Rebecca-mcknight1991 @warrensearle 
Looks fine to me.
