### ISSUE TITLE
Problem uploading templates

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#372]
**Describe the bug**
When I go to upload the self-assessment template it does not appear to the candidate for downloading. It also does not appear on the admin summary page. 

**To Reproduce**
1. Go to staging 
2. Click on JAC00258 (testingtesting) and unlock the exercise 
3. Scroll down to exercise downloads
4. Update downloads
5. Replace the candidate assessment with the attached doc [https://app.zenhub.com/files/201485031/a0ffbd9a-0446-4a83-bcc6-5acd7b1a708a/download](https://app.zenhub.com/files/201485031/a0ffbd9a-0446-4a83-bcc6-5acd7b1a708a/download)
6. Save and continue 
7. Approve and publish from the exercise homepage
8. Go to candidate staging
9. Apply for the exercise
10. Go to 4. Assessment 'self-assessment competencies'
11. You will not be able to download the template

**Expected behavior**
The template should be like a hyperlink for the candidate to download. It should also appear on admin summary page. 

**Screenshots**
![Screenshot 2020-03-31 at 14.08.32.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/1f241241-ef46-4468-ad44-5a3dbc586afa)

![Screenshot 2020-03-31 at 14.08.39.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/5c36c145-9bd8-42b5-881d-b3116ea906cd)

![Screenshot 2020-03-31 at 14.05.15.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/218206d4-557c-44b9-aaae-c72be6a31078)

**Desktop (please complete the following information):**
 - iOs
 - Chrome

**Additional context**
Urgent as impacting an exercise that launched on production today (00009)

**Comment by YaaL** [comment]
It looks like only the "job descriptions" section is wired in to upload files but the candidate app expects templates from the other sections to exist.
@warrensearle do you know why it might be like this?

@ClaireTroughtonJAC - not sure how the uploads are actually supposed to work, could you explain?

**Comment by Rebecca-mcknight1991** [comment]
- [ ] Allowing for multiple uploads on the exercise download page on admin. This is multiple downloads for each separate type of file with titles for each. 

- [ ] Add two additional upload fields in admin download page: 1) Pensions Notes and 2) Competency Framework. Again ability to upload multiple documents with titles for both of these. 

- [ ] Enable admin to see what they have uploaded on this page and the summary page. 

- [ ] The following should appear on the overview page to the right under 'Related Content': Job Description, Terms and Conditions, Competency Framework, Pensions Note.
![Screenshot 2020-04-02 at 11.08.38.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/45799741-fb3e-48dd-b7c3-f7dd666b133c)

- [ ] The documents under 'Candidate assessment' on admin should be visible on apply to the candidate on the assessments page of the application form. Please note this links to whatever assessment option is chosen in 'Assessment options' on admin e.g. it will **not** appear if statement of eligibility OR nothing is chosen but **will appear for all other options** e.g. 'self-assessment' 
![Screenshot 2020-04-02 at 11.11.33.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/13629750-68cb-4e37-8aa4-7b8298cbce56)

- [ ] For document/s on independent assessors these will appear on Related Content when Independent Assessment are requested (dates in timeline). They will also be linked in the Independent Assessment request email (ticket #318).

**Comment by Rebecca-mcknight1991** [comment]
@YaaL updated with checklist.
