### ISSUE TITLE
Update user roles once all created 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#385]
**Is your feature request related to a problem? Please describe.**
As an organisation the JAC needs everyone to have the correct user role so they have the relevant access to the platform. 

**Describe the solution you'd like**

1. All on Apply to be given candidate status before Independent Assessments start getting collected on the platform. 
2. Initially Super Admin to have the ability to change user roles and add users with their relevant roles. 
3. Claire and Becky will go through and assign all Manager and Admin roles.
4. Manager then to be given the ability to add all types of users **except** super admin and we will then ask them to add Commissioners and Panel Members. 

**Describe alternatives you've considered**
Not applicable. 

**Additional context**
None. 

https://docs.google.com/spreadsheets/d/1hkI1vlIC89AII4MgiK9qYtAXRoa27bCOM9Ric1oWdSQ/edit#gid=634165532

**Comment by warrensearle** [comment]
Note. This will be a one-time set up of user roles.
We will provide a spreadsheet of JAC users which should then be completed with a corresponding role for each user.
We will then import this and ensure users roles are updated.

Further changes and administration of users will be via the admin tool.

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC and @Rebecca-mcknight1991 spreadsheets of the staff users on Staging and Production have been shared with you. Please populate the 'role' column and comment here when you're done.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle is this not the same as refreshing user's token?

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 no this is a bulk update to populate all users with their assigned role
