### ISSUE TITLE
Save exercise open and close time in database

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#389]
**Actual**
We are currently storing date only in our database

**Expected**
We should store date plus time in our database. The time should always be 13:00.

Notes
- Currently we always open/close exercises at the same time of 13:00. This may be customisable in future, but not needed here.
- We should use a single field in our database to store the date and time data (timestamp data type).
- We should pay particular attention to timezone and daylight saving to ensure we are 100% confident in correctness of stored timestamp.

**Comment by YaaL** [comment]
@Rebecca-mcknight1991 not done, we still need it

**Comment by warrensearle** [comment]
We now have a form component that handles date and time, so this should be quite a quick one. The problem with hard-coded times raised it's head again during QTs MVP #404 therefore have marked this as high priority.

In Apply there are a few FIXME comments where the time has been hardcoded as 13:00 so we should tidy this up when this ticket has been implemented.

**Note** that the data in existing exercises will need updating to include the time.

**Comment by lloback** [comment]
This was fixed on the issue #860 .

Checked on:

- [ ] EXERCISE TIMELINE: date as timestamp ADD / EDIT
- [ ] VACANCIES - date as timestamp, except `estimatedLaunchDate`
