### ISSUE TITLE
Add new fields for diversity in contacts CSV

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#398]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to see more information relating to diversity in the contacts CSV download. I need this so I can send a complete set of data to the diversity officer to get clearance to my next stage of an exercise. 

**Describe the solution you'd like**
The following fields need to be added to the contacts CSV:

- [x] 'Professional background" 
- [x] 'Attended UK state school' 
- [x] 'First generation to attend University'

**Describe alternatives you've considered**
The full diversity report but this is a complex piece of work and this is needed more urgently. The teams can calculate the numbers and percentages for now. 

**Additional context**
Nothing further.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle if there is any possibility of this being done by Monday evening that would be great. Thanks.

**Comment by warrensearle** [comment]
Sure thing
