### ISSUE TITLE
SPIKE: Combined exercises and QT

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#405]
New workflows for exercises included combining to related exercises and providing data separately.  Also a workflow with a QT that then separates into separate exercises

**Comment by crablab** [comment]
Current QTs:
- Situational Judgment (1 part)
- Critical Analysis and Situational Judgment (2 part)
- Scenario 

The tests have the following input methods:
- Situational Judgement: statement with 4 possible options, choice between "Most appropriate" and "Least appropriate" 
![screenshot_2020-07-29-131041.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/d95c7c83-3c21-41ee-ba8e-df12b3781485)
- Critical Analysis: question/statement with 4 radio button choises
![screenshot_2020-07-29-131206.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/797ad221-91a8-44d1-854c-710a591efca7) 
- Scenario: textual statement plus a number of long form text responses. 
![screenshot_2020-07-29-131345.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/7a570738-4d0d-46de-979e-bf4b23baa32a)

**Comment by crablab** [comment]
As discussed with Becky, some of the issues are:
- No timer 
- No word count on long form responses
- Formatting is removed when copying from Word to the Google Form 

There are a few potential solutions. 

## Embedded Google Form
- Allows us to solve the timer issue fairly quickly and can be implemented for all QTs, at once. 
- Might look/behave a bit jankily when iframed within the platform 
- Relies on correct use/sharing of the Google Forms (which is an issue at the moment) 
- Doesn't solve word count or formatting issues 
- Results are still off platform 

## Document upload for scenario QTs
(Nb. as an aside from whatever happens with the other QTs)
- Allows unlimited formatting in Word (do we really want that?)
- Timer can be displayed on platform, but not visible when candidates are working in Word
- Requires downloading each file to mark, as opposed to viewing responses directly in the platform (as with a text field)

## Form generation, displaying and submission for QTs on platform 
- Most complete solution 
- Timer and word count possible 
- Resolves issues with Google Form creation and sharing
- More restrictive options available when creating a QT
- Doesn't necessarily fix formatting issues
- Complex

**Comment by crablab** [comment]
https://moj-design-system.herokuapp.com/components/rich-text-editor
