### ISSUE TITLE
Ability for Admin and Manager to add notes to candidates history

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#417]
Ability to add notes about candidates for consideration by other teams in other exercise ie

Recent checks
Specific issues candidate has raised - short terms issues or bereavements etc

Limited to specific points to note be aware.  Separate functionality for outcomes for character and eligibility

**Comment by KateMJAC** [comment]
Functionality exists on the platform to create a notes about a particular candidate. 

Other tickets cover the seperate functionality for character and eligibilty outcomes to be recorded. 

This Epic can be closed.
