### ISSUE TITLE
SPIKE: optimise loading external CSS

### ISSUE THREAD

**Issue by YaaL** [jac-uk/admin#426]
We're currently loading **all** CSS for every component. That's suboptimal because we end up with huge files with tons of duplicated CSS.

Turns out just moving `@import "@/styles/main.scss";` from `/vue.config.js` to `/src/App.vue` is not enough if we want to be able to use variables/mixins from `govuk-frontend`.

Let's find a working solution.

**Comment by warrensearle** [comment]
@lloback have assigned this to you. Speak to @YaaL or @warrensearle as and when you have questions

**Comment by HalcyonJAC** [comment]
Through experimentation we found that upgrading the `sass-loader` package resulted in a faster compile time, however it also requires some `vue` packages to be upgraded, so they are compatible with the newer version of SASS. 

So, basically the 'slow complile time' problem is potentially resolvable but has a wider impact on the rest of the system - upgrading Vue will likely incur breaking changes and will certainly require the system to be back-tested broadly.

**Comment by warrensearle** [comment]
Closing as this has been fixed in Admin and a similar change will be rolled out to Apply & Assessments
