### ISSUE TITLE
Create exercise stages 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#436]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to move candidates through the stages of an exercise. 

**Describe the solution you'd like**
For this I need the following stages to be created:

- Review
- Shortlisted
- Selected 
- Recommended
- Handover 

**Additional context**
![Screenshot 2020-05-14 at 10.46.29.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/728c5f92-795d-4bd4-ab7d-9af977d53381)

**Comment by lloback** [comment]
This is done.

**Comment by warrensearle** [comment]
Just need to include the numbers.

**Comment by lloback** [comment]
what numbers?
