### ISSUE TITLE
Create candidate statuses for Shortlisting stage 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#438]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to update the status of a candidate to move them through the stages of an exercise. This will enable the statisticians to see the journey of each applicant, the team to track their progress, and diversity to be collated at various stages. Anyone viewing the exercise from admin will be able to clearly see what stage each applicant is in but also why (from the status). 

The first stage I will need to do this is in the Shortlisting stage of an exercise. 

**Describe the solution you'd like**
The following statuses need to be created for the shortlisting stage of an exercise:

- Invited to selection day
- Rejected as ineligible
- Withdrew application

**Additional context**
https://docs.google.com/spreadsheets/d/1S6qpdM5DchujfNT0v0wUfpnVijtwor8sTcu44oB8E9A/edit?usp=sharing

![Screenshot 2020-05-14 at 10.59.28.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/64d736bc-4037-4c77-a89c-56f41b03bcc1)

**Comment by lloback** [comment]
This is done.
