### ISSUE TITLE
Create candidate statuses for Selected stage

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#439]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to update the status of a candidate to move them through the stages of an exercise. This will enable the statisticians to see the journey of each applicant, the team to track their progress, and diversity to be collated at various stages. Anyone viewing the exercise from admin will be able to clearly see what stage each applicant is in but also why (from the status). 

The first stage I will need to do this is in the Selected stage of an exercise. 

**Describe the solution you'd like**
The following statuses need to be created for the selection stage of an exercise:

- Passed Selection
- Failed Selection
- Passed but not recommended

**Additional context**
https://docs.google.com/spreadsheets/d/1S6qpdM5DchujfNT0v0wUfpnVijtwor8sTcu44oB8E9A/edit?usp=sharing

![Screenshot 2020-05-14 at 11.02.23.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/72e67cd1-52f5-44ae-8928-a7bab46e79f7)

Sub-tasks:
- [x] Wireframe (new files and mock data)
- [x] Link data list to `firebase`
- [x] Link data options statuses to `firebase`
- [x] Submit the form
- [x] update data on firebase

**Comment by lloback** [comment]
This is wireframed with mock data.

[] Wireframe (new files and mock data)
[] Link data list to `firebase`
[] Link data options statuses to `firebase`
[] Submit the form
[] update data on firebase

**Comment by lloback** [comment]
This is done.
