### ISSUE TITLE
Create candidate statuses for Recommended stage

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#440]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to update the status of a candidate to move them through the stages of an exercise. This will enable the statisticians to see the journey of each applicant, the team to track their progress, and diversity to be collated at various stages. Anyone viewing the exercise from admin will be able to clearly see what stage each applicant is in but also why (from the status). 

The first stage I will need to do this is in the Recommended stage of an exercise. 

**Describe the solution you'd like**
The following statuses need to be created for the Recommended stage of an exercise:

- Rejected by character
- Rejected as ineligible
- Approved for immediate appointment
- Approved for future appointment
- SCC to reconsider
- Withdrew application

**Additional context**

https://docs.google.com/spreadsheets/d/1S6qpdM5DchujfNT0v0wUfpnVijtwor8sTcu44oB8E9A/edit?usp=sharing

![Screenshot 2020-05-14 at 11.05.38.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/ffb5b259-0bdb-491b-834c-233dc2a02de5)

**Comment by lloback** [comment]
This is done.
