### ISSUE TITLE
Update statuses of candidates with tick box: individually, bulk and select all function

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#443]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to update the statuses of candidates to move them through the stages. Sometimes this will be selecting all (e.g. to review stage), sometimes an individual, and sometimes multiple individuals or bulk update. 

**Describe the solution you'd like**
A tick box to appear to the left of the candidates which I can tick once, multiple times, or select all if I click the box to the left of reference number. 

I will then click the green set status button to update the statuses. 

**Additional context**

Individual tick

![Screenshot 2020-05-14 at 11.30.39.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/0c06a487-1305-4ebc-9a45-b08817f752c8)

Select all

![Screenshot 2020-05-14 at 11.30.32.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/a1dab1be-561f-4f4f-b3d5-0d8198a9335d)

Select multiple/bulk 

![Screenshot 2020-05-14 at 11.30.25.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/d680dc19-7a74-4010-a23c-293d41d8a3ce)

**Comment by warrensearle** [comment]
This ticket should be covered by the work happening on our new Table component: #430

**Comment by warrensearle** [comment]
In the short term, until we have the Table component, the following should help:
https://stackoverflow.com/questions/33571382/check-all-checkboxes-vuejs

**Comment by lloback** [comment]
- [ ] Review
- [ ] Shortlisted
- [ ] Selected
- [ ] Recommended
- [ ] Handover

**Comment by lloback** [comment]
This is implemented. PR to be reviewed and merged.
