### ISSUE TITLE
 Connecting statuses and stages so the candidates appear in the correct list

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#451]
**Is your feature request related to a problem? Please describe.**
As an admin when I select a status update I need to move the candidate to the correct stage. This will sometimes have a dependency for example if there is a sift but another stage set up after in the candidate record the journey will be different for the candidate. 

**Describe the solution you'd like**
The candidate to either remain in the current stage where they don't progress or move into the next one. 

**Additional context**
This spreadsheet outlines the stages, statuses, where the candidate should go and whether there are any dependencies. 

https://docs.google.com/spreadsheets/d/1S6qpdM5DchujfNT0v0wUfpnVijtwor8sTcu44oB8E9A/edit?usp=sharing

**Comment by warrensearle** [comment]
This is mostly done.
We have a couple of TODOs in our stores which will need to be completed, across all stores:
- [ ] Display available statuses based upon exercise configuration
- [ ] Move to next stage based upon exercise configuration

**Comment by lloback** [comment]
![image.png](https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/a999dde3-34c5-49ba-a615-2d70e3b66a31)

This is the table for testing the scenarios

**Comment by lloback** [comment]
This task is done.

![image.png](https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/91651c8a-05dd-4457-a9f2-0e0487d12689)

We introduced a "Move to the next stage" on the REVIEW tab in order to bypass some limitations in choosing the next stage. This can be clarified and a new task raised for this.
