### ISSUE TITLE
Banner heading when a status is updated 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#452]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to have a confirmation a candidate's status has been updated and an indication of where they have gone as result of that update. 

**Describe the solution you'd like**
When the candidate/s is/are moved a green banner comes up at the top confirming the stage they have moved to. This will appear for all candidates where multiple candidates (see screen shots at the bottom). 

UX want the green banner message to disappear when the user leaves this page but came back to it again. It will not disappear after X seconds. So if the exercise manager decided to update the status for another candidate, then they would not see that previous banner message. 

**Additional context**
See: [MOJ Design System component](https://moj-design-system.herokuapp.com/components/banner)

![banner-alert.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/c98f43fa-c945-46b0-8fd9-6f51f4857aa8)

![bulk-banner-alert (wecompress.com).png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/d0807f0d-b32d-499e-aba3-756c14231883)

**Comment by warrensearle** [comment]
Hey @tomlovesgithub can you and @GabMat97 look to create a new component for this.
No need to worry about show/hide or there being multiple messages as that will be taken care of by the parent page that uses this component.

**Comment by lloback** [comment]
The solution implemented was not exactly the one asked here:

![image](https://user-images.githubusercontent.com/15261814/83531071-69a2d800-a4e4-11ea-93c9-a3cd213e3679.png)

@Rebecca-mcknight1991 @ClaireTroughtonJAC If you are not happy with this solution for now (on MVP), please raise a new ticket and we can address this at a later stage. Also, please review the text.
