### ISSUE TITLE
Add issues column to all Stages lists

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#454]
Add a new column to all stages lists to indicate whether the candidate has eligibility or character issues.

Display static text "Yes" is the candidate is flagged as having issues and "No" if they aren't flagged as having issues.

**Note:** ticket #464 covers making the "Yes" text into links, so doesn't need to be handled here.

![Screenshot 2020-05-18 at 13.17.27.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/00701d19-adec-49ae-ad9e-d00b0da5c729)

**Comment by warrensearle** [comment]
@warrensearle this can be broken down into the following:
- [ ] Add issues column to all lists
- [ ] Add warning when trying to move into Handover @ClaireTroughtonJAC  please confirm
- [ ] Link to issues section of application view (blocked by that piece of work)

**Comment by lloback** [comment]
- [ ] REVIEW
- [ ] SHORTLISTED
- [ ] SELECTED
- [ ] RECOMMENDED
- [ ] HANDOVER

**Comment by lloback** [comment]
This is done. Moving to Ready for release.
