### ISSUE TITLE
Issues column should link to issues section of application view

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#464]
When an application has unresolved issues a "Yes" shows in the Issues column on all stages lists.
Currently this is static text.
This needs to be amended to be a clickable link to the issues section of the Application View page.

![Screenshot 2020-05-18 at 13.17.27.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/00701d19-adec-49ae-ad9e-d00b0da5c729)

**Comment by lloback** [comment]
@Rebecca-mcknight1991 @ClaireTroughtonJAC May I have an example of a link, please?

**Comment by lloback** [comment]
The page is built in the prototype.
Here is a link to the page where issues will be
https://jac-admin-prototype.herokuapp.com/current/view-reports/issues/#eligibility

This is the link to where it will sit in the candidate's application record
https://jac-admin-prototype.herokuapp.com/current/view-reports/issues/applied-jac00105-abc0001
