### ISSUE TITLE
Add `js-enabled` to body tag when our app loads

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#482]
Some of the styling from Gov Design System is dependent  upon the existence of `js-enabled` class being added to, say, our main body tag.

As part of the load of our app let's set this class.

Also we can make use of it when ensuring we have sufficient user experience for non js-enabled browsers.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle do we need this?

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub do we still need this? Love Warren.

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub do we still need this?
