### ISSUE TITLE
Merit List 

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#491]
Panellists grade candidates and display the results at both the shortlisting and selection stages. These results are currently stored off platform on a spreadsheet. 

We need a single source of truth when it comes to candidate grades and a way to reduce errors during data entry and processing. 

We need to explore what is technically possible on the platform and whether a simple upload of the existing spreadsheet onto the platform will be suitable, or whether it is possible to have panel members enter grades directly onto the platform via a newly created UI workflow. 

We have merit list at different stages of the exercise;
[ ]Merit list at sift day- shortlisting
[ ]Merit list at selection days
[ ] Ability to create many panels e.g panel 1,2 , 3
[ ] daily score sheet Template
[ ] Merit list Template
[ ] Report Template
[ ] Moderation control Template
[ ] Moderate 10% to 12% of candidates per exercises. 
[ ] Large exercise with more panellist moderate 30% of candidates.

Example form two panels.
[ ] Daily score sheet for panellist - consist of Panel Chair, Judicial member and independent member used the daily score sheet.
[ ] The panel chair is responsible to update the daily score sheet.
[ ] Panel chair write the report at the end of sift.
[ ] Panel chair should only access their candidates details
[ ] Panel chair to have moderation Control Template for moderation day
[ ] Panel chair to update the moderation control template 
[ ] Create access for Assign commissioner
[ ] Panellist to only have access to their daily score sheet.
[ ] Panellist cannot access each other daily score sheet
[ ] Panellist should be generated a link to access only the candidates that they will be sifting/shortlisting on the day. 
[ ] Ability to lock the daily score sheet at the end of the day.
[ ] Panellist cannot update the daily score sheet once scores have been entered on previous day.

Moderation
[ ]Candidate for moderation are identified by the Teams, Panels, range of grades, background, solicitors, barristers, BAME, Females. The Selection exercise teams agrees with policy on moderation.
[ ] Create a sheet for each of the candidates that follows in the above categories with their original grades.
[ ] Panel 1 and Panel 2 are allocated each other candidates moderation sheets each with their reports like peer review.
[ ] Panel meets with the original candidates panel to decide on candidates grades.
[ ] Panel makes changes on the moderation control sheet.
[ ]  Ability to reflected the changes on the moderation control  sheets to appear on the overall Merit list.

"EPIC - Merit list
panellists: 
 - create panellists app
 - collection of daily scores for sift and selection day
 - collection of scenario scores
 - present scenario responses
admin: 
 - manage panellists
 - configure panels
 - live merit list report
 - configure scenario panels
 - update live merit list report with scenarios
 - scenario report & update application status" 

"EPIC - Merit list
panellists: 
 - support for ranking
 - support for calibration
 - support for moderation
admin: 
 - support for ranking
 - support for calibration
 - support for moderation" 

Links to the templates https://drive.google.com/drive/folders/1p7vtfwDXtgMqKmL2vj7v32vQrKnyZ0FJ

**Comment by andrew-isaac** [comment]
@warrensearle  - What is the update with this work? Why is it blocked?

**Comment by warrensearle** [comment]
Closing as this has been superseded by #1861
