### ISSUE TITLE
Ensure when you click the candidate name a page opens with the record

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#511]
**Is your feature request related to a problem? Please describe.**
As an admin I want to see the candidate record and application history when I click the candidate name. 

**Describe the solution you'd like**
Candidate names are hyperlinked and open the record corresponding to that candidate when clicked. 

**Additional context**

Click the page
This opens
![Screenshot 2020-05-29 at 14.40.36.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/e16f9c58-49d8-466f-98bf-1447b1ce36ec)

Speak to Enor about the prototype for more information on Design.

**Comment by lloback** [comment]
Applications

- [ ] Draft
- [ ] Applied
- [ ] Withdrawn

Stages

- [ ] Review
- [ ] Shortlisted
- [ ] Selected
- [ ] Recommended
- [ ] Handover
