### ISSUE TITLE
Candidate record creation

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#512]
**Is your feature request related to a problem? Please describe.**
As an admin I want to see a candidate record. 

**Describe the solution you'd like**
A candidate record for each candidate to be created as per the prototypes. 

This candidate record shows the following information:

**The name at the top of the screen**

**A link to view applications history - see ticket number #516**

**Personal Details**

[x] - Email Address
[x] - Phone Number
[x] - National Insurance Number 

**Diversity**

[x] - Ethnic Group
[x] - Gender
[x] - Disability
[x] - Professional Background
[x] - Fee-paid Judicial Role 

**Issues**
- Character
This gives the Dates and what the declarations were for any character issues. 
- Eligibility
This lists the eligibility issue e.g. citizenship 

**Notes about the candidate**

[x] Contains any notes written by staff regarding the candidate e.g. SCC outcomes, email address changes etc. The notes will show here and there is an ability to add a note, edit or delete see ticket number ticket #513  #514 and #515. 

**Describe alternatives you've considered**
Not having a record but we need this across the organisation to be able to see a summary of information about candidates. It is crucial for phone conversations and statistical and policy objectives. 

**Additional context**

![Screenshot 2020-05-29 at 14.40.36.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/fe69f1e3-ebbd-49b4-9ebf-68e1797fcd6d)![Screenshot 2020-05-29 at 14.40.43.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/7be986bf-32c7-42c1-bd5d-5c9de9e890f1)
![Screenshot 2020-05-29 at 14.47.00.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/3f5d252b-7569-4b7c-b6cd-cf578d65ff2b)

**Comment by lloback** [comment]
This needs to be reviewed as the bulk of the work is already done.
