### ISSUE TITLE
Give ability to add note to candidate record

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#515]
**Is your feature request related to a problem? Please describe.**
As an admin I often need to be able to add notes about a candidate such as key updates and issues or SCC decisions. 

**Describe the solution you'd like**
An option in the candidate record to 'Add a note' and then input a date, the note itself and save. These should appear at the bottom of the record. 

**Describe alternatives you've considered**
No notes function but it is useful to track any changes and issues with a candidate. The ability to put SCC decision notes was a request from Secretariat.

**Additional context**
![Screenshot 2020-06-01 at 08.07.45.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/797e7682-aa7c-4e88-8bf7-3bc2541c0d5d)

![Screenshot 2020-06-01 at 08.07.39.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/6a5d67cc-dcee-46ff-afc7-2dc3b0f1aeb6)

**Comment by lloback** [comment]
This is developed.
