### ISSUE TITLE
Different tabs for different agencies on admin

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#520]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to see a report with the character agency information divided up by the relevant agencies. 

**Describe the solution you'd like**
A new report on the left hand side menu - 'Agency'. And the report divided up into the different character agency organisations e.g. BSB, SRA, ACRO.

**Additional context**

![Screenshot 2020-06-01 at 11.52.47.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/e4745f83-6c7a-456d-8fda-c7c74eec2c0e)

![Screenshot 2020-06-01 at 11.52.43.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/16607b66-674a-460c-99b6-430e33406a31)

**Comment by Rebecca-mcknight1991** [comment]
@YaaL looking good and happy for this to be released but there are a couple of typos that I'll create a separate ticket for but these don't prevent release.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle when you go into the SRA and BSB tab it says the name in full but these need a tweak. 

SRA says Solicitor Regulation Authority
It should be **Solicitors** Regulation Authority 

BSB says Bar Standard Board
It should be Bar **Standards** Board

Thanks

**Comment by warrensearle** [comment]
These have been done now, as part of release 0.19.0.
