### ISSUE TITLE
Each tab populated with the information candidates input

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#521]
**Is your feature request related to a problem? Please describe.**
As an admin I need to see each tab in the agency report populated with the information the character completes on Apply in the consent form. 

**Describe the solution you'd like**
The relevant information comes up in a table form under each tab. 

**Additional context**
![Screenshot 2020-06-01 at 11.52.43.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/88697035-dfc5-4ca8-b3f3-348bc16d8a9b)

![Screenshot 2020-06-01 at 11.57.04.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/704254c6-cae1-4b75-be8d-d003fd8f480c)

![Screenshot 2020-06-01 at 11.57.08.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/40e0ff79-55e4-4bd6-afa9-7f9f4dc1c7c1)

![Screenshot 2020-06-01 at 11.57.12.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/03bb2510-82b6-4559-bd33-aad944888480)

![Screenshot 2020-06-01 at 11.57.16.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/a6c1c4f2-ae44-4c5a-808f-3d992fbc9544)

![Screenshot 2020-06-01 at 11.57.21.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/f9ad84c4-8989-4b6e-9116-110956b94c60)

**Comment by YaaL** [comment]
Part of #520 really
