### ISSUE TITLE
Information exportable in excel file

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#522]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to export the character agency report so I can email it to the relevant agencies via Notify. 

**Describe the solution you'd like**
An export to xls option. 

**Additional context**
![Screenshot 2020-06-01 at 11.59.43.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/0fd73775-0934-4727-8c2e-4b37e73e9e32)

**Comment by crablab** [comment]
@Rebecca-mcknight1991 Would a .csv (which will open in Excel fine) be okay here? It's the same format that is used elsewhere in the application.

**Comment by Rebecca-mcknight1991** [comment]
@crablab yes a .csv would work fine :) Thanks.

**Comment by crablab** [comment]
https://jac-admin-prototype.herokuapp.com/current/view-reports/agency/
