### ISSUE TITLE
Review the progression from review stage

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#537]
![image](https://user-images.githubusercontent.com/15261814/83527351-97d1e900-a4df-11ea-9a7d-d06a8342bf5d.png)

**Describe the bug**
We introduced a "Move to next stage" step on the REVIEW tab in order to bypass some limitations in choosing the next stage from REVIEW. This can be clarified and a solution proposed:

Solution A:
Leave as it is and close this task. This means that you are happy with the proposed solution - happy with Solution A. 

Solution B:
Automate the process and create some business rules to move to the next stage depeneding on some conditions. The challenge with this one is that we don't have a predefined list of steps that needs to be fulfilled in order to move to the next step, and we don't keep record of the steps that the user have taken. We need to think thoroughly about how we want to do this.

**Additional context**
This is a follow up from task #451

**Comment by Rebecca-mcknight1991** [comment]
@lloback happy with Solution A.

**Comment by lloback** [comment]
AS per @Rebecca-mcknight1991 I am closing this task.
