### ISSUE TITLE
Ensure Table component displays well on small screens

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#543]
See #430 for more details.

Ensure Table component displays well on small screens

Perhaps simply support hiding some columns on small screens and look at Vuetify's [Data Table](https://vuetifyjs.com/en/components/data-tables/) to see how they implement expandable rows

**Comment by KateMJAC** [comment]
During review, established that table component displays need to be implemented for views listed in #430

**Comment by KateMJAC** [comment]
Table component has been tested successfully on views that are accessible on mobiles. 

Tested across different exercises' exercises stages, independet assessments, drafts, applications and QTs.
