### ISSUE TITLE
Application view displays 'Invalid Date' for created

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#595]
**Expected**
Show the date

**Actual**
Shows 'Invalid Date'
See screen grab
![Screenshot 2020-06-16 at 12.08.07.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/a3a237b0-0fde-4b95-8308-3f53b4f830b3)

**Example:**
https://admin.judicialappointments.digital/exercises/EMZEoUTXaqhUBvvrPEyv/application/6cbBRLaGsz12g8BexXar

**Comment by crablab** [comment]
@warrensearle Apologies, looks like I forgot to follow up on this one. 

In some cases there is a data issue which means there isn't a date to display. So the question is really what should we display when we don't have a date to display? 

I would suggest something like "Unknown". It only impacts a small number of past records.

**Comment by warrensearle** [comment]
Hey @crablab I'm happy with your proposed solution. Let's go with it.
@ClaireTroughtonJAC and @Rebecca-mcknight1991 can suggest a text change, if necessary, when reviewing this fix.

**Comment by crablab** [comment]
Awesome! PR coming :soon:

**Comment by YaaL** [comment]
This now works as expected.

There is however an underlying issue with the data - `createdAt` is stored as a Unix timestamp instead of Firebase Timestamp object.

**Comment by crablab** [comment]
@warrensearle There is a separate issue for this now open: https://github.com/jac-uk/digital-platform/issues/331
