### ISSUE TITLE
Post Qualification Experience information missing from panel packs 

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#611]
**Describe the bug**
There seems to be an issue generating panel packs - the "post qualification experience" section of the candidates application appears to disappeared from the full application and panel pack view on the platform and more importantly the download.  Exercise JAC00029 are in the process of creating their packs. 

**To Reproduce**
1. Go to JAC00029
2. Click on either applied or reviewed
3. Select a candidate - in the full information view or panel pack you will see there is no "post qualification experience" section
4. Also when you "download as PDF" the information is not appearing.  

**Expected behavior**
The whole experience section including judicial experience should be included.  I have checked other exercises and the information 
**Screenshots**
![Screenshot 2020-06-17 at 12.18.53.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/c4b455ff-ac80-4664-9228-3472689879d6)appears to be showing in the export and on screen
From the full information view. 

![Screenshot 2020-06-17 at 12.20.55.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/6fc5df55-374a-4d55-b9cd-e705b513885d)
Panel view 

Example PDF download
[https://app.zenhub.com/files/201485031/89c06b91-1780-4111-bc2a-fe78208c2411/download](https://app.zenhub.com/files/201485031/89c06b91-1780-4111-bc2a-fe78208c2411/download)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC JAC00029 is a 'Leadership' exercise and right now the experience and post-qualification experience sections are coded to only show for 'non-legal' and 'legal' exercises....

I believe the logic should be:
- if 'legal' or 'leadership' show Post-qualification experience section
- if 'non-legal' or 'leadership-non-legal' show Experience section

Please can you confirm if that is correct?

**Comment by ClaireTroughtonJAC** [comment]
Hi @warrensearle bad semantics on my part.  You are right its not showing the post qualification experience I'll amend the ticket.  Your logic is absolutely spot on.
