### ISSUE TITLE
Unable to mark application as applied if in draft 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#628]
**Describe the bug**
When I go to mark an application as applied that is in draft I cannot do so because there is not a reference number to click. 

**To Reproduce**
1. Go to any open exercise 
2. Click on drafts
3. Attempt to go into an application so you can mark as applied 
4. Unable to do so 

**Expected behavior**
We need a way to go into a draft application and force it into applied. The staff need to be able to see what has been completed by that applicant so far and then press the normal mark as applied button. 

I spoke about this with Warren and he suggested a number might be generated for draft or it says something like 'has not applied' but you follow the link as with an applied one and then the mark as applied button appears.

**Comment by lloback** [comment]
this is done.
