### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#641]
**Describe the bug**
Update de dependencies

**Expected behavior**
After the update everything should work, so a monitoring of the app should be held.

**Comment by HalcyonJAC** [comment]
I spoke to @warrensearle and we came up with the following plan:

- [x] Upgrade existing dependancies (where upgrades do not incur breaking changes)
- [x] Setup Snyk (to get an initial list of vulnarabilities)
- [ ] Setup Dependabot in GitHub (to get alerts about dependancy upgrades in future)
- [ ] Setup GitHub Code Scanning (to scan the JAC's own code for vulnerabilities)
- [ ] Disable Snyk (once all of the above has been done)
