### ISSUE TITLE
Handover: Ability to add "email to JO" button

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#671]
**Is your feature request related to a problem? Please describe.**
When the Handover report is created it needs to be emailed to the appointments team.  It would be helpful if there could be a button that would allow admins to send the information via the platform directly.   

**Describe the solution you'd like**
Along with a download function (see ticket #665) an additional button to send an email to the Judicial Office (JO) so that once the download has been checked the email can be sent immediately. 

We will need to attach the full report as set out in ticket #665 in the email.  Notify has this capability

Please see link to Notify https://docs.notifications.service.gov.uk/node.html#error-codes for more information

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle will this be needed once we go ahead with the work we are doing with JO?

**Comment by Rebecca-mcknight1991** [comment]
Note for @warrensearle and @Rebecca-mcknight1991. Once we know we are going ahead with JO plan this can be deleted. But may need as back up plan.

**Comment by KateMJAC** [comment]
As we are progressing with the automated transfer this ticket can be closed, as Becky's comments above.
