### ISSUE TITLE
Edit Citizenship on Application and Candidate Details

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#682]
On task #659 we allowed admins to edit some details.
This task is created to provision the changes for the Citizenship.

The information for this task will be the same as the apply: Some countries and 'other'.
Changes on the Candidate page and application.

https://admin-develop.judicialappointments.digital/exercises/wdpALbyICL7ZxxN5AQt8/application/testData-10
![image](https://user-images.githubusercontent.com/15261814/87785318-e3dab200-c82f-11ea-938e-51ae90cdbd0f.png)

https://admin-develop.judicialappointments.digital/candidates/KnTFmjXqtDchIKLGuwkTC5Om4982
![image](https://user-images.githubusercontent.com/15261814/87785420-0a005200-c830-11ea-8249-f1437a75a842.png)

**Comment by KateMJAC** [comment]
To be reviewed as part of the May application and profile edit items on the RM.
