### ISSUE TITLE
Edit Reasonable ADJUSTMENTS on Application and Candidates pages

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#683]
We allowed admins to change the Personal Details of candidates on the task #659 .

We need to allow for the change to Reasonable Adjustments (2 different fields on the database).
This is a change on the EditableField Component in order to add this edge case.

https://admin-develop.judicialappointments.digital/candidates/KnTFmjXqtDchIKLGuwkTC5Om4982
![image](https://user-images.githubusercontent.com/15261814/87785914-f2759900-c830-11ea-9781-899717935cbe.png)

https://admin-develop.judicialappointments.digital/exercises/wdpALbyICL7ZxxN5AQt8/application/testData-10
![image](https://user-images.githubusercontent.com/15261814/87786007-1c2ec000-c831-11ea-9226-59d98804777a.png)

**Comment by KateMJAC** [comment]
To be reviewed as part of the May application and profile edit items on the RM.

**Comment by KateMJAC** [comment]
To be reviewed as part of the May application and profile edit items on the RM.

**Comment by KateMJAC** [comment]
PR for this ticket is covered by #682.
