### ISSUE TITLE
Independent Assessment uploads not showing 028 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#696]
**Describe the bug**
When you click on Independent Assessments for 00028 you cannot see which ones have been uploaded. 

**To Reproduce**
1. Go to admin
2. Click on 00028
3. Scroll down to Independent Assessments 

**This appears to be the same for EVERY exercise which has used the platform for IAs**

**Expected behavior**
Should see the list of assessors and pending assessments, completed one and an option to download them.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle this is closed right?

**Comment by warrensearle** [comment]
Ah yes, sorry, the work has been done under #697, which is a duplicate of this ticket. Will close.
