### ISSUE TITLE
Download panel pack in word doc 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#700]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I download a panel pack in PDF and cannot edit it. The JAC cannot get a licence for everyone so I have to spend hours editing the PDF in word. 

**Describe the solution you'd like**
I would like to be able to download the panel pack in a word document.

**Describe alternatives you've considered**
Waiting off for panellist app development or keeping PDF. Problem with latter is we cannot get a licence for everyone and although waiting for panellist app would have been ideal we need to do more ground work for this. There is an immediate need for these to be easier to having a word download is a good fix.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle there we go :) Will leave to you for estimate and assignee.

**Comment by warrensearle** [comment]
Great, thanks @Rebecca-mcknight1991.
Am discussing with @tomlovesgithub now so we'll estimate and get cracking.

Would like to re-iterate that we're treating this as a 'quick fix' whilst we work up a Panelist App and move towards going paperless.

**Comment by warrensearle** [comment]
This might be useful: https://phppot.com/javascript/how-to-export-html-to-word-document-with-javascript/

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle thanks Warren. I'll add the tickets about downloads but this is definitely slower time.
