### ISSUE TITLE
/candidates is showing IDs not names

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#703]
It appears we are showing the ID of the candidates not their names in the production version of admin. This does not seem to exist in develop/staging. 

![Screenshot from 2020-07-24 15-31-16](https://user-images.githubusercontent.com/5859718/88406401-8d89e800-cdc8-11ea-9985-18b713995aae.png)

Searching for a common name doesn't find anything, so I don't think it's a data issue with some records. 

@warrensearle do you have any ideas before I go down a rabbit hole?

**Comment by tomlovesgithub** [comment]
Have looked into the 🕳🐇.

Good news is that the line of code in particular is doing exactly as its asked
`{{ row.fullName | showAlternative(row.id) }}`

[Looking at Develop](https://console.firebase.google.com/u/1/project/digital-platform-develop/database/firestore/data~2Fcandidates~2Fj8KP4CNLZ6aifdNNfnVSgTUPeu32)
- It appears any account created after the 16th June is appearing as the candidate ID, and looking at firebase the data models are reflecting this. 
(The candidate object is literally just `{ "created": "2020-07-28T15:16:55.691Z" }` )
- I have tested this by creating a new candidate account on apply.

[Looking at staging](https://console.firebase.google.com/u/1/project/digital-platform-staging/database/firestore/data~2Fcandidates~2FeHyWaEwdLGZs5DyD8nQgH7iiwps1)
- We have a very similar situation all candidates after a certain time are just a created value 

[Looking at production](https://console.firebase.google.com/u/1/project/platform-production-9207d/database/firestore/data~2Fcandidates~2F20cePC8a3YVCrd2V18T5ua8etaD3)
- **ALL** candidates are appearing as just a created date

Initially I thought this was quite a bad prognosis, however after spending some time marinating in the data, and looking across the environments, and some head scratching have reassured me all is not lost, although the data structure appears to have evolved at a certain point and some have been left behind.

I cant work out if the personalDetails are attached to candidates or to the applications. 
Either way the desired data can be found on the candidate view page, and the most recently created (? i think ?) candidate will show on the candidate list under 
`{{ this.$store.state.candidates.personalDetails }}`

Happy to continue working on this issue, although i might need some guidance on how the `row` prop inside the <template> on candidatesList is being populated, as this seems integral to the issue.

**Comment by crablab** [comment]
`personalDetails` should be attached to both. They are duplicated across and Lee has some code that controls whether changes to the main profile reflect on an application, or changes to the personal details within the application reflect on the main profile. 

@warrensearle I think this might be cause by us having different versions of cloud functions running in different environments. Please could you investigate this :smile:

**Comment by warrensearle** [comment]
This will be resolved by the following tickets:
digital-platform#289
digital-platform#293
