### ISSUE TITLE
Add Copy to clipboard button to application view

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#704]
Add a 'Copy to clipboard' button on application view.

This is another quick fix to help the teams put panel packs together whilst we consider options for exporting panel packs vs building a panel panel pack viewer.

There are many resources on line for this including the following tutorial which might be useful:
https://www.30secondsofcode.org/blog/s/copy-text-to-clipboard-with-javascript

**Comment by ClaireTroughtonJAC** [comment]
@tomlovesgithub @YaaL @warrensearle This looks fantastic.  My only reservation is that in the downloads and the copy functions, the hyperlinks to "change" fields (like assessors information) are showing when you open the documents.  Please can this be removed.

**Comment by ClaireTroughtonJAC** [comment]
@tomlovesgithub @warrensearle I have reviewed the update.  One small thing that I am sorry I didn't pick up before but in the download can we also remove the email addresses for the IAs.  Otherwise this is fantastic and good to go.

**Comment by warrensearle** [comment]
Hi @ClaireTroughtonJAC as the email address is being removed for IAs should the phone number be removed too?
