### ISSUE TITLE
Add warning component 

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#718]
Add the gov.uk warning component: 
![screenshot_2020-07-30-133028](https://user-images.githubusercontent.com/5859718/88922980-e0e8b400-d268-11ea-825c-7ebfd7269598.png)

```html
<div class="govuk-warning-text">
  <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
  <strong class="govuk-warning-text__text">
    <span class="govuk-warning-text__assistive">Warning</span>
    You can be fined up to £5,000 if you do not register.
  </strong>
</div>
```

https://design-system.service.gov.uk/components/warning-text/

**Comment by ClaireTroughtonJAC** [comment]
HI @crablab I am testing this.  I am supposed to see the exclamation mark or just this.
<img width="637" alt="Screenshot 2020-08-03 at 16 33 32" src="https://user-images.githubusercontent.com/27224574/89199866-1eba4500-d5a7-11ea-8f33-03302d2921b5.png">

**Comment by crablab** [comment]
@ClaireTroughtonJAC Nope! This is a separate component - it's not actually used in admin :see_no_evil:  

It's in here because admin is currently the 'source of truth' for components we use in apply and assessments. It's one of the issues we have with code in multiple repos. 

This is used in another assessment ticket (https://github.com/jac-uk/assessments/pull/58#issuecomment-667919490)
