### ISSUE TITLE
Refactor pagination component 

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#738]
At the moment the pagination component is used with some (duplicated) helper code and data is paged on the front end. Firestore doesn't support pagination in quite the way we want to do it, and so we'll need to make a few changes to the component so that it can natively support the paging of data in Firestore. 

- [ ] Abstract reused frontend helper logic from individual pages in to helper functions 
- [ ] Modify component to only show page numbers when we know start/end limit
- [ ] Modify component to not require an end limit 
- [ ] Modify component to emit forward/back events instead of page number events, when we aren't tracking the page number

**Comment by warrensearle** [comment]
Closing this ticket as work has been superceded
