### ISSUE TITLE
Replace CSV exports with XLSX

### ISSUE THREAD

**Issue by YaaL** [jac-uk/admin#742]
- [x] contacts
- [x] diversity report
- [x] reasonable adjustments report

**Comment by ClaireTroughtonJAC** [comment]
@YaaL I have tested this but I got one error on the diversity stage export.  see screen shot.  If I recover its fine.  
![Error Excel Diversity Stage export](https://user-images.githubusercontent.com/27224574/89649923-70b9de00-d8b9-11ea-96a1-70b6e7ec407b.png)

I also got an error when I generated the reasonable adjustments export. 
![image](https://user-images.githubusercontent.com/27224574/89650096-c1313b80-d8b9-11ea-81fc-aa5e6a410db9.png)

**Comment by ClaireTroughtonJAC** [comment]
I believe this is an issue for MOJ laptops only.
