### ISSUE TITLE
QTs: start the initialised QT

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#761]
As an admin I want to be able to open my QT for candidates. 
As an admin I want candidates to know when the QT has been opened. 

--- 

This should be a button with a confirmation (as it's a permanent and high risk action). 

We may want to have a "Start QT" button which takes the user to a confirmation page. 

The key risks are: 
- This emails all the candidates to let them know the QT is open 
- It cannot be undone 

Once confirmed we should update the QT `status` field and trigger a function: https://github.com/jac-uk/digital-platform/issues/345

**Comment by warrensearle** [comment]
Moving to 'blocked' column whilst we decide whether this should be a start button, that needs to be pressed to activate the test, or a pause button that can be pressed to prevent the test from automatically activating

**Comment by warrensearle** [comment]
Have implemented the cloud function activateQualifyingTests. This works out of the box for manually starting the QT and can be adapted the work with a scheduled cloud task instead.
