### ISSUE TITLE
QTs: display aggregate values

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#764]
As an admin I want to see aggregate statistics about the QTs in progress. 

--- 

Ticket to aggregate the values: https://github.com/jac-uk/digital-platform/issues/346

We should show these values (number of candidates in the QT, number who have started, number who have finished) on the QT page whilst the QT is in progress. 

These are individually clickable and take you to the pages in #762

**Comment by warrensearle** [comment]
These will be displayed on the dashboard page. See #765
