### ISSUE TITLE
Configure database rules for qualifyingTestResponses

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#769]
We have a new collection called qualifyingTestResponses. These are candidate-specific and should only be editable by the relevant candidate and admin users.

- [x] Add initial rules and tests for qualifyingTestResponses collection
- [ ] Prevent candidate from updating any field apart from answers, started and completed
- [ ] Prevent candidate from updating answers before they've started
- [ ] Prevent candidate from updating answers after they've completed
- [ ] Prevent candidate from updating answers if their allowed duration has expired

**Comment by KateMJAC** [comment]
Marked as low priority in conversation with Warren and Joy. If not achievable, this can be included in a QT III iteration.
