### ISSUE TITLE
SPIKE: Export to google sheets

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#770]
When a qualifying test is completed admins will need to process the results data. For now this will be done outside of the admin tool. To facilitate this we will offer an 'Export to google sheets' function.

First we should investigate and decide whether to do this client-side or via a back-end cloud function.

>see
- Add 'Export to Excel' button to QT responses admin #801
- Add 'Export to Google Sheets' button to QT responses. See ticket admin #802
- Add 'Export to Google Sheets' cloud function See ticket  digital-platform #[64](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/assessments/64)

**Comment by tomlovesgithub** [comment]
Looking into solving this ive found a few solutions and backup plans.
The ideal solution would materialise as a UI button which would trigger a cloud function to export data from firebase to a google sheet document. 
*There is questions still to be answered about where to best securely store this file, and still allow it to be safely accessible by teams.*
Assuming we store a single document per test and use that file to show all test results, the best solution would be to create this sheet server-side with the google sheets API 
[Quickstart](https://developers.google.com/sheets/api/quickstart/nodejs)
[Create sheet](https://developers.google.com/sheets/api/guides/create)
Then populate this with data from firestore, perhaps running the function when the time window for a QT closes, then providing a link via the UI button.

Other less preferable solutions, include a few out of the box sheet/firebase syncing tools.
[one](https://gist.github.com/CodingDoug/ffc4f050cc489a0280eb7f4cbe36af07)
[firebase-own solution](https://github.com/firebase/functions-samples/tree/master/google-sheet-sync)
however these aren't ideal as they are syncing tools which will update a sheet as results change, which could be a useful tool for further requirements on QT's or a separate feature. 

Equally its worth investigating and testing all solutions, as if we did want synchronised behaviour we wouldn't want the sheet changing the DB

**Comment by warrensearle** [comment]
This is really useful research @tomlovesgithub. Let's move forward with the following tickets:

- Add 'Export to Excel' button to QT responses. This is our backup plan but will be quick to complete right away, plus may be useful for some users. See ticket TBC
- Add 'Export to Google Sheets' button to QT responses. This will call a cloud function so is just a button. See ticket TBC
- Add 'Export to Google Sheets' cloud function. This will be callable and also perhaps triggered by database events (e.g. a QT closing). See ticket TBC

**Comment by warrensearle** [comment]
Closing as the spike is done and follow up work has been ticketed, as above
