### ISSUE TITLE
Tidy up Qualifying Tests MVP

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#799]
Let's capture here a list of tidying / improvements to be made to the Qualifying Tests MVP.

- [x] Side navigation should indicate (highlight) when user is viewing Qualifying Tests pages
- [x] Add another button to go back on Test Review `qualifying-test/ddkfdld/review`
- [x] On Approval of the QT send back to the dashboard
- [x] ON the dashboard add a button to go directly to the REVIEW page of an edit question (so the user doesn't have to scroll all the questions before reaching the REVIEW page)
- [x] Add a 'remove' button for 'Add another' top level on QT edit page
- [x] Edit QT type? NOT NEEDED RIGHT NOW moved to #819
- [x] Delete QT (possible if draft)? NOT NEEDED RIGHT NOW #820

**Comment by warrensearle** [comment]
@tomlovesgithub @crablab @YaaL @lloback @warrensearle please add to the task list above

**Comment by lloback** [comment]
This is done.
