### ISSUE TITLE
QT SPIKE: Review the steps to initiate the QT

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#807]
There are a lot of buttons hanging on the Dashboard.
This ticket is to review the workflow of the creation/initialization/activation / etc ... for a test/

There are some buttons that should go together
There are some buttons that need to be disabled when some others are enabled
There are some button that should be hidden when some others are enabled / visible

![image](https://user-images.githubusercontent.com/15261814/91305940-bd4f5580-e7a3-11ea-8678-8ef43bf96996.png)

One suggestion was to have a task list with done
![image](https://user-images.githubusercontent.com/15261814/91306382-541c1200-e7a4-11ea-8b46-d2a0cf4379b3.png)

**Comment by Rebecca-mcknight1991** [comment]
@Rebecca-mcknight1991 look at when this can be done.
