### ISSUE TITLE
Start button component ( with arrow SVG )

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/admin#811]
the start button used across the project needs to be component-ized

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub is this still needed?

**Comment by KateMJAC** [comment]
@tomlovesgithub following-up on Becky's query above. Is this still needed?

**Comment by warrensearle** [comment]
Hi @KateMJAC this will be covered by work on the JAC Kit so has been superceeded. Therefore closing.
