### ISSUE TITLE
QTs: differentiate between DNF and completed

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#814]
When a candidate fails to hit the submit button but runs out of time (Did Not Finish), their responses so far are still valid and are still marked and scored. 

We need to show in admin when a candidate has failed to complete the test, but has run out of time. This is to help teams with marking and arranging resists.

**Comment by KateMJAC** [comment]
Hello @warrensearle this ticket makes a lot more sense after the 051 QT. When you get to it, please let me know and we can discuss.

**Comment by KateMJAC** [comment]
Hello @warrensearle this issue came into play during the 051 QT. It helps admins to know whether all answers are completed and there is an auto-submit because canidates didn't press submit or if the test wasn't completed before an auto-submit.

**Comment by KateMJAC** [comment]
Hello @lloback am I right in thinking that this work was not completed in QT pt II and is now to be swept up in QT pt III? I can see the ticket allocated to me in the 2021 and 2022 pipeline.
