### ISSUE TITLE
QT: "Answer not supplied" error on list of responses

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#821]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15261814/91456804-9cf2ca00-e87b-11ea-8f32-9528b85fc634.png)

**To Reproduce**
1. Go to Qulifying test response
I am not sure which of the status was clicked (as I was looking on other person computer)

**Expected behavior**
instead of "Answer not supplied" it should have the status (created, started, etc)

**Comment by crablab** [comment]
@lloback I can reproduce this. It's on either of the progress links (started/in progress).

**Comment by lloback** [comment]
So, to fix, may be we need to add the text `started`/`in progress` to the lookup

**Comment by crablab** [comment]
@lloback I will look at it as part of #814 :+1:
