### ISSUE TITLE
Refactor "Assessment Options" on Admin

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#843]
** Note this requirement has been temporarily satisfied in ticket #912, however we should still refactor the way we capture and store assessment options **

---

As a High Court Applicant
I want to be able to upload a covering letter with my application
So that I can fulfil the requirements for the role

---

For these exercise there needs to be an additional option to upload a covering letter. This change is required by **30 September**

- [ ] We need to refactor the assessment options (See below) into check boxes (more than one selection is possible)

- [ ] We need to add an additional option of "covering letter"

- [ ] We need to add logic to allow for one or more option to be chosen or unselected (ie User may want Self assessment and CV or statement of suitability, CV and covering letter)

- [ ] We need to check the logic with the displaying of pages in "apply"

- [ ] We need the "covering letter" option to have a corresponding page on "apply". see separate ticket

New options

Self Assessment with competencies
Self Assessment with skills and abilities
Statement of Suitability with competencies
Statement of Suitability with skills and abilities
Statement of eligibility
CV
Covering letter
None

**Comment by warrensearle** [comment]
Moved this ticket to the backlog as we have satisfied immediate requirements in ticket #912. This ticket is still valid as we should improve how we capture and store assessment options.
