### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#849]
As a statistician
I want to be able to extract pre-defined data from a number of exercises
So that I can complete further analysis

---

The statisticians need to complete an annual publication of data about our selection exercises. In order to do this they need an extract that contains specific data from fields across the application and exercise.  

They require

- The ability to select exercises from a list (and/or a date range)
- The ability to export data to a CSV in bulk

Here is the spreadsheet containing the requirements.  Each field or fields should be presented in a column and each candidates data supplied in a single row.  

[https://app.zenhub.com/files/201485031/48bbc241-370d-490b-b37a-315d1f8f69cf/download](https://app.zenhub.com/files/201485031/48bbc241-370d-490b-b37a-315d1f8f69cf/download)

---

The following groundwork needs to be completed before we can proceed:
- Admin. Use new Table component and server-side paging for all tabular lists
- Admin. Add filtering to Table component.
- ?Admin. Exercises should have a `stage` corresponding to the stage the processing has reached? TBC
- ?Admin. Approval process for stage completion and sending bulk emails? TBC

The following work is needed:
- Admin. Ability to filter, select exercises and download data. See #959
- Platform. Ensure we have data stored in correct places. See digital-platform#455
- Platform. Enable download of data for selected exercises. See digital-platform#456

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.
