### ISSUE TITLE
Tech Debt

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#862]
Epic for capturing tech debt tasks

**Comment by KateMJAC** [comment]
Hello @warrensearle, i'm guessing that a lot more tickets were meant to be linked to this epic? Given where we are at in terms of transitioning to call off contracts, is it okay to close this Epic?

**Comment by warrensearle** [comment]
Sure @KateMJAC, we haven't populated this epic so let's close it.

Let's arrange a session (or three) to compile a list / amalgamate other tickets so we get a clearer picture of what needs attention.
