### ISSUE TITLE
Amends to qualifying tests download

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#870]
- [x] Sheet name should be "CA" | "SJ" | "SC" followed by the date - e.g. "CA 17/09/2020"
- [x] Score column should be titled "CA Score" | "SJ Score" | "SC Score" 
- [x] Order by score desc
- [x] Format dates/times
- [x] Include the total time taken
- [x] Include score for each question
- [ ] ~Include diversity fields: ethnicity, gender, disabled, professional background~

**Comment by tomlovesgithub** [comment]
- What is 'score desc?' i have ordered by score
- How can i get access to the candidates array?

**Comment by warrensearle** [comment]
Hey @tomlovesgithub 

> What is 'score desc?' i have ordered by score

Great, by 'desc' I meant to order in descending order.

> How can i get access to the candidates array?
Please leave this one for now. I think we're gonna have to do this on the back end instead.

Can you include the scores for each question though

**Comment by warrensearle** [comment]
Hey @tomlovesgithub 
For the per question scores the data model is as follows:
```
questions: [
  response: {
    score: Number,
  }
]
```
See screen grab below from an example document
![Screenshot 2020-09-22 at 14.46.23.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/633557e1-6d3c-4c12-be1b-f1347eb55101)
