### ISSUE TITLE
Admin QT review: Update the status of the question on the fly

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#917]
**Is your feature request related to a problem? Please describe.**
As an admin I want to see when a user has seen a specific question. During a realization of a test some users have internet problems, others want to move to a mop up test. In order to assess this, as an admin we need to know if the user has seen the questions.

**Describe the solution you'd like**
This will be provided by a label STARTED / COMPLETED

![image](https://user-images.githubusercontent.com/15261814/94773615-0e122980-03b4-11eb-9ef0-9f773b13948c.png)

As an alternative we could use icons:
![image](https://user-images.githubusercontent.com/15261814/94774120-1b7be380-03b5-11eb-9c92-7250870672d5.png)

Or as simple as:
![image](https://user-images.githubusercontent.com/15261814/94774323-8d542d00-03b5-11eb-8809-6e0c9b8f6607.png)
![image](https://user-images.githubusercontent.com/15261814/94774333-96dd9500-03b5-11eb-9d0a-21a504879600.png)

**Comment by Rebecca-mcknight1991** [comment]
This is a great idea @lloback @warrensearle

**Comment by Rebecca-mcknight1991** [comment]
Moved to current sprint for now but lets discuss later today.
