### ISSUE TITLE
QT admin: adjust dashboard for users that Run out of time

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#918]
![image](https://user-images.githubusercontent.com/15261814/94778405-191d8780-03bd-11eb-8df4-92aeb34e3eb7.png)

Adjust the dashboard to account for DNF = Did not finish OR users that Run Out of Time.
These users are counted as IN PROGRESS, but they are not.

We need to find a way of accounting for those.

**Comment by Rebecca-mcknight1991** [comment]
@lloback @warrensearle Let's discuss this today. In current sprint for now.

**Comment by warrensearle** [comment]
As discussed with @lloback when a candidate runs out of time their response will be updated with the following flags:
- `status` to `'completed'`
- `isOutOfTime` set to `true`

**Comment by lloback** [comment]
![image.png](https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/2a0a3487-ea1a-43d2-8272-148419965245)

**Comment by lloback** [comment]
![image.png](https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/407edb03-4c2a-4c75-80ae-109e181073dd)

**Comment by lloback** [comment]
![image.png](https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/dac276b7-7400-48d0-82f2-43bb45e8c390)
