### ISSUE TITLE
Move to mop up should check for responses in the testQuestions field before emptying it

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#919]
When we move a qt response to another date we should check for responses that have been stored in the `testQuestions` field before we empty it. Responses were previously stored in `testQuestions` before we un-tangled them from the questions data and stored responses in their own `responses` field.

**Comment by lloback** [comment]
Please could you sanity check this locally to ensure:

- responses are not wiped
- responses in testQuestions are copied across to responses (iff responses is empty)
- anything else
