### ISSUE TITLE
Remote access to candidate account for admins

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#927]
**Is your feature request related to a problem? Please describe.**
As an admin it is frustrating to not be able to see issues a candidate is experiencing and change details from their profile. 

**Describe the solution you'd like**
A remote log in to candidate accounts. 
This would need to have a consent statement for the candidate to give them access. I imagine a bit like controlling the screen something pops up saying 'Do you give JAC Admin your consent in accessing your account'. 

**Describe alternatives you've considered**
Just admin changing details but this is a slightly more sophisticated solution. 

**Additional context**
Stemming from lots of requested to see candidate profiles, change info such as IAs and character.

**Comment by KateMJAC** [comment]
To be reviewed as part of the May application and profile edit items on the RM.
