### ISSUE TITLE
Capture cut-off score, number of spaces and update applications with pass or fail

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#933]
Admin users create qualifying test reports to work out which candidates should progress and which should not. This is primarily based upon how many candidates admins would like to progress (e.g. they may have capacity to only interview 50 candidates) and how well the candidates performed in the tests. 

A **cut-off score** is chosen. 
For example any candidate with 32 marks and higher might be progressed and anyone with 31 and lower would be excluded from progressing.

There may be some flexibility around the cut-off score whereby admins will select individual candidates to progress or not. In these situations the candidates may be flagged as having Equal Merit Provision applied.

**Further detail on how scores are calculated and candidates’ statuses updated**

For online tests with multiple parts (eg. qualifying tests or scenario tests), the average percentage score for each candidate is used to rank all candidates in order of merit, with the highest combined score as the most meritorious, and the lowest score as the least meritorious.

A candidate’s rank should be based on the average of the percentage achieved in each part of the test rather than an overall percentage. First, the candidate has their score for each part of the test converted into a percentage. Then the percentages are added, and a combined average score is calculated. e.g. QT1: 10/20 is 50%; QT2: 32/40 is 80% so the combined average score is 65% (50+80/2).

As an admin I would need to access output from the results, which displays scores for both parts of the test, as well as the combined average score. The combined average score is the most important figure to be displayed in a report, as this is the score used to rank candidates and establish a pass mark. 

As an admin I need to be able to set a pass mark (correct wording). A ‘Set pass mark’ button will update the status of all applications at that rank and above to the relevant/chosen Passed status and everyone else to the relevant/chosen Failed status.

While in the rank page(s) as an admin, I need to have the ability to select either one candidate or a group of candidates that are currently ranked below the pass mark and update their status as pass/fail. I also need to specify whether the EMP has been applied. 

When viewing the reports as an admin, I need to know whether a candidate chose not to provide their diversity data. This would require three display options under each protected characteristic column eg. Yes, no or not provided. 

Once the candidates are allocated a test status (pass/fail), as an admin I need the ability to push candidates through to the next stage of the exercise eg. Candidates that passed a scenario test need to be selected and status updated to ‘shortlisted’. 

---

The following has been implemented so far and is being reviewed with admin users to identify and agree what else is needed.

Select cut-off score (see green 'Set pass mark' button)
![Screenshot 2020-10-19 at 13.57.40.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/956122f8-0f26-46c5-9568-0e12a23610dd)

Select individual candidates (checkboxes and green 'Set status' button)
![Screenshot 2020-10-19 at 13.58.45.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/957242c2-3b24-41fc-aad0-be5da90e6294)

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 have moved this to Blocked whilst we gather feedback

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle think this can now move out of blocked?

**Comment by warrensearle** [comment]
Yes, we just need to document the feedback / what we need to do...

Which is:

- (for multiple tests) Rank should be based on average of the percentage achieved in each test rather than overall percentage:
  e.g. QT1: 10/20 is 50%; QT2: 32/40 is 80% so average percent is 65% (50+80/2) and overall percent is 70% (42/60)
- [ TBC ]

**Comment by KateMJAC** [comment]
Post discussion story points added to ticket. Please let me know if you require any further detail or clarification.

**Comment by warrensearle** [comment]
Thanks @KateMJAC looking great

**Comment by KateMJAC** [comment]
Discussed as part of the QT II epic today. It was agreed that this ticket was a priority to be included in April's work.

**Comment by KateMJAC** [comment]
Sent to UTG on 07/07/21. Update to follow.

**Comment by joy-ade** [comment]
@warrensearle Feedbacks from UTG the  set pass mark button is greyed out. Testers are unable to set mark

**Comment by joy-ade** [comment]
@HalcyonJAC positive feedback from UTG
