### ISSUE TITLE
Cannot update IA details

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#941]
**Describe the bug**
The text box does not appear when you go to change an independent assessors details so you cannot change it. 

**To Reproduce**
1. Go to 00033
2. Click on Applied, find Philip mantle, click app references
3. Scroll down to assessments and try to replace Clive emai

**Expected behavior**
A box should appear to type the email in and then you save and it updates.

**Screenshots**
![Screenshot 2020-10-07 at 18.11.26.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/519e75e7-50ea-470a-8251-9ed49856672b)

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub can you pop an estimate on this please.

**Comment by warrensearle** [comment]
Closing as this has now been resolved under another ticket
