### ISSUE TITLE
Ability for Admin to upload an Independent Assessment 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#960]
**Is your feature request related to a problem? Please describe.**
As an admin I want to be able to upload Independent Assessments from the admin side. 

**Describe the solution you'd like**
An upload button on the Independent Assessments Task area https://admin.judicialappointments.digital/exercises/D7vODO7AVyTTlctVmA5Y/tasks/independent-assessments

**Comment by lloback** [comment]
To Do
=====
[ ] Assessments. Save `filePath`
[ ] Assessments. Download link should use new `filePath` and fall back to existing
[ ] Admin. Upload assessment path should be:
/exercise/{exerciseId}/application/{applicationId}/assessor/jac/
  :assessmentId.pdf
[ ] Admin. Save `filePath`
[ ] Admin. Download link should use new `filePath` and fall back to existing
[x] Platform. Update rules
