### ISSUE TITLE
Please remove these exercises 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#975]
Please remove the following exercises from Admin: 

00060: https://admin.judicialappointments.digital/exercises/zZTQqtcmleUOl1R0jB55/
00058: https://admin.judicialappointments.digital/exercises/9jzuBY9x1FJKQTC3P1Af/
00059: https://admin.judicialappointments.digital/exercises/tzRfCKHghP7856ai6T37/

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle assigned to you but basically need these 3 removed please :) They are either made by mistake or duplicates.

**Comment by warrensearle** [comment]
Have interpreted this request as we're going to allow exercises in Draft mode and without any applications to be deleted by JAC Admin users.
