### ISSUE TITLE
Write test script for invite-only exercises

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#982]
Add a test script for Invite-only Exercises from the Admin perspective. See Epic admin#915 for requirements to be tested

Test scripts are stored in a Google Sheet [here](https://drive.google.com/drive/folders/142leRfwBIMZQbmZXivGzhcYrYTUfYUOS)

**Comment by lloback** [comment]
The work for this task was carried out on the 20OCTB sprint. If new work is needed for this task, we should open a new task and add the work needed.
I am closing this task today.
