### ISSUE TITLE
Schedule 2(d) information not pulling through to admin 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#987]
**Describe the bug**
When someone indicates on Apply they are applying via Schedule 2(d) this does not appear in the application 

**To Reproduce**
1. Go to https://admin.judicialappointments.digital/exercises/OPwPPwNPeiNz4VmnFbNU/applications/applied/application/k6RfemfjtuVjS5WAtwlx
2. Go to Qualifications 
3. No info is there when the answer to if they are applying under 2(d) is yes

**Expected behavior**
See that they have qualified under Schedule 2(d) 

**Screenshots**

Info in firebase is coming up 
![Screenshot 2020-10-28 at 14.22.03.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/b63bab2e-3ba5-47d6-8166-c82cbf355014)

**Additional context**
Can we also check it works where Schedule 2(3) applies. Thanks.

**Comment by warrensearle** [comment]
@tomlovesgithub you happy to take a look at this one?
