### ISSUE TITLE
Search not working on production 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#990]
**Describe the bug**
The search does not work on production as it does on staging. 

**To Reproduce**
1. Go to admin production
2. Click on candidates
3. Type a name such as 'Warren' 

**Expected behavior**
Should see candidates with that name. 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/26eef5c7-360c-4e2d-8757-78a040d0f6aa)

**Comment by mbrookeswebdev** [comment]
I've checked both production and staging, there were a few iterations of this functionality since the ticket was written, it looks like everything works as expected.
