### ISSUE TITLE
New FilterButton component

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#992]
As an admin I want to clearly be able to see certain candidates, for example those who have passed a scenario test, in a list. This helps in updating statuses and checking information. 

I need a 'Filter' button. 

Design:

![Search:Sort:Filter Default desktop.jpg](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/246d8ec5-8a17-495a-9a4f-a48946ab1eac)

Applies to all tables/lists. What you filter needs to vary depending on the list.

**Comment by warrensearle** [comment]
@tomlovesgithub could you create a FilterButton component too. It's basically a regular button however can display a 'bubble' with number in it to indicate the number of filters that have been selected. It should be standalone and separate to the Filter component for now.

[screen grab of number 'bubble' coming soon]
