### ISSUE TITLE
Filter component 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#993]
As an admin I need to be able to choose what I want to filter and then apply this. The design is a pop up bar comes up at the right side for the admin to select this. 

![Filter - Filter default.jpg](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/1766575d-5c87-4909-837c-0a8dfc1b6cb3)![Filter - Filter selected.jpg](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/dbc32fab-1606-49b4-b643-ec45b5c5e10a)

Applies to all tables/lists.

**Comment by warrensearle** [comment]
@tomlovesgithub could you make a start on this component. Make it a standalone component for now though we might end up making it part of the Table component.
