### ISSUE TITLE
Mobile implementation for tables

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#995]
See mobile designs:

![Filter Mobile.jpg](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/a027d039-d6e8-496f-860a-3a5aefc2c15b)

![Filter applied mobile.jpg](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/e56edf15-5cd3-4f13-b1b3-231aa0d6e124)

**Comment by warrensearle** [comment]
Hey @lloback @tomlovesgithub @mbrookeswebdev I've added us all to this ticket. Thinking this can be worked on in JAC Kit and we can all see/try how well that helps with developing responsive UIs.

**Comment by KateMJAC** [comment]
Reviewed on iPhone, when clicked on top right menu link 'Exercises', I could see all exercies displayed in a table format as in the above prototype. 

Ticket #543 will address implentation on other views listed in ticket #430.
