### ISSUE TITLE
Search should be keyword search

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#997]
As an admin I find it frustrating that if a candidate types in capitals or starts their name with a name other than their surname/first name I cannot find them as I have to search precisely what they have applied with e.g. if someone puts WARREN SEARLE I cannot find the if I type warren. We need to replace this with a key word search so there is more flexibility. 

You need to also be able to search by: 
- Email
- Reference number (the bit after the dash)

We may need flexibility here in case that list expands:

**Comment by warrensearle** [comment]
A solution for keyword search, without using as external service like Algolia or Elastic Search, has been tried and tested under this ticket and is being rolled out under tickets [TBC]
